Repository ManimCommunity/manim, pull requests merged in 2020-06, with the labels that each got.

#122 Create z_index to define layer for Mobjects
  manim/camera/camera.py
  manim/mobject/mobject.py
Labels: new feature

#126 Removed Argparse from requirements and setup.py
  requirements.txt
  setup.py
Labels: cleaning

#130 Fix #125 by adding custom .interpolate method for ValueTracker
  manim/mobject/mobject.py
  manim/mobject/value_tracker.py
Labels: bug

#131 Complete rewrite of TeX template management
  example_scenes/custom_template.tex
  example_scenes/customtex.py
  manim/__init__.py
  manim/__main__.py
  manim/config.py
  manim/constants.py
  manim/mobject/svg/tex_mobject.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
Labels: new feature

#127 Add Contribution guideline in Readme
  CONTRIBUTING.md
  README.md
  readme-assets/pull-requests.PNG
Labels: documentation, github

#137 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: github

#121 Make GraphScene more customizable
  manim/mobject/number_line.py
  manim/scene/graph_scene.py
Labels: enhancement

#144 Cleaning up pycairoinstall.py
  scripts/pycairoinstall.py
Labels: documentation

#142 Re-Add GIF export
  manim/extract_scene.py
  manim/scene/scene_file_writer.py
Labels: bug
