Repository ManimCommunity/manim, pull requests merged in 2020-08, with the labels that each got.

#224 Stop adding extra Partial Movie Files to final video.
  manim/scene/scene_file_writer.py
Labels: bug

#229 Add config entries for `default_pixel_width` and `default_pixel_height`
  manim/camera/camera.py
  manim/config.py
  manim/scene/scene_file_writer.py
Labels: bug

#219 Custom config file also when not run from CLI
  manim/utils/config_utils.py
Labels: bug

#212 Implement a basic Subcommand structure.
  docs/source/conf.py
  logo/logo.py
  manim/__main__.py
  manim/config.py
  manim/utils/cfg_subcmds.py
  manim/utils/cfgwriter.py
  manim/utils/config_utils.py
  manim/utils/file_ops.py
  scripts/pycairoinstall.py
  setup.py
  tests/conftest.py
  tests/test_cli/manim.cfg
  tests/test_cli/test_cfg_subcmd.py
  tests/test_cli/test_cli.py
  tests/test_cli/write_cfg_sbcmd_input.txt
Labels: enhancement, refactor/rework

#180 Implement Logging of Terminal Output to a .log file.
  manim/default.cfg
  manim/logger.py
  manim/scene/scene_file_writer.py
  manim/utils/cfg_subcmds.py
  manim/utils/config_utils.py
  tests/test_cli/test_cfg_subcmd.py
  tests/test_cli/write_cfg_sbcmd_input.txt
  tests/test_logging/expected.txt
  tests/test_logging/test_logging.py
  tests/tests_data/manim.cfg
Labels: enhancement, new feature

#218 Verbose
  manim/__main__.py
  manim/config.py
  manim/constants.py
  manim/default.cfg
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/config_utils.py
Labels: enhancement

#266 New function for GraphScene: area between two curves
  manim/scene/graph_scene.py
Labels: new feature

#268 Modify repetitive comment in requirements.txt
  requirements.txt
Labels: enhancement

#166 Added Scene caching
  manim/default.cfg
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/config_utils.py
  manim/utils/file_ops.py
  manim/utils/hashing.py
  tests/conftest.py
  tests/test_cli/test_cfg_subcmd.py
  tests/test_cli/write_cfg_sbcmd_input.txt
  tests/test_logging/expected.txt
  tests/test_logging/test_logging.py
  tests/testing_utils.py
  tests/tests_data/manim.cfg
Labels: enhancement, new feature

#259 Organised Subcommand Selection, Extended cfg writing abilities, Added cfg option to disable timestamps.
  manim/default.cfg
  manim/logger.py
  manim/utils/cfg_subcmds.py
  manim/utils/config_utils.py
  tests/test_cli/write_cfg_sbcmd_input.txt
  tests/test_logging/expected.txt
  tests/test_logging/test_logging.py
  tests/tests_data/manim.cfg
Labels: enhancement

#278 Set MacOS's Config File path to '~/.config/manim/manim.cfg'
  manim/utils/config_utils.py
Labels: enhancement

#281 # Changes in camera.py to fix fixed frame option in 3D
  manim/camera/camera.py
Labels: bug

#289 Document some of the constants that are exposed to the end user
  manim/constants.py
Labels: documentation

#296 Show read cfg files in DEBUG mode only; change default testing mode to DEBUG
  manim/__main__.py
  manim/config.py
  manim/constants.py
  manim/default.cfg
  manim/utils/config_utils.py
  tests/test_cli/manim.cfg
  tests/test_logging/expected.txt
  tests/tests_data/manim.cfg
Labels: enhancement

#291 Convenient py-script to quickly build and load the docs
  scripts/make_and_open_docs.py
Labels: enhancement

#277 Makes windows build faster, by using a prebuild Latex from TinyTex CI and avoid using Choco
  .github/workflows/ci.yml
Labels: cleaning, enhancement

#292 Cleanup and document Container class
  docs/source/reference.rst
  manim/container.py
  manim/container/container.py
  manim/mobject/mobject.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/scene/scene.py
Labels: documentation, enhancement

#297 # Docs-Chapters rearranged
  docs/source/_static/quickstart/first_scene_4k.gif
  docs/source/changelog.rst
  docs/source/contributing.md
  docs/source/examples.md
  docs/source/examples/examples_index.rst
  docs/source/examples/hello_example.md
  docs/source/index.rst
  docs/source/installation/installation_arch.rst
  docs/source/installation/installation_index.rst
  docs/source/installation/installation_mac.rst
  docs/source/installation/installation_ubuntu.rst
  docs/source/installation/installation_win.rst
  docs/source/reference.rst
  docs/source/tutorials/a_deeper_look.md
  docs/source/tutorials/quickstart.md
  docs/source/tutorials/tutorials_index.rst
Labels: cleaning, documentation

#303 Documenting the config system
  CONTRIBUTING.md
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/contributing.md
  docs/source/examples.md
  docs/source/installation/installation_arch.rst
  docs/source/installation/installation_ubuntu.rst
  docs/source/installation/installation_win.rst
  docs/source/readme-assets/pull-requests.PNG
  docs/source/reference.rst
  docs/source/tutorials/configuration.rst
  docs/source/tutorials/tutorials_index.rst
  manim/config.py
  manim/default.cfg
  manim/utils/config_utils.py
Labels: documentation

#304 Check for add in VGroup
  manim/mobject/types/vectorized_mobject.py
  tests/test_vectorized_mobject.py
Labels: bug

#307 add unit tests for Container class
  manim/mobject/mobject.py
  tests/test_container.py
Labels: testing

#316 Support VDict init from python dict of mobjects
  example_scenes/basic.py
  manim/mobject/types/vectorized_mobject.py
  tests/test_vectorized_mobject.py
  tests/tests_cache/writing/TextTest/Text/space.svg
Labels: enhancement

#240 remove_stray_braces quickfix
  manim/mobject/svg/tex_mobject.py
Labels: bug

#318 refactor copy/deepcopy. Closes #294
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  manim/mobject/probability.py
  manim/mobject/svg/brace.py
  manim/mobject/types/image_mobject.py
  tests/test_copy.py
  tests/tests_data/deepcopy/Tex/b26c2d37c7d91fb6.aux
  tests/tests_data/deepcopy/Tex/b26c2d37c7d91fb6.dvi
  tests/tests_data/deepcopy/Tex/b26c2d37c7d91fb6.svg
  tests/tests_data/deepcopy/Tex/b26c2d37c7d91fb6.tex
  tests/tests_data/deepcopy/Tex/bb964ccc0ded6db8.aux
  tests/tests_data/deepcopy/Tex/bb964ccc0ded6db8.dvi
  tests/tests_data/deepcopy/Tex/bb964ccc0ded6db8.svg
  tests/tests_data/deepcopy/Tex/bb964ccc0ded6db8.tex
Labels: refactor/rework

#330 Replace some setters and getters from Camera
  manim/camera/camera.py
  manim/camera/mapping_camera.py
  manim/camera/multi_camera.py
  manim/camera/three_d_camera.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/zoomed_scene.py
Labels: enhancement

#326 Refactor batch_by_property
  manim/camera/camera.py
  manim/utils/iterables.py
Labels: cleaning, enhancement

#347 Docs
  docs/source/_static/custom.css
  docs/source/_templates/autosummary/class.rst
  docs/source/conf.py
  manim/animation/animation.py
  manim/animation/composition.py
  manim/animation/creation.py
  manim/animation/fading.py
  manim/camera/camera.py
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  manim/mobject/number_line.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/scene.py
Labels: Easy review, documentation

#340 Refactor config
  manim/__init__.py
  manim/camera/camera.py
  manim/config.py
  tests/test_camera.py
  tests/test_config.py
  tests/test_logging/expected.txt
Labels: Easy review, refactor/rework

#372 fix links to basic.py, custom_template.tex and customtex.py in readme
  README.md
Labels: Easy review, bug

#381 Read The Docs setup
  docs/requirements.txt
  docs/source/tutorials/configuration.rst
Labels: Easy review, documentation

#378 Make 1080p default video resolution
  manim/default.cfg
Labels: Easy review

#370 Use Cacheing in Github Actions
  .github/manimdependency.json
  .github/workflows/ci.yml
Labels: github

#383 Make the README point to the RTD docs
  CONTRIBUTING.md
  README.md
  docs/source/contributing.md
Labels: Easy review, documentation
