Repository ManimCommunity/manim, pull requests merged in 2020-11, with the labels that each got.

#658 Anchors for example blocks in documentation
  docs/source/_static/custom.css
  docs/source/manim_directive.py
Labels: Easy review, documentation

#662 Mention poetry installation via brew.
  docs/source/installation/for_dev.rst
Labels: Easy review, documentation, enhancement

#672 Fix typo in troubleshooting guide
  docs/source/installation/troubleshooting.rst
Labels: Easy review, documentation

#661 graph_scene: correct placement of labels
  manim/scene/graph_scene.py
  tests/control_data/graphical_units_data/graph/AxesTest.npz
  tests/control_data/graphical_units_data/graph/PlotFunctions.npz
  tests/test_graphical_units/test_axes.py
Labels: Easy review, bug

#678 Added example ShowScreenResolution
  docs/source/examples/shapes_images_positions.rst
Labels: Easy review

#682 document workaround for a weird issue with zlib
  docs/source/installation/troubleshooting.rst
Labels: Easy review, documentation

#683 Remove two removed modules from reference manual
  docs/source/reference.rst
Labels: Easy review, documentation

#684 Add basic opengraph metadata to documentation
  docs/requirements.txt
  docs/source/conf.py
Labels: Easy review, documentation, sphinx

#685 Add shortcut for creating links to issues and PRs in the documentation
  docs/source/changelog.rst
  docs/source/conf.py
Labels: Easy review, documentation, sphinx

#680 Added space in example that is not shown in docs
  docs/source/examples/3d.rst
Labels: Easy review

#647 Direction methods (VMobject)
  manim/mobject/types/vectorized_mobject.py
  manim/utils/space_ops.py
Labels: new feature

#586 Clean up README
  README.md
  docs/source/_static/command.png
  readme-assets/command.png
  readme-assets/pull-requests.PNG
  readme-assets/windows_cairo.png
  readme-assets/windows_miktex.png
  readme-assets/windows_sox.png
Labels: documentation

#681 Bring back support for docker
  README.md
  docker/Dockerfile
  docker/texlive-profile.txt
  docs/source/installation.rst
Labels: enhancement

#691 Succession honors individual animations run times
  manim/animation/composition.py
  tests/test_composition.py
Labels: enhancement

#703 Add links from reference manual to source code on GitHub
  docs/source/conf.py
Labels: documentation, sphinx

#580 Fix shift in axis in GraphScene
  docs/source/changelog.rst
  manim/scene/graph_scene.py
  tests/test_axes_shift.py
Labels: Test Requested

#693 Added BraceBetweenPoints and some documentation
  manim/mobject/svg/brace.py
Labels: enhancement, new feature

#697 Add js_renderer to Extras
  .github/workflows/ci.yml
  docs/source/changelog.rst
  manim/__init__.py
  manim/__main__.py
  poetry.lock
  pyproject.toml
Labels: easy review, enhancement

#706 More color changes
  docs/source/_static/custom.css
Labels: documentation, sphinx

#714 Be more flexible about installed Manim version in Dockerfile
  docker/Dockerfile
Labels: easy review, infrastructure

#715 allow pycairo ^1.19
  poetry.lock
  pyproject.toml
Labels: easy review, enhancement, installation

#716 Make it easier to change background color
  manim/camera/camera.py
  manim/scene/scene.py
  tests/test_color.py
Labels: enhancement

#701 Enable rendering type hints (PEP 484)
  docs/source/conf.py
Labels: documentation, easy review, sphinx

#720 Fix CI build issue
  .github/workflows/ci.yml
Labels: bug, infrastructure

#687 Reorganize example gallery
  docs/source/examples.rst
  docs/source/examples/3d.rst
  docs/source/examples/advanced_projects.rst
  docs/source/examples/animations.rst
  docs/source/examples/annotations.rst
  docs/source/examples/camera_settings.rst
  docs/source/examples/formulas.rst
  docs/source/examples/plots.rst
  docs/source/examples/shapes_images_positions.rst
  docs/source/examples/tex.rst
  docs/source/manim_directive.py
  docs/source/tutorials/configuration.rst
  manim/animation/fading.py
  manim/animation/transform.py
  manim/mobject/functions.py
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  manim/mobject/numbers.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/graph_scene.py
  manim/scene/moving_camera_scene.py
  manim/scene/scene.py
  manim/scene/zoomed_scene.py
Labels: documentation

#725 Example Gallery: Remove z_index from the first example
  docs/source/examples.rst
Labels: easy review

#736 A typo in a comment? That cannot stand!
  manim/animation/animation.py
Labels: easy review

#730 Fix 389: document that ShowCreation only works for vectorized mobjects
  manim/animation/creation.py
  manim/animation/indication.py
Labels: cleaning, documentation, easy review

#630 feat: migrate to Pathlib
  manim/utils/images.py
  manim/utils/module_ops.py
  manim/utils/sounds.py
Labels: enhancement

#744 Fix docbuild warning
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/installation/win.rst
  docs/source/manim_directive.py
  docs/source/tutorials/configuration.rst
  manim/_config/utils.py
  manim/animation/transform.py
  manim/camera/multi_camera.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/scene.py
  manim/utils/hashing.py
Labels: documentation, easy review

#755 Fix "-" as filename feature.
  manim/utils/module_ops.py
Labels: easy review

#754 Allow for Developer Installations Without Poetry
  pyproject.toml
Labels: easy review, enhancement, installation

#707 Add ArcPolygon to geometry.py
  manim/mobject/geometry.py
Labels: new feature

#743 Fix typo in import statement
  manim/__main__.py
  tests/helpers/video_utils.py
Labels: bug, easy review

#785 Fix typo in example.rst
  docs/source/examples.rst
Labels: easy review
