Repository ManimCommunity/manim, pull requests merged in 2020-09, with the labels that each got.

#395 Fix to allow for passing height only with -r flag
  manim/config.py
Labels: Easy review, bug

#390 Enable module doctests
  .github/workflows/ci.yml
  manim/animation/__init__.py
  manim/camera/__init__.py
  manim/mobject/__init__.py
  manim/mobject/mobject.py
  manim/mobject/svg/__init__.py
  manim/mobject/types/__init__.py
  manim/scene/__init__.py
  manim/utils/__init__.py
Labels: Easy review, documentation, enhancement

#376 Create config subpackage
  manim/__init__.py
  manim/__main__.py
  manim/animation/fading.py
  manim/animation/indication.py
  manim/camera/camera.py
  manim/camera/moving_camera.py
  manim/camera/three_d_camera.py
  manim/config/__init__.py
  manim/config/cfg_subcmds.py
  manim/config/config.py
  manim/config/config_utils.py
  manim/config/default.cfg
  manim/config/logger.py
  manim/mobject/coordinate_systems.py
  manim/mobject/frame.py
  manim/mobject/functions.py
  manim/mobject/mobject.py
  manim/mobject/number_line.py
  manim/mobject/svg/drawings.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/vector_field.py
  manim/scene/graph_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/three_d_scene.py
  manim/scene/vector_space_scene.py
  manim/utils/hashing.py
  manim/utils/tex_file_writing.py
  setup.py
  tests/test_cli/manim.cfg
  tests/test_imports.py
Labels: Easy review, cleaning, refactor/rework

#396 Automated Black Updates
  .github/workflows/black.yml
Labels: Easy review, cleaning, enhancement

#374 Add tests for mobject.get_family()
  tests/test_family.py
Labels: testing, waiting for another pr's merge

#400 Quick Mobject docs patch
  manim/mobject/mobject.py
Labels: Easy review, documentation, enhancement

#391 Deprecate `TexMobject` and `TextMobject` in favour of `MathTex` and `Tex`
  docs/source/installation/linux.rst
  example_scenes/basic.py
  example_scenes/customtex.py
  logo/logo.py
  manim/mobject/coordinate_systems.py
  manim/mobject/matrix.py
  manim/mobject/numbers.py
  manim/mobject/probability.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/drawings.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/graph_scene.py
  manim/scene/vector_space_scene.py
  tests/test_logging/basic_scenes.py
Labels: enhancement

#366 Custom Arrow Tips
  manim/mobject/geometry.py
  tests/control_data/graphical_units_data/geometry/CustomDoubleArrowTest.npy
  tests/control_data/graphical_units_data/geometry/DoubleArrowTest.npy
  tests/test_graphical_units/test_geometry.py
Labels: Test Requested, enhancement, new feature

#397 Stop using config at import
  manim/camera/moving_camera.py
  manim/camera/three_d_camera.py
  manim/mobject/coordinate_systems.py
  manim/mobject/frame.py
  manim/mobject/functions.py
  manim/mobject/mobject.py
  manim/mobject/number_line.py
  manim/mobject/svg/drawings.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/vector_field.py
  manim/scene/three_d_scene.py
  manim/scene/vector_space_scene.py
  tests/test_coordinate_system.py
  tests/test_graphical_units/test_graph.py
Labels: enhancement, refactor/rework

#380 Add the Variable class with an example
  docs/source/changelog.rst
  example_scenes/basic.py
  manim/mobject/numbers.py
Labels: help wanted, new feature

#384 Rewrite contributing guide and add two troubleshooting soulutions
  docs/source/contributing.md
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/installation/troubleshooting.rst
  docs/source/reporting_bugs.rst
Labels: Easy review, documentation

#416 Fix File Not Found Error - Github Actions
  .github/workflows/black-pr.yml
  .github/workflows/black.yml
Labels: Easy review, github

#315 Miscellaneous Scene-Caching Optimisations and Bugfixes.
  manim/__main__.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/hashing.py
  tests/test_hashing.py
  tests/test_logging/expected.txt
Labels: bug, enhancement, refactor/rework

#424 Remove Documentation caption from sidebar
  docs/source/index.rst
Labels: Easy review, enhancement

#388 Fix MovingCamera and ZoomedScene
  manim/camera/moving_camera.py
  manim/mobject/mobject.py
  manim/mobject/types/image_mobject.py
  manim/scene/zoomed_scene.py
Labels: Easy review, bug

#427 Scene caching optimisation but ignoring mappingproxy
  manim/utils/hashing.py
Labels: Easy review, enhancement

#165 Move to Poetry
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  README.md
  docs/requirements.txt
  docs/source/changelog.rst
  docs/source/installation.rst
  docs/source/installation/for_dev.rst
  poetry.lock
  pyproject.toml
  pytest.ini
  setup.py
Labels: enhancement, github, new feature

#428 fix formatting of warning block in installation.rst
  docs/source/installation.rst
Labels: Easy review, documentation

#402 Render videos while building documentation
  .readthedocs.yml
  docs/Makefile
  docs/rtd-requirements.txt
  docs/source/_static/custom.css
  docs/source/_static/quickstart/first_scene.gif
  docs/source/_static/quickstart/high_quality.gif
  docs/source/_static/quickstart/second_scene.gif
  docs/source/conf.py
  docs/source/manim_directive.py
  docs/source/tutorials/a_deeper_look.rst
  docs/source/tutorials/quickstart.rst
  manim/mobject/geometry.py
  manim/utils/hashing.py
Labels: documentation, enhancement, sphinx

#430 Make output file names unique when rendering videos in documentation
  docs/source/manim_directive.py
Labels: Easy review, enhancement, sphinx

#434 Fix typo in camera.py
  manim/camera/camera.py
Labels: Easy review

#394 New tutorial: manim internals basic
  docs/source/_static/building_blocks/addremove.gif
  docs/source/_static/building_blocks/placement.png
  docs/source/_static/building_blocks/shapes.png
  docs/source/_static/building_blocks/styling.png
  docs/source/_static/building_blocks/zorder.png
  docs/source/tutorials.rst
  docs/source/tutorials/building_blocks.rst
  docs/source/tutorials/quickstart.rst
Labels: Easy review, documentation

#435 manim-directive: more robust paths, set (and create) tex/text directories
  docs/source/manim_directive.py
Labels: Easy review, bug, sphinx

#436 remove unneeded static files in docs
  docs/source/_static/building_blocks/addremove.gif
  docs/source/_static/building_blocks/placement.png
  docs/source/_static/building_blocks/shapes.png
  docs/source/_static/building_blocks/styling.png
  docs/source/_static/building_blocks/zorder.png
Labels: Easy review, cleaning, documentation

#403 Refactored logs and added log-to-json feature (removed the old log-to-file feature), added logging test utils.
  docs/source/changelog.rst
  manim/__main__.py
  manim/config/config.py
  manim/config/config_utils.py
  manim/config/default.cfg
  manim/config/logger.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/hashing.py
  tests/control_data/logs_data/BasicSceneLoggingTest.txt
  tests/test_logging/__init__.py
  tests/test_logging/basic_scenes.py
  tests/test_logging/expected.txt
  tests/test_logging/test_logging.py
  tests/test_logging/testloggingconfig.cfg
  tests/utils/logging_tester.py
Labels: Test Requested, enhancement

#440 Align Images in Mobile - Sphinx
  docs/source/_static/custom.css
Labels: Easy review, sphinx

#439 Installing using chocolatey for windows
  docs/source/installation/win.rst
Labels: Easy review, documentation

#423 Fix n flag
  manim/config/config_utils.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  tests/control_data/videos_data/SceneWithMultipleCallsWithNFlag.json
  tests/helpers/video_utils.py
  tests/test_scene_rendering/simple_scenes.py
  tests/test_scene_rendering/test_cli_flags.py
Labels: Easy review, bug

#198 Fixed Some bugs of code_mobject.py and Text_mobject.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: Changes requested and not yet done, bug, documentation, enhancement

#438 Improve/extend reference manual
  docs/source/_templates/autosummary/class.rst
  docs/source/reference.rst
  manim/animation/growing.py
  manim/animation/indication.py
  manim/animation/movement.py
  manim/animation/numbers.py
  manim/animation/rotation.py
  manim/animation/specialized.py
  manim/animation/transform.py
  manim/animation/update.py
  manim/camera/camera.py
  manim/camera/mapping_camera.py
  manim/camera/moving_camera.py
  manim/camera/multi_camera.py
  manim/camera/three_d_camera.py
  manim/mobject/changing.py
  manim/mobject/coordinate_systems.py
  manim/mobject/frame.py
  manim/mobject/functions.py
  manim/mobject/matrix.py
  manim/mobject/mobject_update_utils.py
  manim/mobject/numbers.py
  manim/mobject/probability.py
  manim/mobject/shape_matchers.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/drawings.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/three_d_shading_utils.py
  manim/mobject/three_d_utils.py
  manim/mobject/three_dimensions.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/value_tracker.py
  manim/mobject/vector_field.py
  manim/scene/graph_scene.py
  manim/scene/moving_camera_scene.py
  manim/scene/sample_space_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/three_d_scene.py
  manim/scene/vector_space_scene.py
  manim/scene/zoomed_scene.py
  manim/utils/bezier.py
  manim/utils/color.py
  manim/utils/config_ops.py
  manim/utils/debug.py
  manim/utils/file_ops.py
  manim/utils/hashing.py
  manim/utils/images.py
  manim/utils/iterables.py
  manim/utils/paths.py
  manim/utils/rate_functions.py
  manim/utils/simple_functions.py
  manim/utils/sounds.py
  manim/utils/space_ops.py
  manim/utils/strings.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
Labels: documentation, enhancement, help wanted

#446 change default for displaying source code with manim directive
  docs/source/manim_directive.py
  docs/source/tutorials/a_deeper_look.rst
  docs/source/tutorials/building_blocks.rst
  docs/source/tutorials/quickstart.rst
  manim/mobject/changing.py
  manim/mobject/geometry.py
  manim/mobject/value_tracker.py
Labels: Easy review, sphinx

#444 # Added examples for GraphScene to docs
  docs/source/examples/plots_examples.rst
Labels: Easy review, documentation

#445 New sections for the sphinx-example page
  docs/source/examples.rst
  docs/source/examples/3d.rst
  docs/source/examples/advanced_projects.rst
  docs/source/examples/animations.rst
  docs/source/examples/annotations.rst
  docs/source/examples/camera_settings.rst
  docs/source/examples/formulas.rst
  docs/source/examples/hello_example.rst
  docs/source/examples/neat_projects.rst
  docs/source/examples/plots.rst
  docs/source/examples/shapes.rst
  docs/source/examples/text.rst
Labels: documentation

#449 fix RTD documentation build for non-master branches
  docs/requirements.txt
  docs/rtd-requirements.txt
  manim/mobject/geometry.py
Labels: Easy review, documentation

#463 add manim_directive module to reference manual
  docs/source/contributing.md
  docs/source/contributing.rst
  docs/source/manim_directive.py
Labels: Easy review, documentation, enhancement

#481 Missingspace
  manim/mobject/svg/tex_mobject.py
Labels: cleaning, enhancement

#479 [ci] Fix ffmpeg Url
  .github/manimdependency.json
  .github/workflows/ci.yml
Labels: Easy review

#482 Fixed "get_arc_center()" method of Arc class
  manim/mobject/geometry.py
  tests/test_unit_geometry.py
Labels: bug

#468 fix #460 by enabling skipping wait statements.
  manim/scene/scene.py
  tests/control_data/videos_data/SceneWithMultiplePlayCallsWithNFlag.json
  tests/control_data/videos_data/SceneWithMultipleWaitCallsWithNFlag.json
  tests/test_scene_rendering/simple_scenes.py
  tests/test_scene_rendering/test_caching_relalted.py
Labels: Easy review, testing

#493 [Supereasy] Fix some missing newlines before code blocks in Sphinx
  manim/mobject/geometry.py
  manim/utils/color.py
Labels: Easy review, documentation
