Repository ManimCommunity/manim, pull requests merged in 2020-12, with the labels that each got.

#793 fix 780
  manim/mobject/coordinate_systems.py
  manim/scene/vector_space_scene.py
Labels: easy review

#799 fix the URL of the ffmpeg release for windows
  .github/manimdependency.json
Labels: easy review, infrastructure

#798 make Paragraph use CairoText
  manim/mobject/svg/text_mobject.py
Labels: easy review, enhancement

#807 ManimBanner: fix miscalculated m_shape_offset
  manim/mobject/logo.py
Labels: easy review

#803 Docker: use local files when building an image
  docker/Dockerfile
  playground/readme.md
Labels: easy review, infrastructure

#813 move playground/readme --> docker/readme
  docker/readme.md
Labels: easy review

#812 Update the changelog for our latest release
  .github/PULL_REQUEST_TEMPLATE.md
  docs/source/changelog.rst
Labels: docs, easy review

#815 Post-release update for docker readme
  .dockerignore
  docker/readme.md
Labels: easy review, infrastructure

#814 add creation animation for ManimBanner
  docs/source/changelog.rst
  manim/mobject/logo.py
Labels: easy review, enhancement

#783 remove all CONFIG and all digest_config
  docs/source/examples.rst
  manim/animation/animation.py
  manim/animation/composition.py
  manim/animation/creation.py
  manim/animation/fading.py
  manim/animation/growing.py
  manim/animation/indication.py
  manim/animation/movement.py
  manim/animation/numbers.py
  manim/animation/rotation.py
  manim/animation/transform.py
  manim/animation/update.py
  manim/camera/camera.py
  manim/camera/mapping_camera.py
  manim/camera/moving_camera.py
  manim/camera/multi_camera.py
  manim/camera/three_d_camera.py
  manim/constants.py
  manim/container.py
  manim/mobject/changing.py
  manim/mobject/coordinate_systems.py
  manim/mobject/frame.py
  manim/mobject/functions.py
  manim/mobject/geometry.py
  manim/mobject/matrix.py
  manim/mobject/mobject.py
  manim/mobject/number_line.py
  manim/mobject/numbers.py
  manim/mobject/probability.py
  manim/mobject/shape_matchers.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/three_dimensions.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/renderer/cairo_renderer.py
  manim/scene/graph_scene.py
  manim/scene/moving_camera_scene.py
  manim/scene/reconfigurable_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/three_d_scene.py
  manim/scene/vector_space_scene.py
  manim/scene/zoomed_scene.py
  manim/utils/config_ops.py
  manim/utils/rate_functions.py
  manim/utils/tex.py
  tests/test_graphical_units/test_axes.py
  tests/test_graphical_units/test_graph.py
  tests/test_renderer.py
  tests/utils/GraphicalUnitTester.py
Labels: breaking changes, cleaning, refactor

#817 Removed temporary partial movie file in scenefilewriter
  docs/source/changelog.rst
  manim/scene/scene_file_writer.py
Labels: cleaning, enhancement

#753 Add some documentation to Scene.construct
  manim/animation/creation.py
  manim/animation/indication.py
  manim/scene/scene.py
Labels: docs, enhancement

#794 `manimce` to `manim` & capitalizing Manim in readme
  .github/workflows/python-publish.yml
  README.md
  docs/source/installation.rst
  docs/source/installation/troubleshooting.rst
  poetry.lock
  pyproject.toml
  scripts/twitter_post_template.py
Labels: docs, easy review

#826 Add monochromatic versions of logo
  logo/monochromatic/monochromatic_black.svg
  logo/monochromatic/monochromatic_white.svg
Labels: easy review

#784 Feature plugins
  docs/source/changelog.rst
  docs/source/installation.rst
  docs/source/installation/plugins.rst
  manim/__init__.py
  manim/__main__.py
  manim/_config/main_utils.py
  manim/plugins/.gitignore
  manim/plugins/plugins_flags.py
Labels: enhancement

#825 Better creation Example in docs & buff parameter in arrange
  manim/animation/creation.py
  manim/mobject/mobject.py
  tests/control_data/graphical_units_data/geometry/ArrangeTest.npz
  tests/template_generate_graphical_units_data.py
  tests/test_graphical_units/test_geometry.py
Labels: docs

#832 Update Docs Url
  README.md
  example_scenes/basic.py
  manim/utils/tex_file_writing.py
  pyproject.toml
Labels: easy review

#804 Allow disabling ligatures in Text
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: bug

#845 fixed order of mobjects
  manim/utils/hashing.py
Labels: bug, easy review

#835 Typings
  manim/_config/__init__.py
  manim/_config/cfg_subcmds.py
  manim/_config/logger_utils.py
  manim/_config/main_utils.py
  manim/_config/utils.py
  manim/animation/animation.py
  manim/animation/composition.py
  manim/animation/creation.py
  manim/animation/fading.py
  manim/animation/growing.py
  manim/animation/indication.py
  manim/animation/movement.py
  manim/animation/numbers.py
  manim/animation/rotation.py
  manim/animation/transform.py
  manim/animation/update.py
  manim/constants.py
  manim/mobject/vector_field.py
  manim/utils/bezier.py
  manim/utils/rate_functions.py
Labels: enhancement

#820 Add examples to animation creation
  README.md
  manim/animation/creation.py
  manim/animation/indication.py
  manim/mobject/mobject.py
  scripts/template_docsting_with_example.py
  scripts/template_twitter_post.py
Labels: docs

#858 Fix CairoText
  manim/mobject/svg/text_mobject.py
Labels: bug, changes requested, easy review

#859 Add missing argument for classes inheriting from class 'Matrix'
  manim/mobject/matrix.py
Labels: bug, easy review

#660 added ambient rotate for other angles - theta, phi, gamma (take 2)
  manim/scene/three_d_scene.py
Labels: easy review

#833 added DashedLine and CurvesAsSubmobjects example to docs
  docs/source/examples.rst
  manim/mobject/geometry.py
  manim/mobject/types/vectorized_mobject.py
Labels: docs

#855 Markup text
  docs/source/changelog.rst
  manim/mobject/svg/text_mobject.py
Labels: bug, enhancement

#867 Remove old str.format() syntax and change to f-Strings
  manim/animation/numbers.py
  manim/animation/transform.py
  manim/mobject/mobject.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/caching.py
  manim/utils/file_ops.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
  tests/utils/GraphicalUnitTester.py
Labels: easy review, refactor

#872 Properly respect submobjects when sorting by z_index
  manim/mobject/svg/tex_mobject.py
  manim/utils/family.py
  tests/control_data/graphical_units_data/geometry/ZIndexTest.npz
  tests/test_graphical_units/test_geometry.py
Labels: easy review

#827 Added Fading example and removed Fade methods (deprecation)
  manim/animation/fading.py
  tests/control_data/graphical_units_data/creation/FadeInFromDownTest.npz
  tests/test_graphical_units/test_creation.py
Labels: breaking changes, docs

#795 Various cleanup changes
  manim/camera/camera.py
  manim/camera/three_d_camera.py
Labels: easy review, refactor

#883 Allow chaining on `ParametricSurface.set_fill_by_checkerboard`
  manim/mobject/three_dimensions.py
Labels: easy review, enhancement

#884 Modify DashedVMobject to have an even dash pattern for closed shapes.
  manim/mobject/types/vectorized_mobject.py
Labels: easy review, enhancement

#861 Basic implementation of undirected graphs
  docs/source/reference.rst
  manim/__init__.py
  manim/mobject/graph.py
  poetry.lock
  pyproject.toml
  tests/control_data/graphical_units_data/plot/AxesTest.npz
  tests/control_data/graphical_units_data/plot/PlotFunctions.npz
  tests/test_graph.py
  tests/test_graphical_units/test_axes.py
  tests/test_graphical_units/test_graphscene.py
Labels: new feature
