Repository ManimCommunity/manim, pull requests merged in 2020-10, with the labels that each got.

#499 Make VGroup and VDict printable
  docs/source/changelog.rst
  manim/mobject/mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: Easy review

#490 docs: add manim latex chocolatey package
  docs/source/installation/win.rst
Labels: Easy review, documentation

#457 More tex options
  docs/source/changelog.rst
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
Labels: enhancement

#504 Fix windows CI
  .github/workflows/ci.yml
  poetry.lock
  pyproject.toml
Labels: testing

#509 FEAT : Add increment using += support for ValueTracker
  docs/source/changelog.rst
  manim/mobject/value_tracker.py
  tests/test_value_tracker.py
Labels: Easy review, enhancement

#520 Fix docs for `Variable` and remove some unused imports
  manim/mobject/numbers.py
Labels: Easy review, documentation

#519 Fix bug in axes
  manim/mobject/coordinate_systems.py
Labels: Easy review, bug

#531 Fix docs for VDict
  manim/mobject/types/vectorized_mobject.py
Labels: Easy review, documentation

#498 FIX : fixed tuples in hashing, by converting them to lists
  manim/utils/hashing.py
  tests/test_hashing.py
Labels: Easy review

#471 Add Pango Renderer
  .github/manimdependency.json
  .github/workflows/ci.yml
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/installation/mac.rst
  docs/source/installation/win.rst
  example_scenes/pangoText.py
  manim/constants.py
  manim/mobject/svg/text_mobject.py
  poetry.lock
  pyproject.toml
  tests/test_pango.py
Labels: new feature

#525 More examples for the docs
  docs/source/examples/advanced_projects.rst
  docs/source/examples/annotations.rst
  docs/source/examples/formulas.rst
  docs/source/examples/text.rst
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: documentation

#537 Show inheritance in Documentation
  docs/source/_templates/autosummary/class.rst
  docs/source/tutorials/configuration.rst
Labels: Easy review, documentation

#492 Make Text and Tex robust against non-existing text_dir and tex_dir
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/utils/tex_file_writing.py
Labels: Easy review, enhancement

#483 Simplifying TexTemplates and Creating Template Library
  docs/source/examples.rst
  docs/source/examples/tex.rst
  docs/source/reference.rst
  example_scenes/advanced_tex_fonts.py
  example_scenes/custom_template.tex
  example_scenes/customtex.py
  manim/__init__.py
  manim/mobject/svg/tex_mobject.py
  manim/utils/module_ops.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
  manim/utils/tex_templates.py
Labels: cleaning, enhancement

#538 Added neat projects from example_scenes folder
  docs/source/examples.rst
  docs/source/examples/advanced_projects.rst
  docs/source/examples/neat_projects.rst
  docs/source/examples/shapes_images_positions.rst
  example_scenes/basic.py
Labels: documentation

#535 Updated mobject.py, test_copy.py, and conftest.py, from os to pathlib Path
  manim/mobject/mobject.py
  tests/test_copy.py
  tests/test_scene_rendering/conftest.py
Labels: hacktoberfest, hacktoberfest-accepted

#512 Implement standard easing functions
  docs/source/_static/non_standard_rate_funcs.png
  docs/source/changelog.rst
  manim/__init__.py
  manim/utils/rate_functions.py
Labels: enhancement, help wanted, refactor/rework

#549 solve issue 542 - no requirements.txt
  requirements.txt
Labels: Easy review, cleaning

#536 Changing Exception() uses to more specific subclasses
  logo/logo.py
  manim/animation/creation.py
  manim/animation/numbers.py
  manim/animation/specialized.py
  manim/animation/transform.py
  manim/mobject/coordinate_systems.py
  manim/mobject/mobject.py
  manim/mobject/svg/drawings.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/graph_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/vector_space_scene.py
  manim/utils/color.py
  manim/utils/module_ops.py
  manim/utils/space_ops.py
Labels: enhancement

#554 Fix formatting of formulas in the readthedocs-documentation
  manim/utils/tex.py
Labels: Easy review, documentation

#546 Make manim crash when ffmpeg crashes
  docs/source/examples/3d.rst
  docs/source/installation/linux.rst
  docs/source/manim_directive.py
  manim/constants.py
  manim/scene/scene_file_writer.py
  manim/utils/caching.py
Labels: Easy review, bug, cleaning, enhancement

#558 added some words to documentation LaTeX examples
  docs/source/examples.rst
  docs/source/examples/tex.rst
  docs/source/examples/text.rst
Labels: documentation

#577 add logo to documentation
  docs/source/_static/manim-logo-sidebar.svg
  docs/source/_templates/logo-text.html
  docs/source/conf.py
Labels: Easy review, documentation

#597 Move Changelog to Main TOC
  docs/source/index.rst
  docs/source/reference.rst
Labels: Easy review, documentation

#574 fixed set test scene
  tests/helpers/graphical_units.py
Labels: Easy review

#601 remove three_d_shading_utils
  docs/source/reference.rst
  manim/mobject/three_d_shading_utils.py
Labels: cleaning

#565 Added template for the use of set_test_scene into the test folder
  tests/template_generate_graphical_units_data.py
Labels: Easy review, testing

#567 Use 'center' tex_environment instead of \centering
  .gitignore
  docs/source/changelog.rst
  manim/mobject/svg/tex_mobject.py
  manim/utils/tex.py
Labels: enhancement, refactor/rework

#562 Simplify the animation logic within Scene
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
  manim/scene/vector_space_scene.py
  poetry.lock
Labels: cleaning

#603 Added some missing information to changelog
  docs/source/changelog.rst
  docs/source/examples/shapes_images_positions.rst
Labels: Easy review, documentation

#607 Custom "Example reference"-blocks for examples with manim directive
  docs/source/_static/custom.css
  docs/source/examples/advanced_projects.rst
  docs/source/manim_directive.py
Labels: documentation, sphinx

#611 Added copy button for the sphinx page
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation, enhancement

#616 Changed all references to manimcm to manimce
  manim/config/config_utils.py
  pyproject.toml
Labels: Easy review, cleaning, enhancement

#576 New examples
  docs/source/examples.rst
  docs/source/examples/3d.rst
  docs/source/examples/advanced_projects.rst
  docs/source/examples/animations.rst
  docs/source/examples/annotations.rst
  docs/source/examples/camera_settings.rst
  docs/source/examples/formulas.rst
  docs/source/examples/plots.rst
  docs/source/examples/shapes_images_positions.rst
  docs/source/examples/tex.rst
  docs/source/installation/linux.rst
  docs/source/installation/troubleshooting.rst
  manim/mobject/types/image_mobject.py
  manim/scene/scene.py
Labels: documentation

#608 ci: upload release assets
  .github/workflows/python-publish.yml
Labels: release

#609 Make Text use Pango by default
  manim/mobject/svg/text_mobject.py
  tests/test_pango.py
Labels: enhancement

#624 Remove remaining occurrences of PangoText
  docs/source/changelog.rst
  docs/source/examples/shapes_images_positions.rst
  docs/source/examples/tex.rst
  manim/mobject/svg/text_mobject.py
Labels: Easy review, documentation

#614 Fix become bug
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
  tests/control_data/graphical_units_data/transform/FadeInAndOutTest.npz
  tests/test_graphical_units/test_transform.py
Labels: bug

#617 Improve design of documentation
  docs/source/_static/custom.css
  docs/source/index.rst
  docs/source/manim_directive.py
  docs/source/reference.rst
Labels: documentation, enhancement

#568 Create Wait Animation
  manim/animation/animation.py
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
  manim/utils/caching.py
Labels: cleaning, enhancement

#631 Add a favicon
  docs/source/_static/favicon.ico
  docs/source/conf.py
Labels: Easy review

#633 Add suggestion for resolving problem for missing `_generated.ffi` modules to troubleshooting guide
  docs/source/installation/troubleshooting.rst
Labels: Easy review, documentation

#620 Replace the global config dict with new class ManimConfig
  docs/source/manim_directive.py
  docs/source/reference.rst
  manim/__main__.py
  manim/camera/camera.py
  manim/config/__init__.py
  manim/config/default.cfg
  manim/config/logger.py
  manim/config/main_utils.py
  manim/config/utils.py
  manim/constants.py
  manim/grpc/impl/frame_server_impl.py
  manim/mobject/mobject.py
  manim/mobject/svg/text_mobject.py
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/caching.py
  manim/utils/file_ops.py
  manim/utils/module_ops.py
  manim/utils/tex_file_writing.py
  tests/control_data/logs_data/BasicSceneLoggingTest.txt
  tests/helpers/graphical_units.py
  tests/test_config.py
  tests/test_container.py
  tests/test_copy.py
  tests/test_logging/test_logging.py
  tests/test_quality_flags.py
  tests/test_scene_rendering/conftest.py
  tests/test_scene_rendering/simple_scenes.py
  tests/test_scene_rendering/test_caching_related.py
  tests/test_scene_rendering/test_cli_flags.py
  tests/utils/GraphicalUnitTester.py
Labels: enhancement, new feature

#639 Preserve new lines in code
  manim/mobject/svg/code_mobject.py
Labels: Easy review, enhancement

#462 New features: AnnotationDot and LabledDot
  manim/mobject/geometry.py
  tests/control_data/graphical_units_data/geometry/AnnotationDotTest.npy
  tests/test_graphical_units/test_geometry.py
Labels: Easy review, Test Requested, new feature

#643 Follow-up to #462: fix pipeline on master
  docs/source/changelog.rst
  tests/control_data/graphical_units_data/geometry/AnnotationDotTest.npy
  tests/control_data/graphical_units_data/geometry/AnnotationDotTest.npz
Labels: Easy review

#646 pass html_favicon as string
  docs/source/conf.py
Labels: Easy review, sphinx

#605 Auto resize Images from ImageMobject
  manim/mobject/types/image_mobject.py
  manim/utils/file_ops.py
Labels: enhancement

#644 Smol fix : replaced set_style_data by set_style
  manim/mobject/shape_matchers.py
Labels: Easy review, bug

#653 Make set_test_scene more robust when missing self.wait()
  tests/helpers/graphical_units.py
Labels: Easy review, testing

#654 Show module-level functions in documentation
  docs/source/_static/custom.css
  docs/source/_templates/autosummary/module.rst
  docs/source/conf.py
Labels: documentation
