Repository ManimCommunity/manim, pull requests merged in 2020-05, with the labels that each got.

#25 New README
  README.md
  readme-assets/command.png
  readme-assets/windows_cairo.png
  readme-assets/windows_miktex.png
  readme-assets/windows_sox.png
Labels: documentation, enhancement

#27 Change .gitignore
  .gitignore
Labels: enhancement

#28 Minimal tests
  manimlib/imports.py
  samples/sample_scenes.py
  tests/tests_sample_scenes.py
Labels: enhancement

#29 fix typo in README and add SSH option
  README.md
Labels: bug, documentation, enhancement

#35 Added DocStrings for Camera type objects, and updated DocStrings for Scene type objects.
  manimlib/camera/camera.py
  manimlib/camera/mapping_camera.py
  manimlib/camera/moving_camera.py
  manimlib/camera/multi_camera.py
  manimlib/camera/three_d_camera.py
  manimlib/scene/graph_scene.py
  manimlib/scene/moving_camera_scene.py
  manimlib/scene/scene.py
  manimlib/scene/scene_file_writer.py
  manimlib/scene/three_d_scene.py
  manimlib/scene/vector_space_scene.py
  manimlib/scene/zoomed_scene.py
Labels: documentation

#45 Add setup.py
  manim.py
  setup.py
Labels: enhancement

#36 Added DocStrings for Camera type objects, and updated DocStrings for Scene type objects.
  manimlib/camera/camera.py
  manimlib/camera/mapping_camera.py
  manimlib/camera/moving_camera.py
  manimlib/camera/multi_camera.py
  manimlib/camera/three_d_camera.py
  manimlib/scene/graph_scene.py
  manimlib/scene/moving_camera_scene.py
  manimlib/scene/scene.py
  manimlib/scene/scene_file_writer.py
  manimlib/scene/three_d_scene.py
  manimlib/scene/vector_space_scene.py
  manimlib/scene/zoomed_scene.py
Labels: documentation

#63 Added dry run
  README.md
  manim/config.py
  tests/tests_sample_scenes.py
Labels: enhancement

#58 constants.py overhaul
  manim/__init__.py
  manim/config.py
  manim/constants.py
  manim/dirs.py
  manim/media_dir.txt
  manim/mobject/mobject.py
  manim/mobject/svg/text_mobject.py
  manim/scene/scene_file_writer.py
  manim/utils/tex_file_writing.py
Labels: bug, cleaning, enhancement, new feature

#59 Add logger and replace print calls with appropriate logging functions
  manim/__init__.py
  manim/camera/camera.py
  manim/config.py
  manim/constants.py
  manim/extract_scene.py
  manim/logger.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/vector_field.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/scene_from_video.py
  manim/utils/tex_file_writing.py
  requirements.txt
  setup.py
Labels: enhancement

#67 Remove blank spaces on L7
  manim/__init__.py
Labels: cleaning

#54 Readme update
  README.md
Labels: documentation

#70 Update setup.py
  setup.py
Labels: bug, cleaning

#72 Enable python -m manim invocation
  manim/__main__.py
Labels: enhancement

#78 Fix __init__.py, __main__.py, and entrypoints
  example_scenes/basic.py
  manim/__init__.py
  manim/__main__.py
  manim/config.py
  manim/extract_scene.py
  manim/imports.py
  requirements.txt
  setup.py
Labels: cleaning, enhancement, refactor/rework

#49 Small improvements to Matrix mobject
  manim/mobject/matrix.py
Labels: enhancement, new feature

#89 Fix missing spaces and capitalize some words in usage message
  manim/config.py
Labels: documentation

#84 added AddTextLetterByLetter
  manim/animation/creation.py
Labels: new feature

#48 completely rewrote the TeX template model
  example_scenes/customtex.py
  manim/__init__.py
  manim/__main__.py
  manim/config.py
  manim/constants.py
  manim/mobject/svg/tex_mobject.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
Labels: new feature, refactor/rework

#105 ArcBetweenPoints fix/enhancement
  manim/mobject/geometry.py
  manim/mobject/mobject.py
Labels: bug, enhancement

#115 prefer NotImplementedError to a base Exception
  manim/mobject/mobject.py
Labels: enhancement
