Repository ManimCommunity/manim, pull requests merged in 2020-07, with the labels that each got.

#98 Configparser setup: figuring out config.py, constants.py, dirs.py, CLI arguments, and more [WIP]
  .travis.yml
  .travis/linux.sh
  .travis/osx.sh
  .travis/travis-requirements.txt
  example_scenes/basic.py
  example_scenes/customtex.py
  manim/__init__.py
  manim/__main__.py
  manim/animation/transform.py
  manim/camera/camera.py
  manim/camera/moving_camera.py
  manim/camera/three_d_camera.py
  manim/config.py
  manim/constants.py
  manim/container/container.py
  manim/default.cfg
  manim/dirs.py
  manim/extract_scene.py
  manim/mobject/coordinate_systems.py
  manim/mobject/frame.py
  manim/mobject/functions.py
  manim/mobject/mobject.py
  manim/mobject/number_line.py
  manim/mobject/svg/drawings.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/scene/graph_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/three_d_scene.py
  manim/scene/vector_space_scene.py
  manim/scene/zoomed_scene.py
  manim/utils/color.py
  manim/utils/tex_file_writing.py
  setup.py
  tests/conftest.py
  tests/manim.cfg
  tests/test_cli/manim.cfg
  tests/test_cli/test_cli.py
  tests/test_creation.py
  tests/test_geometry.py
  tests/test_graph.py
  tests/test_indication.py
  tests/test_movements.py
  tests/test_threed.py
  tests/test_transform.py
  tests/test_updaters.py
  tests/test_writing.py
  tests/testing_utils.py
  tests/tests_cache/writing/TextTest/Text/space.svg
  tests/tests_data/basic_scenes.py
  tests/tests_data/manim.cfg
Labels: cleaning, enhancement, help wanted, refactor/rework

#156 More explicit installation guide for GNU/Linux OS
  README.md
Labels: documentation

#164 Fix #101
  manim/mobject/coordinate_systems.py
Labels: bug

#155 Added instruction to test changes locally before taking a PR. [skip ci]
  CONTRIBUTING.md
Labels: documentation, enhancement, github, testing

#189 Properly parse the file path to get the module containing the Scenes
  manim/__main__.py
Labels: bug

#190 Added a VDict class with usage example
  example_scenes/basic.py
  manim/mobject/types/vectorized_mobject.py
Labels: new feature

#207 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#208 Allow for End-to-end tests on Windows
  .github/workflows/ci.yml
  tests/test_cli/dash_test_script.txt
  tests/test_cli/test_cli.py
Labels: enhancement, github, testing

#151 Rich Command line output colour customization
  example_scenes/manim.cfg
  manim/__main__.py
  manim/config.py
  manim/default.cfg
  manim/logger.py
  manim/utils/cfgwriter.py
  manim/utils/config_utils.py
  setup.py
Labels: enhancement, new feature

#217 Remove a reference to Travis in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cleaning

#220 Use file_writer_config instead of config to get text_dir for Text()
  manim/mobject/svg/text_mobject.py
  tests/testing_utils.py
Labels: bug
