Repository ManimCommunity/manim, pull requests merged in 2021-09, with the labels that each got.

#1980 Added a 'dissipating' feature for `TracedPath`
  manim/mobject/changing.py
Labels: new feature

#1929 Implementing a ``Zoom`` parameter to :class:`~.ThreeDScene`
  manim/camera/three_d_camera.py
  manim/scene/three_d_scene.py
  tests/control_data/graphical_units_data/threed/CameraMove.npz
  tests/control_data/graphical_units_data/threed/CameraMoveAxes.npz
  tests/test_graphical_units/test_threed.py
Labels: new feature

#1989 Prepare new release v0.10.0
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.10.0-changelog.rst
  pyproject.toml
  scripts/TEMPLATE.cff
Labels: release

#1991 Deprecated :meth:`.VMobject.get_points`
  docs/source/tutorials/building_blocks.rst
  manim/animation/transform_matching_parts.py
  manim/mobject/changing.py
  manim/mobject/geometry.py
  manim/mobject/opengl_geometry.py
  manim/mobject/opengl_mobject.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/value_tracker.py
  manim/renderer/opengl_renderer.py
  manim/renderer/vectorized_mobject_rendering.py
Labels: deprecation, maintenance

#1469 Added proportion_from_point method to VMobject, which uses some new bezier curve utilities
  manim/mobject/mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/utils/bezier.py
Labels: enhancement, new feature

#2004 Cancel previous workflows in the same branch in Github Actions
  .github/workflows/ci.yml
Labels: infrastructure

#2020 Corrected user-wide Config Paths for *NIX
  docs/source/tutorials/configuration.rst
Labels: documentation

#2017 Avoid using deprecated get_points and fix :class:~.OpenGLPMPoint color
  manim/mobject/types/opengl_point_cloud_mobject.py
Labels: bugfix, easy review

#1994 Fix :meth:`~.input_to_graph_point` when passing a `line_graph`
  manim/mobject/coordinate_systems.py
  manim/utils/simple_functions.py
  tests/test_coordinate_system.py
Labels: bugfix

#2027 Added missing space in info message for :meth:`~.SceneFileWriter.clean_cache`
  manim/scene/scene_file_writer.py
Labels: easy review, maintenance

#2011 Fixed -a flag for opengl
  manim/cli/render/commands.py
Labels: bugfix, opengl

#2035 Fix broken link in readme
  README.md
Labels: documentation

#2043 Fix bug where `~.NumberLine.add_labels()` cannot accept non-mobject labels.
  manim/mobject/number_line.py
Labels: bugfix, easy review

#2024 Deprecated redundant methods of Mobject
  docs/source/examples.rst
  manim/animation/indication.py
  manim/mobject/coordinate_systems.py
  manim/mobject/mobject.py
  manim/mobject/svg/opengl_text_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/scene/vector_space_scene.py
Labels: deprecation

#2028 Fixed opengl overriding svg fill color
  manim/mobject/opengl_mobject.py
Labels: bugfix, opengl

#2041 Added config to enable opengl wireframe for debugging
  docs/source/tutorials/configuration.rst
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/cli/render/global_options.py
  manim/renderer/opengl_renderer.py
Labels: enhancement, easy review, opengl

#2026 Fixed opengl shift animation for :class:~.Text
  manim/animation/animation.py
  manim/animation/transform.py
Labels: bugfix, opengl

#2039 Added opengl compatibility for :meth:`~Cylinder.add_bases`.
  manim/mobject/three_dimensions.py
Labels: bugfix, opengl

#1971 Add OpenGL support for :class:`~.StreamLines`
  manim/mobject/vector_field.py
Labels: enhancement, opengl

#2037 Fixed OpenGL :meth:`~.OpenGLMobject.apply_complex_function`
  manim/mobject/types/opengl_vectorized_mobject.py
Labels: bugfix, opengl

#2060 Fixed opengl compatibility issue for meth:`~Line.set_opacity`
  manim/mobject/geometry.py
Labels: bugfix, opengl

#2072 Added OpenGL compatibility for :class:`~.Cube`.
  manim/mobject/three_dimensions.py
Labels: bugfix, opengl

#2064 Removed duplicate insert shader directory
  manim/renderer/shader_wrapper.py
  manim/renderer/shaders/inserts/NOTE.md
  manim/renderer/shaders/inserts/add_light.glsl
  manim/renderer/shaders/inserts/camera_uniform_declarations.glsl
  manim/renderer/shaders/inserts/finalize_color.glsl
  manim/renderer/shaders/inserts/get_gl_Position.glsl
  manim/renderer/shaders/inserts/get_rotated_surface_unit_normal_vector.glsl
  manim/renderer/shaders/inserts/get_unit_normal.glsl
  manim/renderer/shaders/inserts/position_point_into_frame.glsl
  manim/renderer/shaders/inserts/quadratic_bezier_distance.glsl
  manim/renderer/shaders/inserts/quadratic_bezier_geometry_functions.glsl
Labels: easy review, maintenance, opengl

#2013 Removed unnecesary check in :class:`~.TransformMatchingAbstractBase` - Fixes #1609
  manim/animation/transform_matching_parts.py
Labels: enhancement

#2055 Fixed :meth:`~Graph.add_edges` and :meth:`~Graph.add_vertices` parameter types
  manim/mobject/graph.py
Labels: documentation

#2080 Reused tests for :class:`~Mobject`. with :class:`~OpenGLMobject`
  manim/mobject/opengl_mobject.py
  tests/conftest.py
  tests/opengl/__init__.py
  tests/opengl/test_opengl_mobject.py
  tests/standard_config.cfg
  tests/test_scene_rendering/conftest.py
Labels: testing, opengl

#1998 Added support for Boolean Operations on VMobjects
  docs/source/reference_index/mobjects.rst
  manim/__init__.py
  manim/mobject/boolean_ops.py
  poetry.lock
  pyproject.toml
  tests/control_data/graphical_units_data/boolean_ops/difference.npz
  tests/control_data/graphical_units_data/boolean_ops/exclusion.npz
  tests/control_data/graphical_units_data/boolean_ops/intersection.npz
  tests/control_data/graphical_units_data/boolean_ops/intersection_3_mobjects.npz
  tests/control_data/graphical_units_data/boolean_ops/union.npz
  tests/test_boolops/test_boolops.py
Labels: new feature

#1982 Added opengl support for --format png output
  docs/source/tutorials/configuration.rst
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/cli/render/global_options.py
  manim/renderer/opengl_renderer.py
  manim/renderer/shader.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  pyproject.toml
  tests/test_config.py
  tests/test_scene_rendering/conftest.py
  tests/test_scene_rendering/test_cli_flags.py
  tests/test_scene_rendering/test_opengl_renderer.py
Labels: enhancement, opengl

#2084 Added :meth:`~Table.get_highlighted_cell` and fixed :meth:`~Table.add_highlighted_cell`
  manim/mobject/table.py
Labels: bugfix, enhancement

#2061 Remove deprecated u-min/max and v-min/max in :class:'~.Surface'
  manim/mobject/three_dimensions.py
  tests/test_graphical_units/test_threed.py
Labels: deprecation

#2101 Added note that translation process is not ready
  docs/source/contributing/internationalization.rst
Labels: documentation

#2008 Reuse CLI flag tests for opengl
  tests/test_scene_rendering/opengl/__init__.py
  tests/test_scene_rendering/opengl/test_cli_flags_opengl.py
  tests/test_scene_rendering/opengl/test_opengl_renderer.py
Labels: testing, opengl

#2102 Deprecated `SampleSpaceScene` and `ReconfigurableScene`
  manim/scene/reconfigurable_scene.py
  manim/scene/sample_space_scene.py
Labels: deprecation

#2088 Reused a batch of cairo tests with the opengl renderer
  manim/scene/scene.py
  tests/opengl/test_animate_opengl.py
  tests/opengl/test_axes_shift_opengl.py
  tests/opengl/test_copy_opengl.py
  tests/opengl/test_graph_opengl.py
  tests/opengl/test_ipython_magic_opengl.py
  tests/opengl/test_markup_opengl.py
  tests/opengl/test_scene_opengl.py
  tests/opengl/test_texmobject_opengl.py
  tests/opengl/test_text_mobject_opengl.py
  tests/opengl/test_ticks_opengl.py
  tests/opengl/test_unit_geometry_opengl.py
  tests/opengl/test_value_tracker_opengl.py
Labels: testing, opengl

#2016 Add Opengl support for Boolean Operation
  manim/mobject/boolean_ops.py
Labels: opengl

#2075 Implemented :meth:`.Mobject.set_default`, a mechanism for changing default values of keyword arguments
  manim/mobject/mobject.py
  manim/mobject/opengl_mobject.py
Labels: new feature

#2113 Added OpenGL compatibility to :meth:`.ThreeDScene.begin_ambient_camera_rotation` and :meth:`.ThreeDScene.move_camera`
  manim/scene/three_d_scene.py
Labels: enhancement, opengl

#2071 Fixed :class:`~AnimationGroup` opengl compatibility
  manim/animation/animation.py
Labels: bugfix, opengl

#2070 Fixed :meth:`~OpenGLRenderer.get_frame` when window is created
  manim/renderer/opengl_renderer.py
  tests/test_scene_rendering/conftest.py
  tests/test_scene_rendering/test_opengl_renderer.py
Labels: bugfix, opengl
