Repository ManimCommunity/manim, pull requests merged in 2021-03, with the labels that each got.

#1063 Fix docs related to .animate
  manim/mobject/mobject.py
Labels: easy review

#1058 Fix #1039 (<span foreground=> tags)
  manim/mobject/svg/style_utils.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/text_mobject.py
  tests/control_data/graphical_units_data/img_and_svg/UseTagInheritanceTest.npz
  tests/test_graphical_units/img_svg_resources/aabbb.svg
  tests/test_graphical_units/test_img_and_svg.py
Labels: enhancement

#1053 fix #1045 changes in line 118
  docs/source/conf.py
Labels: easy review

#1070 Raise FileNotFoundError when unable to locate the .cfg file specified by --config_file
  manim/_config/utils.py
Labels: easy review

#1083 Correct shape of torus
  manim/mobject/three_dimensions.py
Labels: easy review

#1078 Cleanup __main__.py - remove stray print statements
  manim/__main__.py
  manim/_config/main_utils.py
  tests/test_commands.py
Labels: easy review

#718 Rotating the numbers in y axis
  manim/mobject/coordinate_systems.py
  manim/mobject/number_line.py
  manim/scene/graph_scene.py
Labels: enhancement

#1073 Remove "one line summary" from pr template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/source/changelog.rst
Labels: cleaning, easy review

#1110 Deprecated SmallDot + OpenGLSmallDot
  manim/mobject/geometry.py
  manim/mobject/opengl_geometry.py
Labels: cleaning

#1085 Added Angle/RightAngle classes for two intersecting lines
  manim/mobject/geometry.py
  tests/control_data/graphical_units_data/geometry/AngleTest.npz
  tests/control_data/graphical_units_data/geometry/RightAngleTest.npz
  tests/test_graphical_units/test_geometry.py
Labels: new feature

#1103 Documentation + examples for Square, Dot, Circle and Rectangle
  manim/mobject/geometry.py
Labels: docs

#1074 Added jupyter media_width option to the config
  docs/source/tutorials/configuration.rst
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/utils/ipython_magic.py
Labels: easy review

#1036 Docs: Added :class:`~.SurroundingRectangle` to example gallery
  docs/source/examples.rst
Labels: docs

#1077 +doc Mobject.get_critical_point()
  docs/source/contributing.rst
  docs/source/installation/for_dev.rst
  docs/source/installation/mac.rst
  manim/mobject/mobject.py
Labels: docs

#1157 Apply refereshed triangulation on call to :meth:`~.OpenGLVMobject.apply_points_function`
  manim/mobject/types/opengl_vectorized_mobject.py
Labels: enhancement

#1144 Improved quality of GIFs
  manim/scene/scene_file_writer.py
Labels: enhancement

#1140 Flake8 Compat & Code Cleanup
  .flake8
  .github/workflows/lint.yml
  manim/__main__.py
  manim/_config/utils.py
  manim/animation/creation.py
  manim/animation/indication.py
  manim/animation/transform.py
  manim/camera/camera.py
  manim/camera/moving_camera.py
  manim/camera/three_d_camera.py
  manim/grpc/impl/frame_server_impl.py
  manim/mobject/graph.py
  manim/mobject/mobject.py
  manim/mobject/numbers.py
  manim/mobject/opengl_geometry.py
  manim/mobject/opengl_mobject.py
  manim/mobject/probability.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/plugins/import_plugins.py
  manim/plugins/plugins_flags.py
  manim/renderer/shader_wrapper.py
  manim/scene/graph_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/vector_space_scene.py
  manim/utils/bezier.py
  manim/utils/color.py
  manim/utils/config_ops.py
  manim/utils/ipython_magic.py
  manim/utils/iterables.py
  manim/utils/space_ops.py
  poetry.lock
  pyproject.toml
Labels: style

#1164 Fixed single PEP8 style in `cairo_renderer.py`
  manim/renderer/cairo_renderer.py
Labels: easy review, style

#1071 Enable pytest-cov based code coverage
  .github/workflows/ci.yml
  poetry.lock
  pyproject.toml
Labels: infrastructure

#1173 MAINT: numpy.ndarray.tostring is deprecated
  manim/scene/scene_file_writer.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#1159 Added support for multiple transforms in the same SVG element
  manim/mobject/svg/svg_mobject.py
  tests/control_data/graphical_units_data/img_and_svg/MatrixTransformTest.npz
  tests/control_data/graphical_units_data/img_and_svg/MultipleTransformTest.npz
  tests/control_data/graphical_units_data/img_and_svg/RotateTransformTest.npz
  tests/control_data/graphical_units_data/img_and_svg/ScaleTransformTest.npz
  tests/control_data/graphical_units_data/img_and_svg/SkewXTransformTest.npz
  tests/control_data/graphical_units_data/img_and_svg/SkewYTransformTest.npz
  tests/control_data/graphical_units_data/img_and_svg/TranslateTransformTest.npz
  tests/test_graphical_units/img_svg_resources/matrix.svg
  tests/test_graphical_units/img_svg_resources/multiple_transforms.svg
  tests/test_graphical_units/img_svg_resources/rotate.svg
  tests/test_graphical_units/img_svg_resources/scale.svg
  tests/test_graphical_units/img_svg_resources/skewX.svg
  tests/test_graphical_units/img_svg_resources/skewY.svg
  tests/test_graphical_units/img_svg_resources/translate.svg
  tests/test_graphical_units/test_img_and_svg.py
Labels: bug

#1166 CI: Use poetry's cache dir rather than pip
  .github/workflows/ci.yml
Labels: infrastructure

#1097 Added 3D Mobject :class:`~.Dot3D`
  manim/constants.py
  manim/mobject/geometry.py
  manim/mobject/three_dimensions.py
  tests/control_data/graphical_units_data/threed/Dot3DTest.npz
  tests/test_graphical_units/test_threed.py
Labels: new feature

#1128 Added examples for :class:`~.DashedLine`, :class:`~.TangentLine`, :class:`~.Elbow`, :class:`~.Arrow`, :class:`~.Vector`, :class:`~.DoubleArrow`
  manim/mobject/geometry.py
Labels: documentation

#1165 Added documentation for installing Manim on Colab
  docs/source/installation.rst
  docs/source/installation/colab.rst
Labels: documentation

#1170 Fixed minor SVG parsing bugs
  manim/mobject/svg/style_utils.py
  tests/test_graphical_units/img_svg_resources/multi_part_path.svg
Labels: bug

#1187 Add CodeCov to Github Workflow
  .codecov.yml
Labels: infrastructure

#1188 Added sounds example to docs
  docs/source/_static/click.wav
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/sounds.py
Labels: documentation

#1160 Enable CI testing for OpenGL
  .github/workflows/ci.yml
  manim/renderer/opengl_renderer.py
  tests/__init__.py
  tests/control_data/graphical_units_data/opengl/CircleTest.npz
  tests/test_graphical_units/test_opengl.py
  tests/utils/GraphicalUnitTester.py
Labels: infrastructure, testing

#1193 Fixed using :class:`Animation`s without a child :class:`~.Mobject` in :class:`~.AnimationGroup`
  manim/animation/animation.py
  manim/animation/composition.py
  tests/test_composition.py
Labels: bug

#1138 Add a Script to generate changelog
  .github/PULL_REQUEST_TEMPLATE.md
  docs/source/changelog.rst
  docs/source/changelog/0.1.0-changelog.rst
  docs/source/changelog/0.1.1-changelog.rst
  docs/source/changelog/0.2.0-changelog.rst
  docs/source/changelog/0.3.0-changelog.rst
  docs/source/changelog/0.4.0-changelog.rst
  poetry.lock
  pyproject.toml
  scripts/dev_changelog.py
Labels: easy review, release

#1130 Added pre-commit to run black and flake8, updated contributing documentation accordingly
  .flake8
  .pre-commit-config.yaml
  docs/source/_static/pull-requests.PNG
  docs/source/contributing.rst
  docs/source/installation.rst
  docs/source/installation/for_dev.rst
  poetry.lock
  pyproject.toml
Labels: documentation, easy review, infrastructure

#1037 Added new fade and transform animations (:class:`~.TransformMatchingShapes`, :class:`~.TransformMatchingTex`, :class:`~.FadeTransform`) from 3b1b/manim
  docs/source/reference.rst
  manim/__init__.py
  manim/animation/fading.py
  manim/animation/transform.py
  manim/animation/transform_matching_parts.py
  manim/mobject/svg/tex_mobject.py
Labels: new feature

#1114 Added examples for :class:`~.Ellipse`, :class:`~.Polygon`, :class:`~.RegularPolygon`, :class:`~.Triangle` and :class:`~.RoundedRectangle`
  manim/mobject/geometry.py
Labels: documentation

#1137 Added testing/documentation from GitHub Wiki to Sphinx Docs
  .pre-commit-config.yaml
  docs/source/contributing.rst
  docs/source/contributing/development.rst
  docs/source/contributing/documentation.rst
  docs/source/contributing/reference/manim_directive.ManimDirective.rst
  docs/source/contributing/reference/manim_directive.rst
  docs/source/contributing/reference/manim_directive.skip_manim_node.rst
  docs/source/contributing/testing.rst
  docs/source/installation/for_dev.rst
  manim/mobject/geometry.py
Labels: documentation, easy review

#1204 added rotation example to example gallery
  docs/source/examples.rst
Labels: documentation

#1192 Fixed issue when an animation is cached, manim can't merge the partial movie files.
  manim/renderer/cairo_renderer.py
  tests/assert_utils.py
  tests/test_scene_rendering/test_cairo_renderer.py
Labels: bug

#1209 Added :ref_methods: to the manim directive
  docs/source/examples.rst
  docs/source/manim_directive.py
Labels: documentation, sphinx
