Repository ManimCommunity/manim, pull requests merged in 2021-02, with the labels that each got.

#988 Fix Windows CI pipeline by adding missing LaTeX package
  .github/manimdependency.json
Labels: easy review

#986 v0.3.0: prepare new release
  docs/source/changelog.rst
  pyproject.toml
Labels: release

#1005 Fix - as filename feature
  manim/_config/utils.py
  tests/test_scene_rendering/test_cli_flags.py
  tests/utils/commands.py
Labels: bug

#1010 Disable STDIN interaction for ffmpeg concat.
  manim/scene/scene_file_writer.py
Labels: bug, enhancement

#1003 GrowArrow animation fixed
  manim/animation/growing.py
  manim/mobject/geometry.py
Labels: easy review

#995 Add generic set method and compatibility layer between properties and get_*/set_* methods
  manim/mobject/mobject.py
  manim/utils/module_ops.py
  tests/test_get_set.py
Labels: easy review

#1021 Docs: added Bezier example
  manim/mobject/geometry.py
Labels: docs, easy review

#1044 register_font is available for macOS
  manim/mobject/svg/text_mobject.py
Labels: easy review

#1046 Update importlib-metadata
  poetry.lock
  pyproject.toml
Labels: easy review

#1059 More descriptive error when accessing an unhandled mobject attribute
  manim/mobject/mobject.py
  tests/test_get_set.py
Labels: easy review

#1050 fix - make sure stroke color & width gets applied in Cross object
  manim/mobject/shape_matchers.py
Labels: easy review

#1060 docs: update installation docs for linux - pango
  docker/Dockerfile
  docs/source/installation/linux.rst
Labels: easy review
