Repository ManimCommunity/manim, pull requests merged in 2021-07, with the labels that each got.

#1740 Fix pillow to <8.3.0
  poetry.lock
  pyproject.toml
Labels: bugfix

#1735 Metaclass compatibility for `coordinate_system.py`, `Code` and `ParametricSurface`
  manim/mobject/coordinate_systems.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/three_dimensions.py
Labels: enhancement

#1733 Let OpenGLMobject.copy return a deep copy by default
  manim/mobject/opengl_mobject.py
Labels: bugfix, enhancement

#1728 Improve positioning and size of the OpenGL window
  docs/source/tutorials/configuration.rst
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/cli/render/global_options.py
  manim/renderer/opengl_renderer_window.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#1738 Preparation for v0.8.0: added changelog and bumped version number
  docs/source/changelog/0.8.0-changelog.rst
  pyproject.toml
Labels: release

#1736 Fix LinearTransformationScene crashing on second animation
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
Labels: bugfix

#1774 Add the ``reverse`` parameter to :class:`~.Write`
  manim/animation/creation.py
Labels: enhancement, refactor

#1706 Rework example for :class:`~.Variable`
  manim/mobject/numbers.py
Labels: documentation, hackathon

#1743 Edited the developer installation instructions to add in missing context about repository cloning
  docs/source/installation/for_dev.rst
Labels: documentation, easy review

#1686 Added `.set_fill_by_value()` to :class:`~.ParametricSurface`
  manim/mobject/three_dimensions.py
  tests/control_data/graphical_units_data/threed/SurfaceColorscaleTest.npz
  tests/test_graphical_units/test_threed.py
Labels: new feature

#1765 Added a static method to :class:`~.Circle` to allow it to be defined by three points
  manim/mobject/geometry.py
  manim/utils/space_ops.py
  tests/control_data/graphical_units_data/geometry/CirclePointsTest.npz
  tests/test_graphical_units/test_geometry.py
Labels: enhancement

#1757 Added warning when there is a large number of items to hash.
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/utils/hashing.py
Labels: enhancement

#1775 Let :class:`~.Create` work on :class:`~.OpenGLSurface`
  manim/animation/creation.py
  manim/mobject/mobject.py
Labels: enhancement

#1719 Added :class:`~.Broadcast` animation.
  docs/source/reference.rst
  manim/__init__.py
  manim/animation/animation.py
  manim/animation/specialized.py
Labels: enhancement, new feature

#1778 Improve sidebar structure of reference manual
  docs/source/_templates/autosummary/class.rst
  docs/source/_templates/autosummary/module.rst
  docs/source/contributing/development.rst
  docs/source/contributing/reference/manim_directive.ManimDirective.rst
  docs/source/contributing/reference/manim_directive.rst
  docs/source/contributing/reference/manim_directive.skip_manim_node.rst
  docs/source/reference.rst
  docs/source/reference_index/animations.rst
  docs/source/reference_index/cameras.rst
  docs/source/reference_index/configuration.rst
  docs/source/reference_index/mobjects.rst
  docs/source/reference_index/scenes.rst
  docs/source/reference_index/utilities_misc.rst
Labels: documentation

#1813 remove unused variables from tutorial
  docs/source/tutorials/building_blocks.rst
Labels: documentation

#1819 Update misleading -h flag in document
  docs/source/changelog/0.6.0-changelog.rst
  docs/source/tutorials/configuration.rst
Labels: documentation

#1791 fix: set_z_index now sets all submobjects' z_index value
  manim/mobject/mobject.py
Labels: bugfix

#1802 Refactored graphical unit testing system, and implemented multi frames tests.
  manim/renderer/cairo_renderer.py
  manim/renderer/opengl_renderer.py
  tests/conftest.py
  tests/test_graphical_units/testing/_frames_testers.py
  tests/test_graphical_units/testing/_show_diff.py
  tests/test_graphical_units/testing/_test_class_makers.py
  tests/test_graphical_units/testing/config_graphical_tests_monoframe.cfg
  tests/test_graphical_units/testing/config_graphical_tests_multiframes.cfg
  tests/test_graphical_units/testing/frames_comparison.py
Labels: enhancement, testing

#1829 Switch the order of Scoop and Choco in the docs for the Windows Installation
  docs/source/installation/win.rst
Labels: documentation

#1808 OpenGL renderer updates
  manim/_config/default.cfg
  manim/mobject/opengl_mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/renderer/opengl_renderer.py
  manim/renderer/opengl_renderer_window.py
  manim/renderer/shader.py
  manim/renderer/shaders/vectorized_mobject_fill/vert.glsl
  manim/renderer/vectorized_mobject_rendering.py
  manim/scene/scene.py
  manim/utils/opengl.py
  manim/utils/space_ops.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#1839 Allow passing arguments to `.animate` with the OpenGL renderer
  manim/mobject/opengl_mobject.py
Labels: bugfix, easy review, opengl

#1842 Update documentation for `developer installation` in `for_dev.rst`
  docs/source/installation/for_dev.rst
Labels: documentation

#1826 Fix bar chart scaling
  manim/mobject/probability.py
Labels: bugfix

#1823 DashedVMobject reworked
  manim/mobject/geometry.py
  manim/mobject/opengl_geometry.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  tests/control_data/graphical_units_data/geometry/DashedVMobjectTest.npz
  tests/test_graphical_units/test_geometry.py
Labels: breaking changes, enhancement

#1821 Fixed issues concerning frame_center in ThreeDScene
  manim/camera/three_d_camera.py
  manim/scene/three_d_scene.py
  tests/control_data/graphical_units_data/threed/CameraMoveTest.npz
  tests/test_graphical_units/test_threed.py
Labels: bugfix

#1844 Fix oversized code window with opengl renderer
  manim/mobject/svg/text_mobject.py
Labels: bugfix
