Repository ManimCommunity/manim, pull requests merged in 2021-06, with the labels that each got.

#1610 Made the extension of pull-requests picture lowercase.
  docs/source/_static/pull-requests.png
  docs/source/contributing/development.rst
Labels: maintenance

#1620 Fixed tip about command-line help
  docs/source/tutorials/configuration.rst
Labels: documentation, maintenance

#1621 Revert default template and add new templates
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/hackathon.md
Labels: easy review, infrastructure

#1623 CI: branch rename: master -> main
  .github/workflows/ci.yml
Labels: bugfix, enhancement

#1631 Added example for :class:`~.BulletedList`
  manim/mobject/svg/tex_mobject.py
Labels: documentation, hackathon

#1630 Added example for :class:`~.Arc`
  manim/mobject/geometry.py
Labels: documentation, hackathon

#1634 Fixed OpenGL examples for MacOS
  example_scenes/opengl.py
Labels: bugfix

#1633 Added example for :class:`~Integer`
  manim/mobject/numbers.py
Labels: documentation, hackathon

#1635 Add missing numpy import for :class:`.~Probability`
  manim/mobject/probability.py
Labels: maintenance

#1644 Add an example to shape_matchers.py
  manim/mobject/shape_matchers.py
Labels: documentation, hackathon

#1617 Tweak tutorial example
  docs/source/tutorials/quickstart.rst
Labels: documentation

#1643 Fixed RightArcAngleExample in docs
  manim/mobject/geometry.py
Labels: bugfix

#1640 Add example for :class:`Point`
  manim/mobject/types/point_cloud_mobject.py
Labels: documentation, hackathon

#1651 Small code cleanup for :class:`~.Polygram`
  manim/mobject/geometry.py
Labels: easy review, maintenance

#1608 Color file paths in terminal; remove curly braces surrounding the file path in "Partial movie file written in..." messages
  manim/scene/scene_file_writer.py
  manim/utils/file_ops.py
Labels: easy review, enhancement

#1639 Add Example to :class:`~.SampleSpace`
  manim/mobject/probability.py
Labels: documentation, hackathon

#1619 Fix latex error summary
  manim/utils/tex_file_writing.py
Labels: enhancement

#1658 Update python requirement in docs
  docs/source/installation.rst
Labels: documentation, easy review

#1646 Added example for :class:`~.UnderLine`
  manim/mobject/shape_matchers.py
Labels: documentation, hackathon

#1628 Added an example for :class:`~.NumberPlane`
  manim/mobject/coordinate_systems.py
Labels: documentation, hackathon

#1636 Fixed bugs and added examples to methods and classes in matrix.py
  manim/mobject/matrix.py
Labels: bugfix, documentation, hackathon

#1673 Fix: use weight instead of style for BOLD Text/MarkupText in docs
  manim/mobject/svg/text_mobject.py
Labels: bugfix, documentation, easy review

#1647 Added example for :class:`Sector`
  manim/mobject/geometry.py
Labels: documentation, hackathon

#1569 Added example to demonstrate differences between :class:`~.Transform` and :class:`~.ReplacementTransform`
  manim/animation/transform.py
Labels: documentation

#1627 Added example for :class:`~.Sphere`
  manim/mobject/three_dimensions.py
Labels: documentation

#1692 Remove redundant warning in CLI parsing
  manim/cli/render/commands.py
Labels: maintenance

#1660 Add support for webm and jupyter transparency
  manim/_config/utils.py
  manim/cli/render/render_options.py
  manim/scene/scene_file_writer.py
  manim/utils/file_ops.py
  manim/utils/ipython_magic.py
  tests/test_scene_rendering/test_cli_flags.py
Labels: enhancement, new feature

#1689 Added example to :class:`~.SurroundingRectangle`
  manim/mobject/shape_matchers.py
Labels: documentation, hackathon

#1678 Fixed rate functions and lag ratios
  manim/animation/animation.py
  manim/animation/movement.py
  manim/utils/rate_functions.py
Labels: bugfix

#1642 Add examples and docstrings for :class:`~.BarChart`
  manim/mobject/probability.py
Labels: documentation, hackathon, typehints

#1693 Made the default arrowhead size for :class:`~.Arrow3D` smaller
  manim/mobject/three_dimensions.py
  tests/control_data/graphical_units_data/threed/Arrow3DTest.npz
Labels: enhancement

#1695 Add option to justify text with :class:`MarkupText`
  manim/mobject/svg/text_mobject.py
Labels: new feature

#1657 Add example for :class:~.`ParametricSurface`
  manim/mobject/three_dimensions.py
Labels: documentation, hackathon

#1708 Fixed MyBinder Page Link in the Docs
  docs/source/examples.rst
Labels: documentation

#1710 Update copyright year in documentation to 2020-2021
  docs/source/conf.py
Labels: documentation

#1664 Fixed accidental displacement in :class:`~.Axes` caused by `include_numbers`/`numbers_to_include`
  manim/mobject/coordinate_systems.py
  tests/control_data/graphical_units_data/coordinate_systems/NumberPlaneTest.npz
  tests/control_data/graphical_units_data/plot/AxesTest.npz
Labels: bugfix, refactor

#1712 Added a second example for :class:`DoubleArrow`
  manim/mobject/geometry.py
Labels: documentation

#1626 Added example for :class:`Prism`
  manim/mobject/three_dimensions.py
Labels: documentation, hackathon

#1637 Add example to :class:`FunctionGraph`
  manim/mobject/functions.py
Labels: documentation, hackathon

#1696 Added an Example to :class:`~.DashedVMobject`
  manim/mobject/types/vectorized_mobject.py
Labels: documentation, hackathon

#1594 Improve the look of the docs.
  docs/source/_static/custom.css
  docs/source/conf.py
Labels: documentation, enhancement

#1697 Added an example to :class:`~.PGroup`
  manim/mobject/types/point_cloud_mobject.py
Labels: documentation, hackathon

#1652 Removed Container ABC
  docs/source/contributing/testing.rst
  docs/source/reference.rst
  manim/__init__.py
  manim/container.py
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  manim/mobject/number_line.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/three_dimensions.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/scene.py
  manim/utils/rate_functions.py
  tests/test_container.py
  tests/test_graphical_units/test_graphscene.py
  tests/test_mobject.py
  tests/test_number_line.py
  tests/test_scene.py
Labels: maintenance

#1720 Renamed incorrect references of ``master`` to ``main``
  README.md
  docker/readme.md
  docs/source/contributing/development.rst
  docs/source/contributing/examples.rst
  docs/source/index.rst
  manim/scene/scene.py
Labels: easy review, maintenance

#1681 Added example to :class:`~.NumberLine`
  manim/mobject/number_line.py
Labels: documentation, hackathon

#1687 Updated imports in `geometry.py` and added example to :class:`~.Arrow`
  manim/mobject/geometry.py
Labels: documentation, hackathon

#1685 Added example and parameter description to :class:`~.AnnularSector`
  manim/mobject/geometry.py
Labels: documentation, hackathon

#1510 Add a tutorial for using :class:`~.Text` and :class:`Tex`
  docs/source/tutorials.rst
  docs/source/tutorials/using_text.rst
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: documentation

#1690 Added Example for :class:`~.CoordinateSystem`
  manim/mobject/coordinate_systems.py
Labels: documentation, hackathon

#1698 Added Example to :class:`~.PMobject`
  manim/mobject/types/point_cloud_mobject.py
Labels: documentation, hackathon

#1729 Fix bug when using Text with the opengl renderer.
  manim/mobject/opengl_mobject.py
Labels: bugfix

#1732 docs: remove reference of `--plugins`
  docs/source/installation/plugins.rst
Labels: documentation
