Repository ManimCommunity/manim, pull requests merged in 2021-08, with the labels that each got.

#1677 New Mobject: Added :class:`~.Tabular`
  docs/source/reference_index/mobjects.rst
  manim/__init__.py
  manim/mobject/opengl_mobject.py
  manim/mobject/tabular.py
  tests/control_data/graphical_units_data/tabular/DecimalTabularTest.npz
  tests/control_data/graphical_units_data/tabular/IntegerTabularTest.npz
  tests/control_data/graphical_units_data/tabular/MathTabularTest.npz
  tests/control_data/graphical_units_data/tabular/MobjectTabularTest.npz
  tests/control_data/graphical_units_data/tabular/TabularTest.npz
  tests/test_graphical_units/test_tabular.py
Labels: help wanted, new feature

#1760 Add `window_size` flag.
  docs/source/tutorials/configuration.rst
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/renderer/opengl_renderer_window.py
Labels: enhancement

#1835 Updated docs for the test refactor (Tests PR 2/3)
  docs/source/contributing/testing.rst
Labels: documentation, testing

#1722 Fixing `remover=True` for :class:`~.AnimationGroup`
  manim/animation/composition.py
Labels: bugfix, needs discussion

#1739 Custom Animation Docs
  docs/source/tutorials/building_blocks.rst
  manim/animation/animation.py
Labels: documentation

#1848 Deprecated parameters for :class:`~.DashedLine` and :class:`~.DashedVMobject`
  manim/mobject/geometry.py
  manim/mobject/opengl_geometry.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: deprecation

#1833 Opengl compatibility for :class:`~.VDict`, :class:`~.Axes.get_line_graph` and :class:`~.FocusOn`.
  manim/animation/indication.py
  manim/mobject/coordinate_systems.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: easy review, enhancement, opengl

#1780 Allow non-numerical values to be added to :class:`~.NumberLine`/:class:`~.Axes`
  manim/mobject/coordinate_systems.py
  manim/mobject/number_line.py
  tests/control_data/graphical_units_data/plot/custom_coordinates.npz
  tests/test_graphical_units/test_axes.py
  tests/test_number_line.py
Labels: enhancement

#1807 Updated installation instructions
  README.md
  docs/source/installation.rst
Labels: documentation

#1852 Fixed docs for :meth:`.Coordinate_system.add_coordinates` and moved :class: `~.Code` example
  manim/mobject/coordinate_systems.py
  manim/mobject/svg/code_mobject.py
Labels: documentation

#1850 Bump version number to ``v0.9.0`` and generate changelog
  .codespellrc
  docs/source/changelog/0.7.0-changelog.rst
  docs/source/changelog/0.9.0-changelog.rst
  docs/source/installation/win.rst
  pyproject.toml
Labels: release

#1847 Allow Addition of Cross without the Mobject in argument
  manim/mobject/shape_matchers.py
Labels: enhancement

#1860 Removed :class:`~.GraphScene`, :class:`~.NumberLineOld` and parameters for :class:`~.ChangingDecimal`
  manim/__init__.py
  manim/animation/numbers.py
  manim/mobject/coordinate_systems.py
  manim/mobject/number_line.py
  manim/scene/graph_scene.py
  tests/control_data/graphical_units_data/graphscene/PlotFunctions.npz
  tests/control_data/graphical_units_data/plot/plot_functions.npz
  tests/test_axes_shift.py
  tests/test_graphical_units/test_axes.py
  tests/test_graphical_units/test_graphscene.py
Labels: deprecation

#1869 Fixed duplicated Parameters section in :meth:`.Mobject.arrange_in_grid`
  manim/mobject/mobject.py
Labels: documentation

#1864 Shortened and simplified PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: infrastructure

#1877 Remove duplicated imports in some documentation examples
  manim/mobject/graph.py
  manim/mobject/mobject.py
Labels: documentation

#1880 Update an example to use .animate instead of ApplyMethod
  docs/source/tutorials/building_blocks.rst
Labels: documentation

#1887 Fix ``custom_config`` not working in ``frames_comparison``
  tests/test_graphical_units/testing/frames_comparison.py
Labels: bugfix, testing

#1841 Reduced default resolution of :class:`~.Dot3D`
  manim/mobject/three_dimensions.py
  tests/control_data/graphical_units_data/polyhedra/Dodecahedron.npz
  tests/control_data/graphical_units_data/polyhedra/Icosahedron.npz
  tests/control_data/graphical_units_data/polyhedra/Octahedron.npz
  tests/control_data/graphical_units_data/polyhedra/Tetrahedron.npz
  tests/control_data/graphical_units_data/threed/Dot3D.npz
Labels: enhancement

#1868 Add OpenGL support to IPython magic
  manim/renderer/opengl_renderer.py
  manim/utils/ipython_magic.py
Labels: enhancement, opengl

#1896 Made RTD apt install FFMPEG instead of installing a Python binding
  .readthedocs.yml
  docs/rtd-requirements.txt
  docs/source/conf.py
Labels: infrastructure

#1906 Consistency and language improvements for README
  README.md
Labels: documentation

#1915 Fix wording problem in colab installation docs
  docs/source/installation/colab.rst
Labels: documentation

#1744 Fix :class:`~.NumberPlane` bug with positive/negative `x_range`/`y_range` values.
  manim/mobject/coordinate_systems.py
  tests/test_coordinate_system.py
Labels: bugfix

#1923 Fixed init help text formatting so that it's not truncated
  manim/cli/init/commands.py
Labels: enhancement

#1828 Add configuration option ``zero_pad`` for zero padding PNGs.
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/cli/render/output_options.py
  manim/scene/scene_file_writer.py
  tests/test_scene_rendering/test_cli_flags.py
Labels: new feature

#1893 Fix single-scene issue with gui
  manim/utils/module_ops.py
Labels: bug

#1931 Bugfix in `arrange_in_grid()`
  manim/mobject/mobject.py
  manim/mobject/opengl_mobject.py
Labels: bugfix, easy review

#1939 Fixed formatting of parameter description of :class:`~.NumberPlane`
  manim/mobject/coordinate_systems.py
Labels: documentation

#1922 Clean up when OpenGL renderer raises an error using IPython
  manim/utils/ipython_magic.py
Labels: enhancement

#1924 Made arrow tips rotate up/down
  manim/mobject/geometry.py
  tests/control_data/graphical_units_data/geometry/AngledArrowTip.npz
  tests/test_graphical_units/test_geometry.py
Labels: bugfix

#1938 Fixed :class:`~.Rotate` for angles that are multiples of :math:`2\pi`
  manim/animation/rotation.py
  manim/animation/transform.py
  manim/utils/paths.py
  tests/control_data/graphical_units_data/transform/FullRotation.npz
  tests/test_graphical_units/test_transform.py
Labels: bugfix

#1898 Replaced `self.data["attr"]` and `self.uniforms["attr"]` with `self.attr`.
  manim/mobject/number_line.py
  manim/mobject/opengl_mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/svg_path.py
  manim/mobject/types/opengl_surface.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/renderer/opengl_renderer.py
  manim/renderer/vectorized_mobject_rendering.py
  manim/utils/config_ops.py
  tests/test_set_attr.py
Labels: opengl

#1899 Allow to switch the renderer to opengl at runtime
  manim/_config/utils.py
  manim/mobject/opengl_compatibility.py
  manim/scene/scene.py
  tests/test_opengl_metaclass.py
Labels: opengl

#1951 Fixed the positioning of line graph that was under the graph
  manim/mobject/coordinate_systems.py
  tests/control_data/graphical_units_data/coordinate_system/line_graph.npz
  tests/test_graphical_units/test_coordinate_systems.py
Labels: bugfix

#1956 Upgrade to modern Python syntax
  docs/source/manim_directive.py
  example_scenes/basic.py
  manim/animation/animation.py
  manim/animation/creation.py
  manim/animation/indication.py
  manim/animation/transform.py
  manim/camera/camera.py
  manim/grpc/gen/frameserver_pb2.py
  manim/grpc/gen/frameserver_pb2_grpc.py
  manim/grpc/gen/renderserver_pb2.py
  manim/grpc/gen/renderserver_pb2_grpc.py
  manim/mobject/coordinate_systems.py
  manim/mobject/geometry.py
  manim/mobject/graph.py
  manim/mobject/matrix.py
  manim/mobject/mobject.py
  manim/mobject/numbers.py
  manim/mobject/opengl_geometry.py
  manim/mobject/opengl_mobject.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/opengl_tex_mobject.py
  manim/mobject/svg/opengl_text_mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/table.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/renderer/shader.py
  manim/renderer/shader_wrapper.py
  manim/renderer/vectorized_mobject_rendering.py
  manim/scene/sample_space_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/vector_space_scene.py
  manim/utils/bezier.py
  manim/utils/config_ops.py
  manim/utils/family.py
  manim/utils/family_ops.py
  manim/utils/file_ops.py
  manim/utils/hashing.py
  manim/utils/ipython_magic.py
  manim/utils/iterables.py
  manim/utils/simple_functions.py
  manim/utils/space_ops.py
  manim/utils/strings.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
  manim/utils/tex_templates.py
  tests/test_copy.py
  tests/test_graph.py
  tests/test_graphical_units/test_transform.py
  tests/test_vectorized_mobject.py
  tests/utils/logging_tester.py
  tests/utils/video_tester.py
Labels: maintenance

#1947 Set flake8 not to ignore undefined names in Python code
  .flake8
  manim/animation/transform_matching_parts.py
Labels: maintenance

#1949 Reworked installation instructions
  docs/source/_static/windows_cairo.png
  docs/source/_static/windows_miktex.png
  docs/source/_static/windows_sox.png
  docs/source/contributing/development.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/installation/colab.rst
  docs/source/installation/docker.rst
  docs/source/installation/for_dev.rst
  docs/source/installation/jupyter.rst
  docs/source/installation/linux.rst
  docs/source/installation/mac.rst
  docs/source/installation/macos.rst
  docs/source/installation/win.rst
  docs/source/installation/windows.rst
  docs/source/plugins.rst
  docs/source/reference_index/scenes.rst
  docs/source/tutorials/using_text.rst
  manim/utils/space_ops.py
Labels: documentation

#1952 Implement option to save last frame for OpenGL
  manim/renderer/opengl_renderer.py
Labels: enhancement

#1967 Fix :attr:`.Axes.coordinate_labels` referring to the entire axis, not just its labels.
  manim/mobject/coordinate_systems.py
Labels: bugfix

#1976 Fix labelling of languages in documentation example
  manim/mobject/svg/opengl_text_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: documentation

#1979 Correct Japanese phrases in documentation
  manim/mobject/svg/text_mobject.py
Labels: documentation

#1950 Fixed passing custom arrow shapes to :class:`~.CurvedArrow`
  manim/mobject/geometry.py
  tests/control_data/graphical_units_data/geometry/CurvedArrowCustomTip.npz
  tests/test_graphical_units/test_geometry.py
Labels: bugfix

#1973 Fixed indexing of :meth:`.Table.get_entries` to respect row length
  manim/mobject/table.py
Labels: bugfix

#1941 Added examples, tests and improved documentation for :mod:`~.coordinate_systems`
  manim/mobject/coordinate_systems.py
  tests/control_data/graphical_units_data/plot/get_area.npz
  tests/control_data/graphical_units_data/plot/get_axis_labels.npz
  tests/control_data/graphical_units_data/plot/get_derivative_graph.npz
  tests/control_data/graphical_units_data/plot/get_graph.npz
  tests/control_data/graphical_units_data/plot/get_graph_label.npz
  tests/control_data/graphical_units_data/plot/get_line_graph.npz
  tests/control_data/graphical_units_data/plot/get_lines_to_point.npz
  tests/control_data/graphical_units_data/plot/get_riemann_rectangles.npz
  tests/control_data/graphical_units_data/plot/get_x_axis_label.npz
  tests/control_data/graphical_units_data/plot/get_y_axis_label.npz
  tests/control_data/graphical_units_data/plot/get_z_axis_label.npz
  tests/control_data/graphical_units_data/plot/t_label.npz
  tests/test_coordinate_system.py
  tests/test_graphical_units/test_axes.py
Labels: documentation, deprecation, testing

#1871 Fixed broken :meth:`.VectorScene.vector_to_coords`
  manim/scene/vector_space_scene.py
  tests/control_data/graphical_units_data/vector_scene/vector_to_coords.npz
  tests/test_graphical_units/test_vector_scene.py
Labels: bugfix

#1843 Drop redundant OpenGL files and add metaclass support for `Surface`
  docs/source/examples.rst
  example_scenes/opengl.py
  manim/mobject/mobject.py
  manim/mobject/opengl_compatibility.py
  manim/mobject/opengl_mobject.py
  manim/mobject/opengl_three_dimensions.py
  manim/mobject/polyhedra.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/opengl_svg_mobject.py
  manim/mobject/svg/opengl_svg_path.py
  manim/mobject/three_dimensions.py
  manim/mobject/types/opengl_surface.py
  manim/opengl/__init__.py
  manim/scene/three_d_scene.py
  tests/control_data/graphical_units_data/opengl/Circle.npz
  tests/control_data/graphical_units_data/polyhedra/Dodecahedron.npz
  tests/control_data/graphical_units_data/polyhedra/Icosahedron.npz
  tests/control_data/graphical_units_data/polyhedra/Octahedron.npz
  tests/control_data/graphical_units_data/polyhedra/Tetrahedron.npz
  tests/control_data/graphical_units_data/threed/Dot3D.npz
  tests/control_data/graphical_units_data/threed/Sphere.npz
  tests/test_graphical_units/test_opengl.py
  tests/test_graphical_units/test_threed.py
  tests/test_set_attr.py
Labels: deprecation, breaking changes, opengl

#1881 Added methods :meth:`~.get_lines` and :meth:`~.get_value` to :class:`~.Angle`
  manim/mobject/geometry.py
Labels: enhancement

#1856 Modified Dockerfile to support multi-platform builds via ``docker buildx``
  docker/Dockerfile
  docker/readme.md
Labels: infrastructure

#1964 Add `CITATION.cff` and a method to automatically update this citation with new releases
  CITATION.cff
  README.md
  scripts/TEMPLATE.cff
  scripts/dev_changelog.py
Labels: infrastructure

#1987 Added support for using OpenGL in subprocess in Windows pipeline
  .github/workflows/ci.yml
  tests/__init__.py
Labels: infrastructure, opengl

#1985 Use `height` to determine `font_size` instead of the `_font_size` attribute.
  manim/mobject/numbers.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  tests/control_data/graphical_units_data/numbers/set_value_with_updaters.npz
  tests/test_graphical_units/test_numbers.py
  tests/test_numbers.py
  tests/test_texmobject.py
  tests/test_text_mobject.py
Labels: bugfix
