Repository ManimCommunity/manim, pull requests merged in 2021-01, with the labels that each got.

#894 Prepare new release: v0.2.0
  docs/source/changelog.rst
  pyproject.toml
Labels: release

#904 Added blank line between imports and class example
  README.md
Labels: easy review, enhancement

#903 Tiny grammar improvements in documentation
  docs/source/index.rst
Labels: easy review, enhancement

#906 Bugfix: allow new-style method animation to be used in animation groups
  manim/animation/animation.py
  manim/animation/composition.py
  manim/scene/scene.py
  tests/test_composition.py
Labels: bug, easy review

#907 Bugfix: make Scene.add_sound work again (when running with --disable_caching)
  manim/scene/scene.py
  tests/test_sound.py
Labels: bug, easy review

#742 Feature: unit conversion
  manim/__init__.py
  manim/utils/unit.py
  tests/test_units.py
Labels: enhancement, new feature

#916 Multipartite graph column layout
  manim/mobject/graph.py
Labels: enhancement

#932 Correctly parse log_dir
  manim/_config/utils.py
  tests/test_logging/basic_scenes_write_stuff.py
Labels: easy review

#938 Remove dependency on progressbar
  poetry.lock
  pyproject.toml
Labels: cleaning, easy review

#936 Fix BulletedList TeX environment problem and add a typing to get_module
  manim/mobject/svg/tex_mobject.py
  manim/utils/module_ops.py
Labels: bug, easy review

#941 Bugfix: add limit parameters to 'ThreeDAxes'
  manim/mobject/coordinate_systems.py
Labels: easy review, enhancement

#756 Fix 749: frame_height and frame_width can't be set via config file
  manim/_config/utils.py
  tests/test_config.py
Labels: docs, enhancement

#865 Rename get_submobject_index_labels to index_labels
  manim/utils/debug.py
Labels: easy review, enhancement

#917 Allow overriding new-style method animations
  manim/mobject/mobject.py
  tests/test_animate.py
Labels: enhancement, test requested

#948 New feature: allow passing a code string to Code
  manim/mobject/svg/code_mobject.py
Labels: easy review, enhancement, new feature

#947 Fixes #946 and miscellaneous fixes for PointCloundDot
  manim/constants.py
  manim/mobject/types/point_cloud_mobject.py
  tests/control_data/graphical_units_data/mobjects/PointCloudDotTest.npz
  tests/test_graphical_units/test_mobjects.py
Labels: easy review

#957 Bugfix: Raise NotImplementedError when trying to chain overridden method animations
  manim/mobject/mobject.py
  tests/test_animate.py
Labels: bug, easy review

#943 New Feature: IPython %%manim magic
  README.md
  docs/rtd-requirements.txt
  docs/source/reference.rst
  docs/source/tutorials/quickstart.rst
  manim/__init__.py
  manim/animation/animation.py
  manim/scene/scene_file_writer.py
  manim/utils/ipython_magic.py
  poetry.lock
  pyproject.toml
Labels: new feature

#954 Bugfix: fix edges lagging behind vertices in animations involving graphs
  manim/mobject/graph.py
Labels: easy review

#945 New feature: change_layout method for Graph mobject
  manim/mobject/graph.py
Labels: new feature
