Repository ManimCommunity/manim, pull requests merged in 2021-10, with the labels that each got.

#2118 Added 3D support for :class:`~.ArrowVectorField` and :class:`~.StreamLines`
  manim/mobject/vector_field.py
Labels: new feature

#2116 Made type hint for ``line_spacing`` argument of :class:`~.Paragraph` more accurate
  manim/mobject/svg/text_mobject.py
Labels: documentation

#2122 Fixed broken links in inheritance graphs by moving them to ``reference.rst``
  docs/source/reference.rst
  docs/source/reference_index/animations.rst
  docs/source/reference_index/cameras.rst
  docs/source/reference_index/mobjects.rst
  docs/source/reference_index/scenes.rst
Labels: documentation

#2124 Upgrade several dependencies (in particular: ``skia-pathops``)
  poetry.lock
  pyproject.toml
Labels: maintenance

#1990 Improved the implementation of :meth:`.CoordinateSystem.get_area` to work without Riemann rectangles, added new :meth:`.CoordinateSystem.get_area_with_riemann_rectangles`
  docs/source/examples.rst
  manim/mobject/coordinate_systems.py
  tests/control_data/graphical_units_data/plot/get_area.npz
  tests/control_data/graphical_units_data/plot/get_area_with_riemann_rectangles.npz
  tests/test_graphical_units/test_axes.py
Labels: enhancement, breaking changes

#2120 Changed ``manim_directive`` to use a clean configuration via ``tempconfig``
  docs/source/manim_directive.py
  manim/mobject/mobject.py
Labels: documentation

#2131 Copyedited the configuration tutorial in the documentation
  docs/source/tutorials/configuration.rst
Labels: documentation

#2094 Implemented :class:`~.ImplicitFunction` and :meth:`.CoordinateSystem.get_implicit_curve` for plotting implicit curves
  manim/mobject/coordinate_systems.py
  manim/mobject/functions.py
  poetry.lock
  pyproject.toml
  tests/control_data/graphical_units_data/coordinate_system/implicit_graph.npz
  tests/control_data/graphical_units_data/functions/ImplicitFunction.npz
  tests/test_graphical_units/test_coordinate_systems.py
  tests/test_graphical_units/test_functions.py
Labels: new feature, highlight

#2126 Fixed whitespace in info message issued by :meth:`.SceneFileWriter.clean_cache`
  manim/scene/scene_file_writer.py
Labels: maintenance

#2111 Improved setting of OpenGL colors
  manim/mobject/opengl_mobject.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/renderer/opengl_renderer.py
  tests/opengl/test_color_opengl.py
Labels: enhancement, opengl

#2114 Prepared new release, ``v0.11.0``
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.11.0-changelog.rst
  pyproject.toml
Labels: release

#2239 Removed erroneous raw string from text tutorial
  docs/source/tutorials/using_text.rst
Labels: documentation

#2136 Added type hints to all colors
  manim/utils/color.py
Labels: maintenance, typehints

#2168 Fixed order in function `cartesian_to_spherical`
  manim/mobject/geometry.py
  manim/utils/space_ops.py
  tests/test_space_ops.py
Labels: bugfix

#2243 Fixed wasteful recursion in :meth:`.Mobject.get_merged_array`
  manim/mobject/mobject.py
Labels: enhancement

#2142 Fixed opengl family duplicates issue and add tests
  manim/mobject/opengl_mobject.py
  manim/utils/iterables.py
  tests/opengl/test_family_opengl.py
Labels: bugfix, testing, opengl
