Repository ManimCommunity/manim, pull requests merged in 2021-04, with the labels that each got.

#1219 Updated Dockerfile (include dependencies for building documentation), moved documentation to main README
  README.md
  docker/Dockerfile
  docker/readme.md
Labels: documentation, infrastructure

#1201 Prevent crash on :meth:`~.Scene.embed` for empty scenes
  manim/scene/scene.py
Labels: bug, easy review

#1224 Fixed :class:`~.ShowIncreasingSubsets`, :class:`~.ShowSubmobjectsOneByOne`, and :class:`~.AddTextLetterByLetter`
  manim/animation/creation.py
Labels: bug, easy review

#1218 Removed BezierSpline from the example gallery
  docs/source/examples.rst
Labels: documentation

#1213 Updated TinyTex dependencies
  .github/manimdependency.json
Labels: infrastructure

#1206 Added Docstrings to :class:`~.Mobject`
  manim/mobject/mobject.py
Labels: documentation

#1217 Copyedited the document on testing in our documentation
  docs/source/contributing/testing.rst
Labels: documentation

#1013 Refactored the Command Line Interface to use Click instead of Argparse
  README.md
  docs/source/_static/command.png
  docs/source/installation/plugins.rst
  docs/source/tutorials/a_deeper_look.rst
  docs/source/tutorials/configuration.rst
  docs/source/tutorials/quickstart.rst
  example_scenes/basic.py
  manim/__main__.py
  manim/_config/default.cfg
  manim/_config/main_utils.py
  manim/_config/utils.py
  manim/cli/__init__.py
  manim/cli/cfg/__init__.py
  manim/cli/cfg/commands.py
  manim/cli/plugins/__init__.py
  manim/cli/plugins/commands.py
  manim/cli/render/__init__.py
  manim/cli/render/commands.py
  manim/cli/render/ease_of_access_options.py
  manim/cli/render/global_options.py
  manim/cli/render/output_options.py
  manim/cli/render/render_options.py
  manim/constants.py
  manim/mobject/mobject.py
  manim/renderer/webgl_renderer.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/ipython_magic.py
  manim/utils/module_ops.py
  manim/utils/space_ops.py
  poetry.lock
  pyproject.toml
  tests/test_commands.py
  tests/test_logging/test_logging.py
  tests/test_plugins/test_plugins.py
  tests/test_quality_flags.py
  tests/test_scene_rendering/test_caching_related.py
  tests/test_scene_rendering/test_cli_flags.py
  tests/utils/commands.py
Labels: breaking changes, highlight

#1235 Fixed version of decorator at <5.0.0
  poetry.lock
  pyproject.toml
Labels: infrastructure, maintenance

#1231 Improve changelog generation script
  docs/source/changelog.rst
  docs/source/changelog/0.5.0-changelog.rst
  scripts/dev_changelog.py
Labels: documentation

#1216 Use actions/checkout for cloning repository; black-checks
  .github/workflows/lint.yml
Labels: infrastructure

#1242 Added an example for the manim colormap
  manim/utils/color.py
Labels: documentation

#1254 Removed the comment warning that GitHub doesn't allow uploading video in the issue templates.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: infrastructure

#1255 CI: Fix macOS pipeline failure
  .github/workflows/ci.yml
  docs/source/installation/mac.rst
Labels: infrastructure

#1259 Removed deprecated CairoText class
  manim/mobject/svg/text_mobject.py
Labels: deprecation

#1249 Set corners of :class:`~.Rectangle` in counterclockwise direction
  manim/mobject/geometry.py
  tests/control_data/graphical_units_data/geometry/RoundedRectangleTest.npz
  tests/control_data/graphical_units_data/movements/HomotopyTest.npz
  tests/control_data/graphical_units_data/movements/MoveAlongPathTest.npz
  tests/control_data/graphical_units_data/threed/AmbientCameraMoveTest.npz
  tests/control_data/graphical_units_data/threed/CameraMoveTest.npz
  tests/control_data/graphical_units_data/threed/CubeTest.npz
Labels: enhancement

#1270 Added isort to pre_commit file
  .pre-commit-config.yaml
Labels: infrastructure

#1278 Fixed flake8 errors and removed linter/formatter workflows
  .github/workflows/black.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  docs/source/contributing/development.rst
  example_scenes/advanced_tex_fonts.py
  tests/conftest.py
Labels: infrastructure, maintenance

#1247 Added warning for the usage of `animate`
  manim/mobject/mobject.py
Labels: documentation

#1268 Added documentation explaining the differences between manim versions
  docs/source/installation.rst
  docs/source/installation/versions.rst
Labels: documentation

#1279 Added sphinx requirements to pyproject.toml
  docs/source/contributing/development.rst
  poetry.lock
  pyproject.toml
Labels: documentation, infrastructure

#1220 Added sanity checks to :meth:`~.Mobject.add_to_back` for Mobjects
  manim/mobject/mobject.py
  tests/test_vectorized_mobject.py
Labels: enhancement, maintenance

#1283 Set default value of keyword ``random_seed`` in Scene to None (was 0 and fixed before)
  manim/scene/scene.py
Labels: enhancement

#1029 Added example jupyter notebook into the examples folders
  .gitignore
  README.md
  docs/source/installation.rst
  example_scenes/manim_jupyter_example.ipynb
Labels: documentation, easy review

#1261 Render image automatically if no animation is played in a scene
  docs/source/manim_directive.py
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  tests/control_data/graphical_units_data/updaters/ValueTrackerTest.npz
  tests/test_graphical_units/test_coordinate_systems.py
  tests/test_graphical_units/test_functions.py
  tests/test_graphical_units/test_geometry.py
  tests/test_graphical_units/test_graphscene.py
  tests/test_graphical_units/test_mobjects.py
  tests/test_graphical_units/test_modifier_methods.py
  tests/test_graphical_units/test_threed.py
  tests/test_graphical_units/test_updaters.py
Labels: new feature

#1122 Support for specifying the interpolation algorithms for individual ImageMobjects
  manim/camera/camera.py
  manim/constants.py
  manim/mobject/types/image_mobject.py
  tests/control_data/graphical_units_data/img_and_svg/ImageInterpolationTest.npz
  tests/test_graphical_units/test_img_and_svg.py
Labels: enhancement

#1274 Fix :meth:`~.VMobject.point_from_proportion` to account for the length of curves.
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  tests/test_vectorized_mobject.py
Labels: bug

#1284 Updated readme by providing the correct link to the example_scenes
  README.md
Labels: documentation

#1291 Grammar fixes to README.md
  README.md
Labels: documentation

#1293 Minor fixes - reduce lines
  manim/mobject/types/point_cloud_mobject.py
  manim/renderer/opengl_renderer.py
Labels: maintenance

#1232 Further docstrings and examples for :class:`~.Mobject`
  manim/mobject/mobject.py
Labels: documentation

#1295 Fix grammar and typos in the CODE OF CONDUCT
  CODE_OF_CONDUCT.md
Labels: maintenance

#1292 Remove unnecessary imports from files
  manim/animation/fading.py
  manim/animation/transform_matching_parts.py
  manim/grpc/impl/frame_server_impl.py
  manim/mobject/numbers.py
  manim/mobject/opengl_three_dimensions.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/three_dimensions.py
  manim/plugins/plugins_flags.py
  manim/renderer/opengl_renderer.py
  manim/scene/scene.py
Labels: maintenance

#1294 Added mixed-line-ending to .pre-commit-config.yaml
  .github/manimdependency.json
  .pre-commit-config.yaml
  docs/make.bat
  tests/test_graphical_units/img_svg_resources/video_icon.svg
Labels: infrastructure

#1251 Switch documentation from guzzle-sphinx-theme to furo
  docs/requirements.txt
  docs/source/_static/custom.css
  docs/source/_static/manim-logo-sidebar-dark.svg
  docs/source/conf.py
  docs/source/examples.rst
  docs/source/manim_directive.py
  docs/source/reference.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#1296 Fix random pipeline TeX failures
  manim/utils/tex.py
  tests/control_data/graphical_units_data/coordinate_systems/NumberPlaneTest.npz
  tests/control_data/graphical_units_data/plot/AxesTest.npz
  tests/control_data/graphical_units_data/plot/PlotFunctions.npz
Labels: bug, infrastructure

#1246 Added docstrings for :class:`~.ValueTracker`
  manim/mobject/value_tracker.py
  tests/test_value_tracker.py
Labels: documentation

#1299 Red pixels (different value) now appear over green pixels (same value) in GraphicalUnitTest
  tests/utils/GraphicalUnitTester.py
Labels: testing

#1297 Change docs to use viewcode extension instead of linkcode
  docs/source/conf.py
Labels: documentation

#1298 Add double backquotes for rst code samples (value_tracker.py)
  manim/mobject/value_tracker.py
Labels: documentation

#1275 Add SVG <line> element support to :class:`~.SVGMobject`
  manim/mobject/svg/svg_mobject.py
  tests/control_data/graphical_units_data/img_and_svg/LineTest.npz
  tests/test_graphical_units/img_svg_resources/line.svg
  tests/test_graphical_units/test_img_and_svg.py
Labels: enhancement

#1305 Automatically remove long tick marks not within the range of the :class:`~NumberLine`
  manim/mobject/number_line.py
Labels: bug

#1301 Added futher docstrings and typehints to :class:`~.Mobject`
  manim/mobject/mobject.py
Labels: documentation

#1237 Notify user if they are using an outdated version of Manim
  docs/source/tutorials/configuration.rst
  manim/__main__.py
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/cli/render/commands.py
  manim/cli/render/global_options.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#1234 New :class:`~.Mobject` method, :meth:`~.Mobject.get_midpoint`
  manim/mobject/mobject.py
Labels: enhancement

#1323 Blacken Docs Strings
  .pre-commit-config.yaml
  docs/source/contributing/documentation.rst
  docs/source/contributing/testing.rst
  docs/source/tutorials/configuration.rst
  docs/source/tutorials/quickstart.rst
  manim/_config/__init__.py
  manim/_config/utils.py
  manim/mobject/svg/opengl_text_mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/utils/color.py
  poetry.lock
  pyproject.toml
Labels: documentation, infrastructure

#1326 Improve documentation of :class:`~.ManimMagic` (in particular: fix documented order of CLI flags)
  manim/utils/ipython_magic.py
Labels: documentation

#1315 Fix performance issues with :meth:`~.VMobject.get_arc_length`, stemming from :pr:`1302`
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: enhancement

#1302 Raise appropriate errors in :meth:`~.VMobject.point_from_proportion`
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  tests/test_vectorized_mobject.py
Labels: enhancement

#1328 Docs: Update Brace example
  manim/mobject/svg/brace.py
Labels: documentation

#1245 Added filled angle Example
  manim/mobject/geometry.py
Labels: documentation

#1282 Fix typing hints in vectorized_mobject.py based on mypy
  manim/mobject/types/vectorized_mobject.py
  manim/utils/bezier.py
Labels: maintenance

#1335 Added import statements to examples in documentation
  docs/source/manim_directive.py
Labels: documentation

#1210 Added tutorial chapter on coordinates of an mobject
  docs/source/tutorials/building_blocks.rst
Labels: documentation

#1257 CI: Caching ffmpeg, tinytex dependencies and poetry venv
  .github/manimdependency.json
  .github/workflows/ci.yml
Labels: infrastructure

#1339 CI: Fix macOS installation error from creating file in read-only file system
  .github/workflows/ci.yml
Labels: infrastructure

#1241 Type Annotations: Fixing errors showing up in static type checking tool mypy
  manim/animation/animation.py
  manim/animation/composition.py
  manim/animation/creation.py
  manim/animation/transform.py
  manim/mobject/mobject.py
  manim/mobject/mobject_update_utils.py
  manim/scene/scene.py
  manim/utils/rate_functions.py
Labels: maintenance

#1304 Improve Tex string splitting at double braces: only split for double brace groups
  manim/mobject/svg/tex_mobject.py
Labels: enhancement

#1346 Fixed errors introduced by stray print in :class:`~.MathTex`
  manim/mobject/svg/tex_mobject.py
Labels: bugfix

#1285 Add :meth:`~.Scene.interactive_embed` for OpenGL rendering
  manim/cli/render/commands.py
  manim/renderer/opengl_renderer.py
  manim/scene/scene.py
  manim/utils/exceptions.py
Labels: new feature

#1338 Added documentation guidelines for type hints
  docs/source/contributing/documentation.rst
Labels: documentation

#1349 Removed the deprecated Small Dot
  manim/constants.py
  manim/mobject/geometry.py
  tests/test_graphical_units/test_geometry.py
Labels: deprecation

#1358 Fixed link to installation instructions for developers
  docs/source/contributing/development.rst
Labels: documentation

#1359 Make FILE a required argument
  manim/cli/render/commands.py
Labels: easy review, enhancement

#1363 Change of TeX complier and output file format
  example_scenes/customtex.py
Labels: enhancement

#1370 Remove TexMobject and TextMobject
  manim/mobject/svg/tex_mobject.py
Labels: deprecation

#1364 Added :meth:`~.Mobject.match_points`
  manim/mobject/mobject.py
  tests/control_data/graphical_units_data/transform/MatchPointsScene.npz
  tests/test_graphical_units/test_transform.py
Labels: documentation, enhancement

#1360 Grammatical error corrections in documentation
  docs/source/contributing.rst
  docs/source/contributing/development.rst
  docs/source/contributing/documentation.rst
  docs/source/contributing/testing.rst
  docs/source/examples.rst
  docs/source/installation/for_dev.rst
  docs/source/installation/linux.rst
  docs/source/installation/troubleshooting.rst
  docs/source/installation/versions.rst
  docs/source/reporting_bugs.rst
  docs/source/tutorials/a_deeper_look.rst
  docs/source/tutorials/building_blocks.rst
  docs/source/tutorials/configuration.rst
  docs/source/tutorials/quickstart.rst
Labels: documentation, maintenance

#1354 Refactored and deprecated a few functions in space_ops.py
  manim/camera/camera.py
  manim/mobject/changing.py
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  manim/mobject/opengl_geometry.py
  manim/mobject/opengl_mobject.py
  manim/mobject/svg/brace.py
  manim/mobject/three_d_utils.py
  manim/mobject/three_dimensions.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/scene/vector_space_scene.py
  manim/utils/paths.py
  manim/utils/space_ops.py
  tests/test_graphical_units/test_movements.py
  tests/test_number_line.py
Labels: deprecation, maintenance

#1355 Rewrite `put_start_and_end_on` to work in 3D
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  tests/control_data/graphical_units_data/threed/MovingVerticesTest.npz
  tests/test_graphical_units/test_threed.py
Labels: bugfix

#1395 SVG transforms now handle exponent notation (6.02e23)
  manim/mobject/svg/svg_mobject.py
Labels: bugfix

#1362 Quick reference to modules
  docs/source/index.rst
  manim/mobject/geometry.py
  manim/mobject/value_tracker.py
Labels: documentation

#1380 Allow image objects as background images
  manim/camera/camera.py
  manim/mobject/types/vectorized_mobject.py
Labels: enhancement

#1383 Overhaul of the `animation.indication` module interfaces
  manim/animation/indication.py
  tests/control_data/graphical_units_data/indication/CircumscribeTest.npz
  tests/control_data/graphical_units_data/indication/ShowCreationThenDestructionTest.npz
  tests/control_data/graphical_units_data/indication/ShowCreationThenFadeOutTest.npz
  tests/control_data/graphical_units_data/indication/ShowPassingFlashAroundTest.npz
  tests/control_data/graphical_units_data/indication/ShowPassingFlashTest.npz
  tests/control_data/graphical_units_data/indication/WiggleOutThenInTest.npz
  tests/control_data/graphical_units_data/indication/WiggleTest.npz
  tests/test_graphical_units/test_indication.py
Labels: enhancement, new feature

#1421 Updated changelog generator's labels and removed pre-commit bot from changelog
  scripts/dev_changelog.py
Labels: infrastructure

#1381 Hot reloading for the OpenGL renderer
  manim/cli/render/commands.py
  manim/scene/scene.py
  poetry.lock
  pyproject.toml
Labels: new feature

#1368 Added a check to ensure checking for the latest version was successful
  manim/cli/render/commands.py
Labels: bugfix

#1407 Fix bug in :meth:`vector_coordinate_label` and move it to :class:`~.geometry.py`
  manim/mobject/geometry.py
  manim/mobject/matrix.py
  manim/scene/vector_space_scene.py
Labels: enhancement, refactor

#1385 Added :meth:`~.CoordinateSystem.get_line_graph` for plotting a line graph
  manim/mobject/coordinate_systems.py
Labels: new feature

#1424 Fixed all current docbuild warnings
  docs/source/contributing/development.rst
  docs/source/contributing/documentation.rst
  docs/source/installation.rst
  docs/source/installation/versions.rst
  manim/mobject/mobject.py
  manim/mobject/three_dimensions.py
  manim/mobject/types/vectorized_mobject.py
Labels: documentation, easy review, infrastructure

#1161 Upgrades to CoordinateSystem and graphing.
  manim/mobject/coordinate_systems.py
  manim/mobject/functions.py
  manim/mobject/geometry.py
  manim/mobject/number_line.py
  manim/scene/graph_scene.py
  tests/control_data/graphical_units_data/coordinate_systems/NumberPlaneTest.npz
  tests/control_data/graphical_units_data/plot/AxesTest.npz
  tests/control_data/graphical_units_data/plot/PlotFunctions.npz
  tests/control_data/graphical_units_data/threed/AxesTest.npz
  tests/control_data/graphical_units_data/threed/FixedInFrameMObjectTest.npz
  tests/test_coordinate_system.py
  tests/test_graphical_units/test_axes.py
  tests/test_graphical_units/test_coordinate_systems.py
  tests/test_graphical_units/test_functions.py
Labels: breaking changes, enhancement, maintenance

#1398 Fix and enhance `Mobject.arrange_in_grid`
  manim/mobject/mobject.py
Labels: enhancement

#1427 Add URL's to pyproject.toml
  poetry.lock
  pyproject.toml
Labels: infrastructure, maintenance
