Repository ManimCommunity/manim, pull requests merged in 2021-11, with the labels that each got.

#2236 Added ``skip_animations`` argument to :meth:``.Scene.next_section``
  docs/source/tutorials/a_deeper_look.rst
  manim/renderer/cairo_renderer.py
  manim/renderer/opengl_renderer.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/section.py
  tests/control_data/videos_data/SceneWithSections.json
  tests/control_data/videos_data/SceneWithSkipAnimations.json
  tests/test_graphical_units/testing/_test_class_makers.py
  tests/test_scene_rendering/simple_scenes.py
  tests/test_scene_rendering/test_play_logic.py
  tests/test_scene_rendering/test_sections.py
Labels: new feature

#2162 Implemented :meth:`.MovingCamera.auto_zoom` for automatically zooming onto specified mobjects
  manim/camera/camera.py
  manim/camera/moving_camera.py
  tests/test_auto_zoom.py
Labels: new feature

#2128 Added keyword arguments ``match_center``, ``match_width`` etc. to :meth:`.Mobject.become`
  manim/mobject/mobject.py
  tests/control_data/graphical_units_data/mobjects/become.npz
  tests/test_graphical_units/test_mobjects.py
Labels: new feature

#2138 Show example for :meth:`~.Vector.coordinate_label` and add more customization for :class:`~.Matrix`.
  manim/mobject/geometry.py
  manim/mobject/matrix.py
Labels: documentation, enhancement

#2232 Fixed :class:`.Graph` stopping to update after animating additions/deletions of vertices or edges
  manim/animation/composition.py
  manim/mobject/graph.py
  tests/test_graph.py
Labels: bugfix

#2244 Fixed :meth:`.CoordinateSystem.get_area` when using few plot points and a boundary graph
  manim/mobject/coordinate_systems.py
  tests/control_data/graphical_units_data/plot/get_area.npz
  tests/control_data/graphical_units_data/plot/get_area_with_boundary_and_few_plot_points.npz
  tests/test_graphical_units/test_axes.py
Labels: bugfix

#2245 Removed deprecated method ``get_center_point`` and parameters ``azimuth_label_scale``, ``number_scale_value``, ``label_scale``, ``scale_factor``, ``size``, ``x_min``, ``x_max``, ``delta_x``, ``y_min``, ``y_max``, ``delta_y``
  manim/mobject/coordinate_systems.py
  manim/mobject/number_line.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/vector_field.py
Labels: deprecation

#2151 Allow setting the input file via a config file
  manim/_config/utils.py
  manim/cli/render/commands.py
  tests/control_data/videos_data/InputFileViaCfg.json
  tests/test_scene_rendering/test_cli_flags.py
Labels: new feature

#1926 OpenGL: changed ``submobjects`` to be a property
  manim/mobject/opengl_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: deprecation, maintenance, opengl

#2247 Prepared new release ``v0.12.0``
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.12.0-changelog.rst
  pyproject.toml
Labels: release

#2272 Added test for :class:`~.Broadcast`
  tests/control_data/graphical_units_data/specialized/Broadcast.npz
  tests/test_graphical_units/test_specialized.py
Labels: enhancement

#2300 Add contact email for PyPi
  pyproject.toml
Labels: enhancement

#2294 Made `index.html` more concise and rearranged order of tutorials
  docs/source/index.rst
  docs/source/tutorials.rst
Labels: documentation

#2310 Clarified that Manim does not support Python 3.10 yet in the documentation
  docs/source/installation.rst
  docs/source/installation/linux.rst
  docs/source/installation/windows.rst
Labels: documentation

#2292 Fixed positioning of :class:`~.Flash`
  manim/animation/indication.py
Labels: bugfix

#2313 Finalized translation process and documentation
  docs/source/contributing/internationalization.rst
Labels: documentation, highlight, i18n

#2318 Add missing tests for AnimationGroup 'remover' field #1846
  tests/control_data/graphical_units_data/composition/animationgroup_is_passing_remover_to_animations.npz
  tests/control_data/graphical_units_data/composition/animationgroup_is_passing_remover_to_nested_animationgroups.npz
  tests/test_composition.py
  tests/test_graphical_units/test_composition.py
Labels: testing

#2331 Remove deprecations up to `v0.12.0`
  docs/source/reference.rst
  docs/source/reference_index/scenes.rst
  manim/__init__.py
  manim/camera/three_d_camera.py
  manim/mobject/changing.py
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  manim/mobject/opengl_geometry.py
  manim/mobject/opengl_mobject.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/reconfigurable_scene.py
  manim/scene/sample_space_scene.py
  manim/scene/three_d_scene.py
Labels: deprecation

#2230 Fixed mistakes in building_blocks
  docs/source/tutorials/building_blocks.rst
Labels: documentation

#2319 Swapped `dotL` and `dotR` in :meth:`Mobject.interpolate` example
  manim/mobject/mobject.py
Labels: documentation

#2327 Correct type hint for `labels` parameter of :class:`~.Graph`
  manim/mobject/graph.py
Labels: maintenance, typehints

#2328 Provide alpha multiplied RGBA values to cairo
  manim/utils/color.py
  tests/test_color.py
Labels: bugfix, cairo

#2279 Added documentation for discontinuous functions
  manim/mobject/functions.py
Labels: documentation

#2216 Edited and added new sections to the quickstart tutorial
  docs/source/tutorials/quickstart.rst
Labels: documentation
