Repository ManimCommunity/manim, pull requests merged in 2021-05, with the labels that each got.

#1386 Implement utility methods for adding/removing vertices and edges of graphs; allow custom mobjects as vertices
  manim/mobject/graph.py
  manim/mobject/mobject.py
  tests/test_animate.py
  tests/test_graph.py
Labels: new feature

#1425 Added a "How to Cite Manim" section to the Readme
  README.md
  docs/source/index.rst
Labels: documentation

#1430 Un-deprecated GraphScene (will be deprecated later), fixed an old-style call to NumberPlane
  manim/mobject/coordinate_systems.py
  manim/scene/graph_scene.py
  tests/control_data/graphical_units_data/coordinate_systems/NumberPlaneTest.npz
  tests/control_data/graphical_units_data/threed/AxesTest.npz
  tests/control_data/graphical_units_data/threed/FixedInFrameMObjectTest.npz
  tests/test_graphical_units/test_threed.py
Labels: documentation, maintenance

#1435 CI: Update poetry cache when new version is released
  .github/workflows/ci.yml
Labels: infrastructure

#1436 Cache poetry venv with `pyproject.toml` hash in key
  .github/workflows/ci.yml
Labels: infrastructure

#1431 Fix CLI bugs
  docs/source/manim_directive.py
  manim/__main__.py
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/cli/render/commands.py
  manim/cli/render/output_options.py
  manim/cli/render/render_options.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/file_ops.py
  poetry.lock
  pyproject.toml
  tests/helpers/graphical_units.py
Labels: bugfix, deprecation

#1434 Prepare v0.6.0
  docs/source/changelog/0.6.0-changelog.rst
  pyproject.toml
  scripts/dev_changelog.py
Labels: release

#1445 Remove $ from tutorial commands
  docs/source/tutorials/a_deeper_look.rst
  docs/source/tutorials/configuration.rst
  docs/source/tutorials/quickstart.rst
Labels: documentation

#1453 manim_directive: fix image links in docs - Windows
  docs/source/manim_directive.py
Labels: infrastructure

#1457 Fixing broken doc links
  docs/source/contributing/documentation.rst
  docs/source/installation/for_dev.rst
Labels: documentation

#1460 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: easy review, infrastructure

#1418 Added project management commands
  manim/__main__.py
  manim/cli/cfg/group.py
  manim/cli/init/__init__.py
  manim/cli/init/commands.py
  manim/cli/new/__init__.py
  manim/cli/new/group.py
  manim/templates/Axes.mtp
  manim/templates/Default.mtp
  manim/templates/MovingCamera.mtp
  manim/templates/template.cfg
  manim/utils/file_ops.py
  tests/test_commands.py
Labels: new feature

#1451 Reduce complexity of AngleExample
  manim/mobject/geometry.py
Labels: documentation

#1375 Deprecation of ShowCreation
  manim/animation/creation.py
Labels: deprecation

#1402 Added typestring parser checker
  docs/source/contributing/documentation.rst
Labels: documentation

#1477 Update RDT sphinx package to version 3.5.3
  docs/requirements.txt
Labels: infrastructure

#1481 pyproject.toml: poetry_core -> poetry-core
  pyproject.toml
Labels: infrastructure

#1470 Drop support for Python 3.6
  poetry.lock
  pyproject.toml
Labels: breaking changes, maintenance

#1473 Added easy example for `arrange_in_grid`
  manim/mobject/mobject.py
Labels: documentation

#1449 Added PointCloudDot example
  manim/mobject/types/point_cloud_mobject.py
Labels: documentation

#1458 Refine docs of `Text` ( add `disable_ligatures=True` for t2c)
  manim/mobject/svg/text_mobject.py
Labels: documentation

#1492 Remove stray print statements introduced in #1404
  manim/utils/deprecation.py
  poetry.lock
Labels: maintenance

#1382 Expand documentation, testing, and functionality of ValueTrackers; remove ExponentialValueTracker
  manim/mobject/value_tracker.py
  tests/test_value_tracker.py
Labels: documentation, enhancement, testing

#1439 Cleaning `Sequence typehints`
  manim/mobject/coordinate_systems.py
  manim/mobject/svg/brace.py
Labels: typehints

#1502 Added `center` parameter to :class:`~.Sphere` and `point` parameter to :class:`~.Dot3D`
  manim/mobject/three_dimensions.py
Labels: enhancement

#1499 Updated Discord links in the docs to point towards a standardized redirect
  CODE_OF_CONDUCT.md
  README.md
  docs/source/contributing/testing.rst
  docs/source/index.rst
  docs/source/installation/plugins.rst
  docs/source/installation/troubleshooting.rst
  docs/source/reporting_bugs.rst
  pyproject.toml
Labels: infrastructure

#1485 Added `Title` example for the docs
  manim/mobject/svg/tex_mobject.py
Labels: documentation

#1272 Implement metaclass approach in geometry module to make mobjects compatible with cairo and opengl rendering
  manim/__init__.py
  manim/mobject/geometry.py
  manim/mobject/opengl_mobject.py
  manim/mobject/shape_matchers.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/utils/space_ops.py
Labels: maintenance, new feature

#1516 Update docs to use t_range instead of t_min and t_max in ParametricFunction
  manim/mobject/functions.py
Labels: documentation, easy review

#1504 Color module enhancements
  manim/mobject/types/vectorized_mobject.py
  manim/utils/color.py
  tests/control_data/graphical_units_data/threed/AmbientCameraMoveTest.npz
  tests/control_data/graphical_units_data/threed/Arrow3DTest.npz
  tests/control_data/graphical_units_data/threed/AxesTest.npz
  tests/control_data/graphical_units_data/threed/CameraMoveTest.npz
  tests/control_data/graphical_units_data/threed/ConeTest.npz
  tests/control_data/graphical_units_data/threed/CubeTest.npz
  tests/control_data/graphical_units_data/threed/CylinderTest.npz
  tests/control_data/graphical_units_data/threed/Dot3DTest.npz
  tests/control_data/graphical_units_data/threed/Line3DTest.npz
  tests/control_data/graphical_units_data/threed/SphereTest.npz
  tests/control_data/graphical_units_data/threed/TorusTest.npz
Labels: documentation, maintenance, new feature

#1422 Added :func:`~.override_animation` decorator
  manim/animation/animation.py
  manim/mobject/logo.py
  manim/mobject/mobject.py
  manim/utils/exceptions.py
  tests/test_override_animation.py
Labels: new feature

#1454 Fading module enhancements
  docs/source/examples.rst
  example_scenes/basic.py
  manim/animation/fading.py
  manim/animation/indication.py
  manim/animation/transform_matching_parts.py
  manim/mobject/types/vectorized_mobject.py
  tests/test_composition.py
  tests/test_graphical_units/test_creation.py
Labels: deprecation, enhancement

#1526 Fix fading
  manim/animation/fading.py
Labels: bugfix, easy review

#1527 Improved handling of substring isolation within sqrt, and fixed a bug with transform_mismatch for the matching shape transforms
  manim/animation/transform_matching_parts.py
  manim/mobject/svg/tex_mobject.py
Labels: bugfix, easy review

#1531 Don't use deprecated methods in deprecation.py
  manim/utils/deprecation.py
Labels: maintenance

#1511 OpenGL compatibility via metaclass: svg_mobject, text_mobject, tex_mobject
  manim/mobject/svg/opengl_svg_mobject.py
  manim/mobject/svg/opengl_svg_path.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/svg_path.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: enhancement, maintenance

#1541 Fixing broken links and other minor doc things
  docs/source/contributing.rst
  docs/source/contributing/development.rst
  docs/source/contributing/testing.rst
  docs/source/installation.rst
  docs/source/installation/troubleshooting.rst
  docs/source/installation/versions.rst
  docs/source/installation/win.rst
  docs/source/reference.rst
  manim/mobject/svg/opengl_text_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: documentation

#1490 Added :class:`~.Polygram`, rework the polygon inheritance tree, and add :class:`~.Star`
  manim/mobject/geometry.py
  manim/utils/space_ops.py
  tests/control_data/graphical_units_data/geometry/PolygramTest.npz
  tests/control_data/graphical_units_data/geometry/RegularPolygramTest.npz
  tests/control_data/graphical_units_data/geometry/StarTest.npz
  tests/test_graphical_units/test_geometry.py
Labels: new feature

#1467 Align axes and parametric functions/surfaces when using `Axes` and `ThreeDAxes`
  manim/mobject/coordinate_systems.py
  tests/test_axes_shift.py
Labels: bugfix

#1512 OpenGL compatibility via metaclass: graph
  manim/mobject/graph.py
Labels: enhancement, maintenance

#1211 Refactored scene caching and fixed issue when a different hash was produced when copying a mobject in the scene
  manim/utils/hashing.py
  tests/test_hashing.py
  tests/test_scene_rendering/test_cairo_renderer.py
Labels: bugfix, maintenance

#1567 Compatibility Fixes with ManimPango v0.3.0
  .readthedocs.yml
  docs/rtd-requirements.txt
  manim/mobject/svg/text_mobject.py
  poetry.lock
  pyproject.toml
Labels: enhancement, maintenance

#1480 Add logging info to tex errors
  manim/utils/tex_file_writing.py
Labels: enhancement

#1548 New feature: :class:`ArcBrace`
  manim/mobject/svg/brace.py
  tests/control_data/graphical_units_data/brace/ArcBraceTest.npz
  tests/test_graphical_units/test_brace.py
Labels: new feature

#1570 Output errors to stderr
  manim/_config/__init__.py
  manim/_config/logger_utils.py
  manim/cli/render/commands.py
  tests/test_logging/basic_scenes_error.py
  tests/test_logging/test_logging.py
Labels: bugfix, easy review

#1556 Try pytest-xdist for parallelization in tests
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_deprecation.py
  tests/test_sound.py
  tests/test_texmobject.py
Labels: maintenance, testing

#1566 New feature: Add grid to Rectangle
  manim/mobject/geometry.py
Labels: easy review, new feature

#1513 Fixed rotation of gradients while rotating a VMobject
  manim/mobject/types/vectorized_mobject.py
  tests/control_data/graphical_units_data/modifier_methods/GradientRotationTest.npz
  tests/test_graphical_units/test_modifier_methods.py
Labels: bugfix

#1545 Fix outdated parameters for :class:`LinearTransformationScene` and add an example + typing.
  manim/scene/vector_space_scene.py
Labels: bugfix, documentation

#1509 Copyedited Documentation
  docs/source/installation/for_dev.rst
  docs/source/installation/plugins.rst
  docs/source/installation/troubleshooting.rst
  docs/source/installation/win.rst
  docs/source/tutorials/building_blocks.rst
  docs/source/tutorials/configuration.rst
Labels: documentation

#1447 Added :class:~.PolarPlane for polar coordinates.
  manim/mobject/coordinate_systems.py
  tests/test_coordinate_system.py
Labels: new feature

#1577 Added new metaclass ConvertToOpenGL (replacing MetaVMobject), restore IntelliSense
  manim/mobject/geometry.py
  manim/mobject/graph.py
  manim/mobject/opengl_compatibility.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/svg_path.py
  manim/mobject/types/vectorized_mobject.py
Labels: enhancement

#1584 Added a check for `0` in :meth:`~.round_corners`
  manim/mobject/geometry.py
Labels: easy review, enhancement

#1589 OpenGL compatibility via metaclass: ValueTracker
  manim/mobject/opengl_value_tracker.py
  manim/mobject/value_tracker.py
  manim/opengl/__init__.py
Labels: enhancement, refactor

#1588 Fixed multiple animations being saved in the same file
  manim/utils/module_ops.py
Labels: bugfix

#1472 Porting methods from :class:`GraphScene` to :class:`CoordinateSystem`
  manim/mobject/coordinate_systems.py
  manim/mobject/functions.py
  manim/mobject/geometry.py
  manim/mobject/number_line.py
Labels: bugfix, enhancement, refactor

#1415 New example for gallery and some docs refinements
  docs/source/examples.rst
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
Labels: documentation

#1598 Update examples to use :class:`Axes` and deprecate :class:`GraphScene`
  docs/source/examples.rst
  manim/mobject/coordinate_systems.py
  manim/mobject/functions.py
  manim/mobject/number_line.py
  manim/scene/graph_scene.py
  manim/scene/moving_camera_scene.py
Labels: deprecation, documentation

#1596 Fix indexing for non-whitespace tex arg separator
  manim/mobject/svg/tex_mobject.py
  tests/test_texmobject.py
Labels: bugfix

#1552 Removed unwanted parameters in geometry
  manim/mobject/geometry.py
  manim/mobject/opengl_geometry.py
Labels: refactor

#1574 Fixed error when processing SVG with omitted elliptical arc command
  manim/mobject/svg/svg_path.py
  tests/control_data/graphical_units_data/img_and_svg/HeartTest.npz
  tests/test_graphical_units/img_svg_resources/heart.svg
  tests/test_graphical_units/test_img_and_svg.py
Labels: bugfix

#1606 Bring back ``DARK_BLUE``
  manim/utils/color.py
Labels: revert

#1599 Added example for Annulus
  manim/mobject/geometry.py
Labels: documentation
