Repository ManimCommunity/manim, pull requests merged in 2021-12, with the labels that each got.

#2348 Updated translation source files
  docs/i18n/gettext/changelog/0.12.0-changelog.pot
  docs/i18n/gettext/contributing/internationalization.pot
  docs/i18n/gettext/examples.pot
  docs/i18n/gettext/index.pot
  docs/i18n/gettext/installation.pot
  docs/i18n/gettext/installation/linux.pot
  docs/i18n/gettext/installation/troubleshooting.pot
  docs/i18n/gettext/installation/windows.pot
  docs/i18n/gettext/reference/manim._config.utils.ManimConfig.pot
  docs/i18n/gettext/reference/manim.animation.animation.Animation.pot
  docs/i18n/gettext/reference/manim.animation.animation.Wait.pot
  docs/i18n/gettext/reference/manim.animation.composition.AnimationGroup.pot
  docs/i18n/gettext/reference/manim.animation.composition.Succession.pot
  docs/i18n/gettext/reference/manim.animation.transform.TransformAnimations.pot
  docs/i18n/gettext/reference/manim.animation.transform.TransformFromCopy.pot
  docs/i18n/gettext/reference/manim.camera.camera.Camera.pot
  docs/i18n/gettext/reference/manim.camera.moving_camera.MovingCamera.pot
  docs/i18n/gettext/reference/manim.camera.three_d_camera.ThreeDCamera.pot
  docs/i18n/gettext/reference/manim.mobject.coordinate_systems.Axes.pot
  docs/i18n/gettext/reference/manim.mobject.coordinate_systems.CoordinateSystem.pot
  docs/i18n/gettext/reference/manim.mobject.coordinate_systems.NumberPlane.pot
  docs/i18n/gettext/reference/manim.mobject.coordinate_systems.PolarPlane.pot
  docs/i18n/gettext/reference/manim.mobject.coordinate_systems.ThreeDAxes.pot
  docs/i18n/gettext/reference/manim.mobject.frame.FullScreenFadeRectangle.pot
  docs/i18n/gettext/reference/manim.mobject.frame.PictureInPictureFrame.pot
  docs/i18n/gettext/reference/manim.mobject.functions.ParametricFunction.pot
  docs/i18n/gettext/reference/manim.mobject.geometry.Vector.pot
  docs/i18n/gettext/reference/manim.mobject.matrix.Matrix.pot
  docs/i18n/gettext/reference/manim.mobject.matrix.MobjectMatrix.pot
  docs/i18n/gettext/reference/manim.mobject.mobject.Mobject.pot
  docs/i18n/gettext/reference/manim.mobject.number_line.NumberLine.pot
  docs/i18n/gettext/reference/manim.mobject.table.Table.pot
  docs/i18n/gettext/reference/manim.mobject.three_dimensions.Line3D.pot
  docs/i18n/gettext/reference/manim.mobject.types.vectorized_mobject.VMobject.pot
  docs/i18n/gettext/reference/manim.scene.reconfigurable_scene.ReconfigurableScene.pot
  docs/i18n/gettext/reference/manim.scene.reconfigurable_scene.pot
  docs/i18n/gettext/reference/manim.scene.sample_space_scene.SampleSpaceScene.pot
  docs/i18n/gettext/reference/manim.scene.sample_space_scene.pot
  docs/i18n/gettext/reference/manim.scene.scene.Scene.pot
  docs/i18n/gettext/reference/manim.scene.scene_file_writer.SceneFileWriter.pot
  docs/i18n/gettext/reference/manim.scene.section.DefaultSectionType.pot
  docs/i18n/gettext/reference/manim.scene.section.Section.pot
  docs/i18n/gettext/reference/manim.scene.section.pot
  docs/i18n/gettext/reference/manim.utils.commands.pot
  docs/i18n/gettext/reference/manim.utils.images.pot
  docs/i18n/gettext/reference/manim.utils.scale.LinearBase.pot
  docs/i18n/gettext/reference/manim.utils.scale.LogBase.pot
  docs/i18n/gettext/reference/manim.utils.scale.pot
  docs/i18n/gettext/reference_index/scenes.pot
  docs/i18n/gettext/reference_index/utilities_misc.pot
  docs/i18n/gettext/tutorials/a_deeper_look.pot
  docs/i18n/gettext/tutorials/building_blocks.pot
  docs/i18n/gettext/tutorials/quickstart.pot
  docs/i18n/gettext/tutorials/using_text.pot
Labels: i18n

#2344 Resized SVG logos, fit content to canvas
  logo/dark/dark_background.svg
  logo/dark/transparent_background.svg
  logo/light/light_background.svg
  logo/light/transparent_background.svg
  logo/monochromatic/monochromatic_black.svg
  logo/monochromatic/monochromatic_white.svg
Labels: enhancement, easy review

#2351 Add missing `**kwargs` parameter to meth:`Table.add_highlighted_cell`.
  manim/mobject/table.py
Labels: enhancement

#2343 Replaced current tree layout algorithm with SageMath's for improved layout of large trees.
  manim/mobject/graph.py
Labels: enhancement

#2325 `quality` argument improvements
  manim/_config/utils.py
  manim/cli/render/render_options.py
Labels: bugfix

#2347 Moved ``manim_directive.py`` to ``manim.utils.docbuild``
  docs/source/conf.py
  docs/source/contributing/development.rst
  docs/source/contributing/examples.rst
  manim/utils/docbuild/manim_directive.py
Labels: enhancement

#2276 Fixed :class:`~.ThreeDAxes` axis shift bug.
  manim/mobject/coordinate_systems.py
  tests/test_axes_shift.py
Labels: bugfix

#2359 Resolved ``ValueError`` when calling ``manim cfg write``
  manim/cli/cfg/group.py
Labels: bugfix

#2267 Implemented :meth:`.CoordinateSystem.plot_antiderivative_graph`
  manim/mobject/coordinate_systems.py
  tests/test_graphical_units/control_data/plot/plot_derivative_graph.npz
  tests/test_graphical_units/test_axes.py
Labels: new feature

#2354 Port over docs and typings from `mobject.py`/`vectorized_mobject` to their OpenGL counterparts.
  manim/mobject/mobject.py
  manim/mobject/opengl_mobject.py
  manim/mobject/shape_matchers.py
  manim/mobject/types/opengl_vectorized_mobject.py
Labels: documentation, maintenance, opengl

#2314 Added basic support for adding subcaptions via :meth:`.Scene.add_subcaption`
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  poetry.lock
  pyproject.toml
  tests/test_scene.py
Labels: new feature

#2353 Prepare new release: ``v0.13.0``
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.13.0-changelog.rst
  pyproject.toml
  scripts/dev_changelog.py
Labels: release

#2363 Fixed broken IPython magic command
  manim/cli/render/render_options.py
Labels: bugfix

#2364 Prepared bugfix release ``v0.13.1``
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.13.1-changelog.rst
  pyproject.toml
Labels: release

#2368 Added note in Internationalization
  docs/source/contributing/internationalization.rst
Labels: documentation

#2372 Improved DashedVMobject
  manim/mobject/types/vectorized_mobject.py
  tests/test_graphical_units/control_data/geometry/DashedVMobject.npz
  tests/test_graphical_units/test_geometry.py
Labels: enhancement

#2390 Removed deprecations up to `v0.13.0`
  manim/animation/growing.py
  manim/mobject/coordinate_systems.py
  manim/mobject/frame.py
  manim/mobject/number_line.py
  manim/mobject/opengl_mobject.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/code_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/three_dimensions.py
  manim/mobject/vector_field.py
Labels: deprecation

#2385 Made comments in quickstart tutorial more precise
  docs/source/tutorials/quickstart.rst
Labels: maintenance

#2399 Fix type annotations in `table.py`
  manim/mobject/table.py
Labels: maintenance, typehints

#2395 Add documentation for paths functions
  manim/animation/transform.py
  manim/mobject/mobject.py
  manim/mobject/opengl_mobject.py
  manim/mobject/value_tracker.py
  manim/utils/paths.py
Labels: enhancement

#2388 Added ``about_point`` keyword argument to :class:`~.ApplyMatrix`
  manim/animation/transform.py
  tests/test_graphical_units/control_data/transform/ApplyMatrix.npz
  tests/test_graphical_units/test_transform.py
Labels: enhancement

#2403 Improved docstring of :class:`~.ApplyMethod` and removed propagated ``__init__`` docstring
  manim/animation/transform.py
Labels: documentation

#2383 Made set_fill_by_value() support gradients on different axes.
  manim/mobject/three_dimensions.py
  tests/test_graphical_units/control_data/threed/Y_Direction.npz
  tests/test_graphical_units/test_threed.py
Labels: enhancement

#2371 Add 'dvips' to list of required LaTeX packages on Linux
  docs/source/installation/linux.rst
Labels: documentation

#2352 docs: add localized with Crowdin badge
  docs/source/_static/crowdin-badge.svg
  docs/source/index.rst
Labels: documentation, i18n

#2405 Removed unused OpenGL files
  manim/mobject/svg/opengl_tex_mobject.py
  manim/mobject/svg/opengl_text_mobject.py
Labels: maintenance

#2401 Fixed type annotations in :mod:`.mobject.three_dimensions`
  manim/mobject/three_dimensions.py
Labels: maintenance, typehints

#2410 Fixed Flake8
  .flake8
  docs/source/conf.py
  example_scenes/opengl.py
  manim/camera/moving_camera.py
  manim/cli/new/group.py
  manim/mobject/graph.py
  manim/renderer/shader.py
  manim/scene/scene.py
  manim/scene/three_d_scene.py
  manim/utils/paths.py
  manim/utils/testing/frames_comparison.py
  scripts/dev_changelog.py
  tests/test_file_ops.py
  tests/test_graphical_units/test_axes.py
Labels: maintenance
