Repository ManimCommunity/manim, pull requests merged in 2022-07, with the labels that each got.

#2749 Added :class:`.ChangeSpeed`, an animation wrapper that allows to smoothly change the speed at which an animation is played
  docs/source/reference.rst
  docs/source/reference_index/animations.rst
  manim/__init__.py
  manim/animation/animation.py
  manim/animation/composition.py
  manim/animation/speedmodifier.py
  tests/test_graphical_units/control_data/speed/SpeedModifier.npz
  tests/test_graphical_units/test_speed.py
Labels: new feature, highlight

#2841 addition(bezier.py): adding subdivide_quadratic_bezier and split_quad…
  docs/source/_static/bezier_subdivision_example.png
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/utils/bezier.py
Labels: enhancement, opengl

#2864 Updated lockfile
  poetry.lock
Labels: maintenance

#2638 Fix :meth:`BarChart.change_bar_values` not updating when height is 0.
  manim/mobject/graphing/probability.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
Labels: pr:bugfix

#2667 Made FFmpeg executable path configureable
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/constants.py
  manim/scene/scene_file_writer.py
  manim/utils/file_ops.py
Labels: new feature

#2866 Reorganize test files to match library module structure
  tests/interface/test_commands.py
  tests/miscellaneous/test_version.py
  tests/module/animation/test_animate.py
  tests/module/animation/test_composition.py
  tests/module/animation/test_override_animation.py
  tests/module/mobject/geometry/test_unit_geometry.py
  tests/module/mobject/graphing/test_axes_shift.py
  tests/module/mobject/graphing/test_coordinate_system.py
  tests/module/mobject/graphing/test_number_line.py
  tests/module/mobject/graphing/test_ticks.py
  tests/module/mobject/mobject/test_copy.py
  tests/module/mobject/mobject/test_family.py
  tests/module/mobject/mobject/test_get_set.py
  tests/module/mobject/mobject/test_mobject.py
  tests/module/mobject/mobject/test_opengl_metaclass.py
  tests/module/mobject/mobject/test_set_attr.py
  tests/module/mobject/svg/test_svg_mobject.py
  tests/module/mobject/test_boolean_ops.py
  tests/module/mobject/test_graph.py
  tests/module/mobject/test_value_tracker.py
  tests/module/mobject/text/test_markup.py
  tests/module/mobject/text/test_numbers.py
  tests/module/mobject/text/test_texmobject.py
  tests/module/mobject/text/test_text_mobject.py
  tests/module/mobject/types/vectorized_mobject/test_stroke.py
  tests/module/mobject/types/vectorized_mobject/test_vectorized_mobject.py
  tests/module/scene/test_auto_zoom.py
  tests/module/scene/test_scene.py
  tests/module/scene/test_sound.py
  tests/module/scene/test_threed_scene.py
  tests/module/utils/test_color.py
  tests/module/utils/test_deprecation.py
  tests/module/utils/test_file_ops.py
  tests/module/utils/test_hashing.py
  tests/module/utils/test_space_ops.py
  tests/module/utils/test_units.py
Labels: enhancement, infrastructure, refactor, maintenance

#2861 Added docstring for :meth:`.CoordinateSystem.plot_parametric_curve`
  manim/mobject/graphing/coordinate_systems.py
Labels: documentation

#2288 Added warning when attempting to add same mobject as child twice
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: enhancement

#2842 Moved functionality over from `manim new` to `manim init` and added deprecation warning for `manim new`
  manim/cli/init/commands.py
  manim/cli/new/group.py
  tests/interface/test_commands.py
Labels: enhancement

#2849 Added example for ``path_arc`` keyword argument of :class:`.Transform`
  manim/animation/transform.py
Labels: documentation

#2714 OpenGLVMobject fix pointwise_become_partial to fix stroke rendering
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/utils/bezier.py
Labels: enhancement, pr:dependent, issue:bug, opengl

#2550 New thematic guide: a deep dive into the internals of the library
  .pre-commit-config.yaml
  docs/source/guides/deep_dive.rst
  manim/renderer/cairo_renderer.py
  manim/utils/docbuild/manim_directive.py
  poetry.lock
  pyproject.toml
Labels: documentation

#2870 Fixed issue with ``manim init scene SCENE_NAME filename.py`` and removed necessity of ``main.py`` to be present in working directory
  manim/cli/init/commands.py
  tests/interface/test_commands.py
Labels: pr:bugfix

#2567 Use tempconfig for every scene render
  manim/cli/render/commands.py
  tests/test_scene_rendering/infallible_scenes.py
  tests/test_scene_rendering/opengl/test_cli_flags_opengl.py
  tests/test_scene_rendering/test_cli_flags.py
Labels: pr:bugfix

#2186 Enabled filling color by value for :class:`.OpenGLSurface`, replaced ``colors`` keyword argument of :meth:`.Surface.set_fill_by_value` with ``colorscale``
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/opengl/opengl_surface.py
  manim/mobject/three_d/three_dimensions.py
  tests/test_graphical_units/control_data/coordinate_system/plot_surface.npz
  tests/test_graphical_units/control_data/coordinate_system/plot_surface_colorscale.npz
  tests/test_graphical_units/test_coordinate_systems.py
  tests/test_graphical_units/test_threed.py
Labels: enhancement

#2877 Fixed binder launch problem by adding missing optional ``notebook`` dependency
  poetry.lock
  pyproject.toml
Labels: maintenance

#2887 Removed empty i18n files that caused filename clashes
  docs/i18n/gettext/reference/manim.mobject.geometry.Arc.pot
  docs/i18n/gettext/reference/manim.mobject.geometry.Line.pot
  docs/i18n/gettext/reference/manim.mobject.geometry.Polygram.pot
Labels: maintenance, i18n

#2886 Added docstring to and fixed type hint of :func:`.get_winding_number`
  manim/utils/space_ops.py
Labels: documentation

#2892 Corrected error in the ``PolygonOnAxes`` example
  docs/source/examples.rst
Labels: documentation

#2893 Improved performance of ``test_threed.py``
  pyproject.toml
  tests/test_graphical_units/control_data/threed/Arrow3D.npz
  tests/test_graphical_units/control_data/threed/Cone.npz
  tests/test_graphical_units/control_data/threed/Line3D.npz
  tests/test_graphical_units/control_data/threed/SurfaceColorscale.npz
  tests/test_graphical_units/control_data/threed/Y_Direction.npz
  tests/test_graphical_units/test_threed.py
Labels: testing, performance

#2888 Fixed bug with propagation of ``tex_template`` value when using ``tempconfig``
  manim/_config/utils.py
  manim/cli/render/commands.py
  manim/utils/tex.py
  tests/module/mobject/text/test_texmobject.py
  tests/opengl/test_texmobject_opengl.py
Labels: pr:bugfix

#2903 Fixed minor grammar issues in :doc:`/faq/general`
  docs/source/faq/general.md
Labels: documentation
