Repository ManimCommunity/manim, pull requests merged in 2022-12, with the labels that each got.

#3053 Frame comparison pixel threshold
  manim/utils/testing/_frames_testers.py
  tests/test_graphical_units/control_data/utils/pixel_error_threshold.npz
  tests/test_graphical_units/test_utils.py
Labels: testing

#3049 Added thematic guide for the ``manim-voiceover`` plugin
  docs/source/guides/add_voiceovers.rst
  docs/source/guides/index.rst
Labels: documentation, highlight

#3030 Added support for Python 3.11, dropped support for Python 3.7
  .github/workflows/ci.yml
  manim/renderer/shader.py
  poetry.lock
  pyproject.toml
Labels: breaking changes, maintenance

#3023 Prepared new release: v0.17.0
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.17.0-changelog.rst
  pyproject.toml
Labels: release

#3061 Always use ``/`` when calling LaTeX
  manim/utils/tex_file_writing.py
  tests/module/mobject/text/test_texmobject.py
Labels: pr:bugfix

#3064 Increased minimal required version of ``svgelements``
  poetry.lock
  pyproject.toml
Labels: maintenance

#3066 Increased minimal version of ``pytest``
  poetry.lock
  pyproject.toml
  tests/test_scene_rendering/opengl/test_opengl_renderer.py
Labels: maintenance

#3065 Prepared new release: ``v0.17.1``
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.17.1-changelog.rst
  pyproject.toml
Labels: release

#3074 Fix typo: "turn into into an np array" to "turn into a np array"
  manim/mobject/graphing/number_line.py
Labels: documentation, maintenance

#3073 Fix typo: "Whetherer" to "Whether"
  manim/mobject/graphing/scale.py
Labels: documentation, maintenance

#3079 Updating ci syntax for runner version >=2.298.2
  .github/workflows/ci.yml
Labels: maintenance

#3084 Codeql
  .github/codeql.yml
  .github/workflows/codeql.yml
  manim/mobject/graph.py
  manim/mobject/text/text_mobject.py
  manim/mobject/three_d/three_dimensions.py
Labels: maintenance

#3090 Prepared new Hotfix Release: `v0.17.2`
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.17.2-changelog.rst
  manim/mobject/graphing/number_line.py
  pyproject.toml
Labels: release

#3092 perf: improve Mobject.add by checking for redundancy only once
  manim/mobject/mobject.py
Labels: enhancement, performance

#3083 Minor performance improvement in bezier.py with preallocating array.
  manim/mobject/opengl/opengl_mobject.py
  manim/utils/bezier.py
  poetry.lock
Labels: performance
