Repository ManimCommunity/manim, pull requests merged in 2022-10, with the labels that each got.

#2975 Fixed broken links in README
  README.md
Labels: maintenance

#2977 Fix: Allow rendering of empty text strings
  manim/animation/creation.py
Labels: pr:bugfix

#2981 Implemented fallback save behavior for `pytest --show_diff`
  manim/utils/testing/_frames_testers.py
  manim/utils/testing/_show_diff.py
Labels: testing, easy

#2983 Debugging Windows CI Pipeline
  .github/workflows/ci.yml
  conftest.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  poetry.lock
Labels: maintenance

#2919 Corrected parameters and enhanced the description of :meth:`.ImageMobject.interpolate_color`
  manim/mobject/types/image_mobject.py
Labels: documentation

#2994 Fixed segmentation faults from doctests under Python 3.10
  .github/workflows/ci.yml
  conftest.py
Labels: maintenance

#3001 Added FAQ entry regarding failed ``manimpango`` build
  docs/source/faq/installation.md
Labels: documentation, pr:easy review

#2982 Rewrote unstable tests for :mod:`.text_mobject` to be non-graphical
  tests/test_graphical_units/control_data/text/Text2Color.npz
  tests/test_graphical_units/control_data/text/text_color_inheritance.npz
  tests/test_graphical_units/test_text.py
Labels: testing, pr:easy review

#3004 Fixed docbuild warnings
  docs/source/installation/windows.rst
Labels: documentation, maintenance

#2978 Added documentation and example for :class:`.CyclicReplace`
  manim/animation/transform.py
Labels: documentation

#3003 Fixed setting ``run_time`` of :class:`.Succession` after creating the animation object
  manim/animation/composition.py
  tests/module/animation/test_composition.py
Labels: pr:bugfix

#2980 Migrate more `os.path` to `pathlib`
  manim/_config/utils.py
  manim/cli/cfg/group.py
  manim/cli/init/commands.py
  manim/cli/new/group.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/text/code_mobject.py
  manim/renderer/shader.py
  manim/renderer/shader_wrapper.py
  manim/scene/scene_file_writer.py
  manim/scene/section.py
  manim/utils/docbuild/manim_directive.py
  manim/utils/file_ops.py
  manim/utils/images.py
  manim/utils/ipython_magic.py
  manim/utils/module_ops.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
  scripts/dev_changelog.py
  scripts/extract_frames.py
  tests/test_scene_rendering/opengl/test_cli_flags_opengl.py
  tests/test_scene_rendering/test_cli_flags.py
Labels: maintenance
