Repository ManimCommunity/manim, pull requests merged in 2022-02, with the labels that each got.

#2516 Cache view matrix for :class:`~.OpenGLCamera`
  example_scenes/opengl.py
  manim/renderer/opengl_renderer.py
  manim/renderer/shader.py
  manim/renderer/vectorized_mobject_rendering.py
  poetry.lock
  pyproject.toml
Labels: enhancement, performance

#2524 Reworked `space_ops.py`
  manim/utils/space_ops.py
  tests/test_graphical_units/control_data/threed/AmbientCameraMove.npz
  tests/test_graphical_units/control_data/threed/CameraMove.npz
  tests/test_graphical_units/control_data/threed/Cone.npz
  tests/test_graphical_units/control_data/threed/Cube.npz
  tests/test_graphical_units/control_data/threed/Line3D.npz
  tests/test_graphical_units/control_data/threed/Sphere.npz
  tests/test_graphical_units/test_threed.py
  tests/test_space_ops.py
Labels: maintenance, performance

#2530 Use single source of truth for default text values
  manim/mobject/svg/text_mobject.py
Labels: bugfix

#2535 A faster method to compute split_factors
  manim/mobject/types/vectorized_mobject.py
Labels: enhancement, performance

#2536 Upgraded version of setup-ffmpeg CI action
  .github/workflows/ci.yml
Labels: maintenance

#2487 Fixed :meth:`.ThreeDCamera.remove_fixed_orientation_mobjects`
  manim/camera/three_d_camera.py
  tests/test_threed_scene.py
Labels: bugfix

#2504 Added finer control over :meth:`.Scene.wait` being static (i.e., no updaters) or not
  manim/animation/animation.py
  manim/mobject/opengl_mobject.py
  manim/renderer/opengl_renderer.py
  manim/scene/scene.py
  tests/test_scene_rendering/opengl/test_play_logic_opengl.py
  tests/test_scene_rendering/simple_scenes.py
  tests/test_scene_rendering/test_play_logic.py
Labels: new feature

#2528 Fixed custom naming of gifs and added some tests
  manim/scene/scene_file_writer.py
  poetry.lock
  tests/test_scene_rendering/test_cli_flags.py
Labels: bugfix

#2538 Fixed flickering OpenGL preview when using ``frozen_frame``
  manim/renderer/opengl_renderer.py
Labels: bugfix

#2158 Added OpenGL compatibility to `ThreeDScene.add_fixed_orientation_mobjects` and `ThreeDScene.add_fixed_in_frame_mobjects`
  manim/mobject/opengl_mobject.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/renderer/shaders/include/camera_uniform_declarations.glsl
  manim/renderer/shaders/include/get_gl_Position.glsl
  manim/renderer/shaders/include/position_point_into_frame.glsl
  manim/renderer/shaders/quadratic_bezier_fill/geom.glsl
  manim/renderer/shaders/quadratic_bezier_stroke/geom.glsl
  manim/renderer/shaders/true_dot/geom.glsl
  manim/scene/three_d_scene.py
  tests/test_graphical_units/control_data/opengl/FixedMobjects3D.npz
  tests/test_graphical_units/test_opengl.py
  tests/test_graphical_units/test_threed.py
Labels: enhancement, opengl

#2531 Added a GitHub Action for automatic validation of your citation metadata
  .github/workflows/cffconvert.yml
  CITATION.cff
Labels: infrastructure

#2526 Fix segfault when using `--enable_gui`
  manim/gui/gui.py
  poetry.lock
  pyproject.toml
Labels: bugfix

#1547 Fixed certain unicode characters in users' paths causing issues on Windows
  manim/scene/scene_file_writer.py
  tests/test_scene_rendering/test_file_writer.py
Labels: bugfix

#2548 Fix axes plotting bug with logarithmic x-axis
  manim/mobject/functions.py
  tests/test_graphical_units/control_data/coordinate_system/plot_log_x_axis.npz
  tests/test_graphical_units/test_coordinate_systems.py
Labels: bugfix

#2458 Improved documentation for `Rotate`
  manim/animation/rotation.py
Labels: documentation

#2556 Show highlights when creating table
  manim/mobject/table.py
Labels: bugfix

#2549 Added a page for internals which links to our Github wiki
  docs/source/index.rst
  docs/source/internals.rst
Labels: documentation

#2537 Added support for PySide coordinate system
  manim/renderer/opengl_renderer.py
  tests/test_scene_rendering/opengl/test_opengl_renderer.py
Labels: enhancement

#2467 :class:`~.MathTex`, :class:`~.Tex`, :class:`~.Text` and :class:`~.MarkupText` inherit color from their parent mobjects.
  manim/mobject/coordinate_systems.py
  manim/mobject/number_line.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/tex_mobject.py
  manim/mobject/svg/text_mobject.py
  tests/test_graphical_units/control_data/tex_mobject/color_inheritance.npz
  tests/test_graphical_units/control_data/text/text_color_inheritance.npz
  tests/test_graphical_units/test_tex_mobject.py
  tests/test_graphical_units/test_text.py
  tests/test_texmobject.py
  tests/test_text_mobject.py
Labels: enhancement

#2566 Removed unused livestream-related imports and functions from :mod:`.scene_file_writer`
  manim/scene/scene_file_writer.py
Labels: maintenance

#2568 Remove Deprecated Methods
  manim/mobject/three_dimensions.py
  manim/mobject/types/vectorized_mobject.py
Labels: deprecation

#2565 Allowed passing vertex configuration keyword arguments to :meth:`.Graph.add_edges`
  manim/mobject/graph.py
Labels: enhancement

#2569 Refactored docstrings in mod:`manim.mobject.geometry`
  manim/mobject/geometry/polygram.py
  manim/mobject/geometry/shape_matchers.py
  manim/mobject/geometry/tips.py
Labels: documentation

#2571 Refactored docstrings in :mod:`.graphing`
  manim/mobject/graphing/functions.py
  manim/mobject/graphing/number_line.py
  manim/mobject/graphing/probability.py
  manim/mobject/graphing/scale.py
Labels: documentation

#2478 Alternative scaling for tree graph layout
  manim/mobject/graph.py
Labels: enhancement

#2573 Moved :mod:`.value_tracker` back inside :mod:`.mobject`
  docs/source/reference.rst
  manim/__init__.py
  manim/animation/updaters/__init__.py
  manim/camera/three_d_camera.py
  manim/grpc/impl/frame_server_impl.py
  manim/mobject/text/numbers.py
  manim/mobject/value_tracker.py
  manim/scene/three_d_scene.py
  tests/opengl/test_value_tracker_opengl.py
  tests/test_value_tracker.py
Labels: maintenance

#2560 Refactored more docstrings in :mod:`.geometry`
  docs/source/conf.py
  manim/mobject/geometry/arc.py
  manim/mobject/geometry/boolean_ops.py
  manim/mobject/geometry/line.py
Labels: documentation, maintenance

#2576 Fixed a bug with animation of removal of edges from a :class:`.Graph`
  manim/mobject/graph.py
Labels: bugfix

#2580 Fix `find_intersection` in `space_ops.py`
  manim/utils/space_ops.py
Labels: bugfix

#2574 Improved Error in :mod:`.utils.tex_file_writing`
  manim/utils/tex_file_writing.py
  tests/control_data/logs_data/bad_tex_scene_BadTex.txt
  tests/test_logging/bad_tex_scene.py
  tests/test_logging/test_logging.py
Labels: bugfix
