Repository ManimCommunity/manim, pull requests merged in 2022-01, with the labels that each got.

#1972 Added MyPy Support
  .mypy.ini
  .pre-commit-config.yaml
  docs/source/conf.py
  example_scenes/opengl.py
  manim/__init__.py
  manim/_config/__init__.py
  manim/cli/render/commands.py
  manim/cli/render/render_options.py
  manim/plugins/import_plugins.py
  manim/renderer/cairo_renderer.py
  manim/renderer/shader.py
  manim/renderer/shader_wrapper.py
  manim/utils/docbuild/manim_directive.py
  poetry.lock
  pyproject.toml
  scripts/simple_cors_http_server.py
  tests/test_scene_rendering/opengl/test_opengl_renderer.py
  tests/utils/GraphicalUnitTester.py
Labels: maintenance

#2423 Changed recommendatiom to ``mactex-no-gui`` from ``mactex`` for macOS install
  docs/source/installation/macos.rst
Labels: documentation

#2414 Made improvements to the :doc:`configuration` tutorial
  docs/rtd-requirements.txt
  docs/source/conf.py
  docs/source/tutorials/configuration.rst
  poetry.lock
  pyproject.toml
Labels: documentation, infrastructure

#2424 Remove `strings.py`
  manim/__init__.py
  manim/utils/strings.py
Labels: maintenance

#2408 Removed various return annotations that were stifling type inference
  manim/mobject/mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: maintenance, typehints

#2415 Removed instructions on using and installing Docker on README
  README.md
Labels: documentation

#2436 Fixed typo and improved example in building blocks tutorial
  docs/source/tutorials/building_blocks.rst
Labels: documentation

#2444 Fix `add_axes` in :class:`~.VectorScene`.
  manim/scene/vector_space_scene.py
Labels: bugfix

#2437 Cleanup `simple_functions.py`
  manim/camera/camera.py
  manim/mobject/number_line.py
  manim/mobject/opengl_geometry.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/zoomed_scene.py
  manim/utils/color.py
  manim/utils/simple_functions.py
Labels: maintenance

#2376 Update Dependencies for Python3.10
  .github/workflows/ci.yml
  docs/source/installation/linux.rst
  docs/source/installation/windows.rst
  poetry.lock
  pyproject.toml
Labels: maintenance

#2387 Refactored :class:`~.BarChart` and made it inherit from :class:`~.Axes`.
  manim/mobject/coordinate_systems.py
  manim/mobject/number_line.py
  manim/mobject/probability.py
  tests/test_graphical_units/control_data/probability/advanced_customization.npz
  tests/test_graphical_units/control_data/probability/change_bar_values_negative.npz
  tests/test_graphical_units/control_data/probability/change_bar_values_some_vals.npz
  tests/test_graphical_units/control_data/probability/default_chart.npz
  tests/test_graphical_units/control_data/probability/get_bar_labels.npz
  tests/test_graphical_units/control_data/probability/label_constructor.npz
  tests/test_graphical_units/control_data/probability/negative_values.npz
  tests/test_graphical_units/test_probability.py
Labels: enhancement, new feature, breaking changes

#2396 Fixed animations introducing or removing objects
  manim/animation/animation.py
  manim/animation/composition.py
  manim/animation/creation.py
  manim/animation/fading.py
  manim/animation/growing.py
  manim/animation/indication.py
  manim/mobject/graph.py
  manim/scene/scene.py
  manim/utils/testing/_frames_testers.py
  tests/opengl/test_composition_opengl.py
  tests/test_composition.py
  tests/test_graphical_units/control_data/vector_scene/vector_to_coords.npz
Labels: enhancement

#2482 Updated Python version requirement in installation guide
  docs/source/installation.rst
Labels: documentation, easy review

#2357 Fixed screeninfo.get_monitors returning empty on osx
  poetry.lock
  pyproject.toml
Labels: bugfix

#2490 Fixed two issues of :class:`~.SVGMobject`
  manim/mobject/svg/svg_mobject.py
  tests/test_graphical_units/control_data/img_and_svg/MultipleTransform.npz
Labels: bugfix, SVG

#2493 Fixed typo in documentation for parameters of :class:`.Square`
  manim/mobject/geometry.py
Labels: documentation

#2494 Fixed `.gif` related issues
  manim/scene/scene_file_writer.py
  manim/utils/file_ops.py
Labels: bugfix

#2332 Change `color`, `stroke_color` and `fill_color` fields to properties
  manim/mobject/geometry.py
  manim/mobject/mobject.py
  manim/mobject/opengl_mobject.py
  manim/mobject/shape_matchers.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/text_mobject.py
  manim/mobject/types/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/utils/color.py
  manim/utils/config_ops.py
  tests/opengl/test_color_opengl.py
  tests/test_stroke.py
  tests/test_svg_mobject.py
Labels: bugfix

#2508 Improve performance for :meth:`~become`
  manim/mobject/mobject.py
  tests/test_vectorized_mobject.py
Labels: performance

#2431 Changed example in Surface.set_fill_by_value()
  manim/mobject/three_dimensions.py
Labels: documentation

#2465 Added documentation for `index_labels`.
  docs/source/reference_index/utilities_misc.rst
  docs/source/tutorials/using_text.rst
  manim/utils/debug.py
Labels: documentation

#2457 Deprecated 'ShowCreationThenFadeOut'
  manim/animation/indication.py
Labels: deprecation

#2519 Removed unnecessary/outdated comment
  manim/animation/indication.py
Labels: maintenance
