Repository ManimCommunity/manim, pull requests merged in 2022-05, with the labels that each got.

#2703 Default to utf-8 when reading files in :class:`.Code`
  manim/mobject/text/code_mobject.py
Labels: bugfix

#2715 fix(constants.py,image_mobject.py,opengl_image_mobject.py): Update de…
  manim/constants.py
  manim/mobject/opengl/opengl_image_mobject.py
  manim/mobject/types/image_mobject.py
Labels: enhancement

#2720 docs: Fixed typo in docstring
  manim/mobject/geometry/line.py
Labels: documentation, enhancement

#2727 Slight performance improvement for :class:`.ArrowVectorField` and Bezier curve computation
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/utils/bezier.py
  manim/utils/iterables.py
Labels: performance

#2726 Edited note on :class:`.NumberPlane` length and added another example
  manim/mobject/graphing/coordinate_systems.py
Labels: documentation

#2725 Fix Code mobject wrong indentation
  manim/mobject/text/code_mobject.py
  tests/test_code_mobject.py
Labels: bugfix

#2734 Fix OpenGL segfaulting when running self.play or self.wait
  manim/scene/scene.py
Labels: bugfix

#2732 Refactored structure of documentation; added :doc:`FAQ section <faq/index>`
  .github/workflows/ci.yml
  docs/i18n/readyForTranslation
  docs/requirements.txt
  docs/source/changelog/0.14.0-changelog.rst
  docs/source/conf.py
  docs/source/contributing/development.rst
  docs/source/faq/general.md
  docs/source/faq/help.md
  docs/source/faq/index.rst
  docs/source/faq/installation.md
  docs/source/faq/internals.md
  docs/source/guides/configuration.rst
  docs/source/guides/index.rst
  docs/source/guides/using_text.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/installation/troubleshooting.rst
  docs/source/installation/versions.rst
  docs/source/reference.rst
  docs/source/reference_index/utilities_misc.rst
  docs/source/reporting_bugs.rst
  docs/source/tutorials.rst
  docs/source/tutorials/building_blocks.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/output_and_config.rst
  docs/source/tutorials/quickstart.rst
  docs/source/tutorials_guides.rst
  manim/_config/utils.py
  manim/animation/movement.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/probability.py
  manim/scene/scene.py
  manim/scene/section.py
  manim/utils/deprecation.py
  manim/utils/docbuild/manim_directive.py
  poetry.lock
  pyproject.toml
  tests/test_deprecation.py
Labels: documentation

#2740 Fixed documentation of :meth:`.Cylinder.get_direction`
  manim/mobject/three_d/three_dimensions.py
Labels: documentation

#2730 Added note to let users find documentation of default CLI subcommand easier
  manim/__main__.py
Labels: enhancement

#2728 enhancement(vector_field): added fit_to_coordinate_system
  manim/mobject/vector_field.py
Labels: enhancement
