Repository ManimCommunity/manim, pull requests merged in 2022-09, with the labels that each got.

#2954 Fixed click version string in ``pyproject.toml``
  poetry.lock
  pyproject.toml
Labels: maintenance, easy

#2895 Fixed broken :class:`.ShowPassingFlashWithThinningStrokeWidth`
  manim/animation/indication.py
Labels: pr:bugfix

#2885 Always expand user when validating file-paths
  manim/mobject/svg/svg_mobject.py
  manim/mobject/text/code_mobject.py
  manim/utils/file_ops.py
Labels: pr:bugfix

#2925 CI (test-arm): update python version to `3.10.6`
  .github/workflows/ci.yml
Labels: infrastructure

#2936 Added installation instructions for Windows via ``winget``
  docs/source/installation/windows.rst
Labels: documentation

#2846 Prevent TransformMatchingTex from crashing when there is nothing to fade
  manim/animation/transform.py
  tests/test_graphical_units/control_data/transform/FadeTransform.npz
  tests/test_graphical_units/control_data/transform/FadeTransformPieces.npz
  tests/test_graphical_units/control_data/transform/FadeTransform_TargetIsEmpty_FadesOutInPlace.npz
  tests/test_graphical_units/control_data/transform_matching_parts/TransformMatchingTex.npz
  tests/test_graphical_units/control_data/transform_matching_parts/TransformMatchingTex_FadeTransformMismatches.npz
  tests/test_graphical_units/control_data/transform_matching_parts/TransformMatchingTex_FadeTransformMismatches_NothingToFade.npz
  tests/test_graphical_units/control_data/transform_matching_parts/TransformMatchingTex_TransformMismatches.npz
  tests/test_graphical_units/test_transform.py
  tests/test_graphical_units/test_transform_matching_parts.py
Labels: pr:bugfix

#2963 CI (test-arm): Always select the correct python version
  .github/workflows/ci.yml
Labels: infrastructure

#2962 Disabled "Edit on GitHub" button in documentation
  docs/source/conf.py
Labels: documentation, easy

#2883 Add animation RemoveTextLetterByLetter
  manim/animation/creation.py
Labels: new feature

#2898 Ported improved implementation of :class:`.SVGMobject` from 3b1b/manim
  docs/requirements.txt
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_point_cloud_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/svg/__init__.py
  manim/mobject/svg/brace.py
  manim/mobject/svg/style_utils.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/svg/svg_path.py
  manim/mobject/text/numbers.py
  manim/mobject/text/tex_mobject.py
  manim/mobject/text/text_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/utils/images.py
  manim/utils/iterables.py
  poetry.lock
  pyproject.toml
  tests/module/mobject/svg/test_svg_mobject.py
  tests/test_graphical_units/control_data/img_and_svg/Arcs01.npz
  tests/test_graphical_units/control_data/img_and_svg/Arcs02.npz
  tests/test_graphical_units/control_data/img_and_svg/ContiguousUSMap.npz
  tests/test_graphical_units/control_data/img_and_svg/DesmosGraph1.npz
  tests/test_graphical_units/control_data/img_and_svg/HalfEllipse.npz
  tests/test_graphical_units/control_data/img_and_svg/Heart.npz
  tests/test_graphical_units/control_data/img_and_svg/Line.npz
  tests/test_graphical_units/control_data/img_and_svg/ManimLogo.npz
  tests/test_graphical_units/control_data/img_and_svg/MultipleTransform.npz
  tests/test_graphical_units/control_data/img_and_svg/Penrose.npz
  tests/test_graphical_units/control_data/img_and_svg/PixelizedText.npz
  tests/test_graphical_units/control_data/img_and_svg/Rhomboid.npz
  tests/test_graphical_units/control_data/img_and_svg/RotateTransform.npz
  tests/test_graphical_units/control_data/img_and_svg/SkewXTransform.npz
  tests/test_graphical_units/control_data/img_and_svg/SkewYTransform.npz
  tests/test_graphical_units/control_data/img_and_svg/SmoothCurves.npz
  tests/test_graphical_units/control_data/img_and_svg/WeightSVG.npz
  tests/test_graphical_units/control_data/vector_scene/vector_to_coords.npz
  tests/test_graphical_units/img_svg_resources/curve.svg
  tests/test_graphical_units/img_svg_resources/half_ellipse.svg
  tests/test_graphical_units/img_svg_resources/states_map.svg
Labels: enhancement, breaking changes, maintenance
