Repository ManimCommunity/manim, pull requests merged in 2022-04, with the labels that each got.

#2609 Copy Edit troubleshooting.rst
  docs/source/installation/troubleshooting.rst
Labels: documentation

#2656 Fixed incompatibility with black version
  .pre-commit-config.yaml
  manim/mobject/graphing/coordinate_systems.py
Labels: infrastructure, maintenance

#2642 Migrated file_ops.py and scene_file_writer.py from os.path to Pathlib
  manim/scene/scene_file_writer.py
  manim/utils/file_ops.py
  tests/test_file_ops.py
Labels: enhancement

#2651 Update copyright year in documentation to 2020-2022
  docs/source/conf.py
Labels: documentation

#2663 Added documentation for scene updater functions
  manim/scene/scene.py
Labels: documentation

#2655 Fix `assert_is_mobject_method` when using OpenGL
  manim/animation/updaters/mobject_update_utils.py
Labels: enhancement

#2668 (Re)set background color of :class:`.OpenGLRenderer` when initializing scene
  manim/renderer/opengl_renderer.py
Labels: bugfix, opengl

#2665 Improved handling of attributes when using the ``.animate`` syntax
  manim/animation/transform.py
  manim/mobject/mobject.py
  tests/test_scene_rendering/test_play_logic.py
Labels: enhancement

#2640 Copyedited Documentation
  docs/source/tutorials/configuration.rst
Labels: documentation

#2676 Fixed opengl finish transform
  manim/mobject/opengl/opengl_mobject.py
  tests/test_scene_rendering/opengl/test_play_logic_opengl.py
Labels: bugfix, opengl

#2658 Fix arguments of overridden `set_style` for `BackgroundRectangle`
  manim/mobject/geometry/shape_matchers.py
  tests/test_unit_geometry.py
Labels: bugfix

#2648 Handle user-defined centers for Wiggle animation
  manim/animation/indication.py
  tests/test_graphical_units/test_indication.py
Labels: bugfix

#2678 Require `backports-cached-property` only for Python < 3.8
  poetry.lock
  pyproject.toml
Labels: maintenance

#2693 Allow using :meth:`.MovingCamera.auto_zoom` without animation
  manim/camera/moving_camera.py
  tests/test_camera.py
Labels: enhancement

#2684 Created a more accessible way to create Angles with line.py angle function - Angle.from_three_points
  manim/mobject/geometry/line.py
  tests/test_graphical_units/control_data/geometry/three_points_Angle.npz
  tests/test_graphical_units/test_geometry.py
Labels: new feature

#2688 Fixed two minor issues of :class:`.SpiralIn` and :class:`.ManimBanner`
  manim/animation/creation.py
  manim/mobject/logo.py
Labels: bugfix

#2534 Implement `OpenGLImageMobject`
  manim/mobject/opengl/opengl_image_mobject.py
  manim/mobject/opengl/opengl_surface.py
  manim/mobject/types/image_mobject.py
  manim/opengl/__init__.py
  manim/renderer/opengl_renderer.py
  manim/utils/images.py
Labels: new feature, opengl

#2691 Removed :class:`CameraFrame`
  manim/camera/moving_camera.py
Labels: maintenance

#2697 devchangelog: Sort items before writing
  scripts/dev_changelog.py
Labels: maintenance

#1975 Improved CLI help page styling
  docs/source/tutorials/configuration.rst
  manim/__main__.py
  manim/_config/__init__.py
  manim/_config/cli_colors.py
  manim/_config/default.cfg
  manim/cli/cfg/group.py
  manim/cli/default_group.py
  manim/cli/init/commands.py
  manim/cli/new/group.py
  manim/cli/plugins/commands.py
  manim/cli/render/commands.py
  manim/constants.py
  poetry.lock
  pyproject.toml
  scripts/dev_changelog.py
  tests/test_commands.py
Labels: enhancement

#2694 Prepared bugfix release v0.15.2
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.15.2-changelog.rst
  pyproject.toml
Labels: release
