Repository ManimCommunity/manim, pull requests merged in 2022-06, with the labels that each got.

#2751 Fixed flake C417 and improved a comment
  manim/utils/ipython_magic.py
  manim/utils/testing/frames_comparison.py
Labels: maintenance

#2753 Fixed multiplatform builds for docker images in pipeline
  .github/workflows/publish-docker.yml
  .github/workflows/publish.yml
Labels: maintenance

#2743 Replace assert with np.testing assertions
  tests/opengl/test_axes_shift_opengl.py
  tests/opengl/test_color_opengl.py
  tests/opengl/test_config_opengl.py
  tests/opengl/test_coordinate_system_opengl.py
  tests/opengl/test_family_opengl.py
  tests/opengl/test_opengl_vectorized_mobject.py
  tests/opengl/test_unit_geometry_opengl.py
  tests/test_axes_shift.py
  tests/test_boolean_ops.py
  tests/test_color.py
  tests/test_config.py
  tests/test_coordinate_system.py
  tests/test_family.py
  tests/test_set_attr.py
  tests/test_space_ops.py
  tests/test_unit_geometry.py
  tests/test_units.py
  tests/test_vectorized_mobject.py
Labels: testing, maintenance

#2746 Installed ghostscript in the docker image
  docker/Dockerfile
Labels: enhancement, maintenance

#2757 Added missing ``__init__.py`` file in `docbuild` module
  manim/utils/docbuild/__init__.py
Labels: bugfix, documentation

#2760 Remove cmake from the macos installation section
  docs/source/installation/macos.rst
Labels: documentation

#2767 Added more questions and answers to FAQ section, new OpenGL FAQ
  docs/source/faq/general.md
  docs/source/faq/opengl.md
Labels: documentation

#2828 Removed suggestion issue template, added FAQ answer regarding proposing new features
  .github/ISSUE_TEMPLATE/suggestion.md
  docs/source/contributing.rst
  docs/source/faq/help.md
Labels: documentation

#2770 Fixed bug in :meth:`.VMobject.proportion_from_point` that caused proportions greater than 1 to be returned
  manim/utils/bezier.py
  tests/test_vectorized_mobject.py
Labels: pr:bugfix

#2826 Fix TransformMatchingAbstractBase Mobject leaks
  manim/animation/transform_matching_parts.py
  tests/test_graphical_units/control_data/transform_matching_parts/TransformMatchingDisplaysCorrect.npz
  tests/test_graphical_units/control_data/transform_matching_parts/TransformMatchingLeavesOneObject.npz
  tests/test_graphical_units/test_transform_matching_parts.py
Labels: pr:bugfix

#2739 Add vectorized plotting functionality to improve performance
  manim/_config/utils.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/functions.py
  manim/mobject/graphing/number_line.py
  manim/mobject/graphing/scale.py
  manim/mobject/types/vectorized_mobject.py
  manim/utils/space_ops.py
  manim/utils/testing/frames_comparison.py
  tests/test_coordinate_system.py
  tests/test_graphical_units/conftest.py
  tests/test_graphical_units/control_data/coordinate_system/plot_log_x_axis_vectorized.npz
  tests/test_graphical_units/control_data/plot/get_riemann_rectangles_use_vectorized[False].npz
  tests/test_graphical_units/control_data/plot/get_riemann_rectangles_use_vectorized[True].npz
  tests/test_graphical_units/control_data/plot/plot_derivative_graph_use_vectorized[False].npz
  tests/test_graphical_units/control_data/plot/plot_derivative_graph_use_vectorized[True].npz
  tests/test_graphical_units/control_data/plot/plot_functions_use_vectorized[False].npz
  tests/test_graphical_units/control_data/plot/plot_functions_use_vectorized[True].npz
  tests/test_graphical_units/control_data/plot/plot_use_vectorized[False].npz
  tests/test_graphical_units/control_data/plot/plot_use_vectorized[True].npz
  tests/test_graphical_units/test_axes.py
  tests/test_graphical_units/test_coordinate_systems.py
  tests/test_number_line.py
  tests/test_space_ops.py
Labels: enhancement, performance

#2687 Migrate from os.path to pathlib in SVGMobject and other locations
  manim/cli/cfg/group.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/text/text_mobject.py
  manim/utils/tex_file_writing.py
Labels: refactor
