Repository ManimCommunity/manim, pull requests merged in 2022-11, with the labels that each got.

#2992 Fixed ``CLI.tex_template_file`` config file setting
  manim/_config/utils.py
  tests/test_config.py
Labels: pr:bugfix

#2920 fix: Align lines correctly when passing `faded_line_ratio` property to NumberPlane (#2894)
  manim/mobject/graphing/coordinate_systems.py
  tests/test_graphical_units/control_data/coordinate_system/number_plane_log.npz
Labels: pr:bugfix

#3014 Enable code completion on Mobject.animate in supporting IDEs
  manim/mobject/mobject.py
Labels: enhancement

#2988 Convert all types of parameters in docstrings to proper type annotations
  manim/_config/__init__.py
  manim/_config/logger_utils.py
  manim/_config/utils.py
  manim/animation/animation.py
  manim/animation/creation.py
  manim/animation/indication.py
  manim/camera/camera.py
  manim/camera/moving_camera.py
  manim/camera/multi_camera.py
  manim/camera/three_d_camera.py
  manim/cli/cfg/group.py
  manim/cli/init/commands.py
  manim/cli/new/group.py
  manim/mobject/geometry/line.py
  manim/mobject/geometry/polygram.py
  manim/mobject/geometry/shape_matchers.py
  manim/mobject/graphing/number_line.py
  manim/mobject/graphing/scale.py
  manim/mobject/matrix.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/svg/brace.py
  manim/mobject/table.py
  manim/mobject/text/code_mobject.py
  manim/mobject/text/numbers.py
  manim/mobject/three_d/three_dimensions.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/renderer/cairo_renderer.py
  manim/scene/moving_camera_scene.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/three_d_scene.py
  manim/scene/vector_space_scene.py
  manim/scene/zoomed_scene.py
  manim/utils/bezier.py
  manim/utils/caching.py
  manim/utils/family.py
  manim/utils/file_ops.py
  manim/utils/hashing.py
  manim/utils/space_ops.py
  manim/utils/testing/frames_comparison.py
  manim/utils/tex.py
  manim/utils/tex_file_writing.py
  scripts/template_docsting_with_example.py
  tests/helpers/graphical_units.py
  tests/utils/GraphicalUnitTester.py
  tests/utils/testing_utils.py
Labels: maintenance

#3018 Follow-up to :pr:`2988` -- fixes and improvements to some docstrings
  manim/animation/animation.py
  manim/camera/camera.py
  manim/mobject/types/image_mobject.py
  manim/scene/scene.py
Labels: documentation, maintenance

#2915 Added documentation to :mod:`.three_dimensions`
  manim/mobject/three_d/three_dimensions.py
Labels: documentation

#3017 Replaced renderer strings with :class:`.RendererType` enum entries
  docs/source/plugins.rst
  docs/source/reference_index/mobjects.rst
  manim/__init__.py
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/animation/animation.py
  manim/animation/changing.py
  manim/animation/composition.py
  manim/animation/transform.py
  manim/animation/transform_matching_parts.py
  manim/cli/render/commands.py
  manim/cli/render/render_options.py
  manim/constants.py
  manim/mobject/geometry/boolean_ops.py
  manim/mobject/geometry/line.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_compatibility.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/table.py
  manim/mobject/text/numbers.py
  manim/mobject/text/tex_mobject.py
  manim/mobject/text/text_mobject.py
  manim/mobject/three_d/three_dimensions.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/utils.py
  manim/mobject/vector_field.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/three_d_scene.py
  manim/utils/ipython_magic.py
  manim/utils/space_ops.py
  tests/module/mobject/mobject/test_set_attr.py
Labels: new feature, maintenance

#3019 Fixed rendering SVG paths with multiple move commands
  manim/mobject/types/vectorized_mobject.py
  manim/utils/iterables.py
  tests/test_graphical_units/control_data/img_and_svg/path_multiple_moves.npz
  tests/test_graphical_units/img_svg_resources/path_multiple_moves.svg
  tests/test_graphical_units/test_img_and_svg.py
Labels: pr:bugfix

#3016 Implemented :class:`.LineJointTypes` for both Cairo and OpenGL renderer
  example_scenes/basic.py
  manim/camera/camera.py
  manim/constants.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/renderer/opengl_renderer.py
  tests/test_graphical_units/control_data/mobjects/vmobject_joint_types.npz
  tests/test_graphical_units/test_mobjects.py
Labels: new feature

#3022 Corrected type hint in :meth:`Axes.coords_to_point`
  manim/mobject/graphing/coordinate_systems.py
Labels: documentation, typehints

#2927 Allowed ``networkx`` to return 3D layouts when passing ``dim=3`` in the ``layout_config`` of a :class:`.Graph`
  manim/mobject/graph.py
Labels: enhancement

#2938 Suggested fixes by iCR, OpenRefactory, Inc.
  manim/cli/render/commands.py
  manim/mobject/opengl/opengl_mobject.py
Labels: maintenance

#3029 CI: update actions version and add dependabot config
  .github/dependabot.yml
  .github/workflows/cffconvert.yml
  .github/workflows/ci.yml
  .github/workflows/publish-docker.yml
  .github/workflows/python-publish.yml
Labels: infrastructure

#3035 Include latex install instructions on ubuntu
  docs/source/installation/linux.rst
Labels: pr:easy review

#3054 Removed unused ``GraphicalUnitTester``
  docs/source/contributing/testing.rst
  tests/utils/GraphicalUnitTester.py
Labels: pr:easy review, maintenance
