Repository ManimCommunity/manim, pull requests merged in 2022-03, with the labels that each got.

#2593 Fixed bug with displaying images in Jupyter Notebooks when ``config.media_embed`` is set to ``False``
  manim/utils/ipython_magic.py
Labels: bugfix

#2587 Fix bug introduced in Tex rendering via #2574
  manim/utils/tex_file_writing.py
  tests/control_data/logs_data/bad_tex_scene_BadTex.txt
  tests/test_texmobject.py
Labels: bugfix

#2584 Fixed bug with invalid color type ``None``
  manim/mobject/types/vectorized_mobject.py
  tests/test_graphical_units/control_data/mobjects/match_style.npz
  tests/test_graphical_units/control_data/transform/ReplacementTransform.npz
  tests/test_graphical_units/test_mobjects.py
  tests/test_graphical_units/test_transform.py
Labels: bugfix

#2603 Reduced the number of warnings during documentation build
  docs/source/changelog/0.10.0-changelog.rst
  docs/source/changelog/0.11.0-changelog.rst
  docs/source/changelog/0.12.0-changelog.rst
  docs/source/changelog/0.13.0-changelog.rst
  docs/source/changelog/0.13.1-changelog.rst
  docs/source/changelog/0.14.0-changelog.rst
  docs/source/changelog/0.15.0-changelog.rst
  docs/source/changelog/0.5.0-changelog.rst
  docs/source/changelog/0.6.0-changelog.rst
  docs/source/changelog/0.7.0-changelog.rst
  docs/source/changelog/0.8.0-changelog.rst
  docs/source/changelog/0.9.0-changelog.rst
  docs/source/conf.py
  docs/source/contributing/internationalization.rst
  docs/source/installation/windows.rst
  scripts/dev_changelog.py
Labels: documentation, maintenance

#2570 Refactored docstrings in mod:`manim.mobject.graphing.coordinate_systems`
  manim/mobject/graphing/coordinate_systems.py
Labels: documentation

#2594 Fixed render flow issues with introducer animations
  manim/animation/animation.py
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
  tests/opengl/test_composition_opengl.py
  tests/test_composition.py
  tests/test_graphical_units/control_data/creation/bring_to_back_introducer.npz
  tests/test_graphical_units/control_data/creation/z_index_introducer.npz
  tests/test_graphical_units/control_data/vector_scene/vector_to_coords.npz
  tests/test_graphical_units/test_creation.py
  tests/test_graphical_units/test_vector_scene.py
Labels: bugfix

#2596 Prepared bugfix release v0.15.1
  CITATION.cff
  docs/i18n/gettext/changelog/0.10.0-changelog.pot
  docs/i18n/gettext/changelog/0.11.0-changelog.pot
  docs/i18n/gettext/changelog/0.12.0-changelog.pot
  docs/i18n/gettext/changelog/0.13.0-changelog.pot
  docs/i18n/gettext/changelog/0.13.1-changelog.pot
  docs/i18n/gettext/changelog/0.14.0-changelog.pot
  docs/i18n/gettext/changelog/0.15.0-changelog.pot
  docs/i18n/gettext/changelog/0.15.1-changelog.pot
  docs/i18n/gettext/changelog/0.5.0-changelog.pot
  docs/i18n/gettext/changelog/0.6.0-changelog.pot
  docs/i18n/gettext/changelog/0.7.0-changelog.pot
  docs/i18n/gettext/changelog/0.8.0-changelog.pot
  docs/i18n/gettext/changelog/0.9.0-changelog.pot
  docs/i18n/gettext/installation/windows.pot
  docs/i18n/gettext/reference/manim.mobject.graphing.coordinate_systems.Axes.pot
  docs/i18n/gettext/reference/manim.mobject.graphing.coordinate_systems.CoordinateSystem.pot
  docs/i18n/gettext/reference/manim.mobject.graphing.coordinate_systems.NumberPlane.pot
  docs/i18n/gettext/reference/manim.mobject.graphing.coordinate_systems.PolarPlane.pot
  docs/i18n/gettext/reference/manim.mobject.graphing.coordinate_systems.ThreeDAxes.pot
  docs/source/changelog.rst
  docs/source/changelog/0.15.1-changelog.rst
  pyproject.toml
Labels: release

#2404 Add SpiralIn Animation
  example_scenes/basic.py
  manim/animation/creation.py
  manim/mobject/logo.py
Labels: new feature

#2613 Fixed bug in :meth:`.Circle.point_at_angle` when the angle is not in the interval :math:`[0, 2\pi]`
  manim/mobject/geometry/arc.py
  tests/test_vectorized_mobject.py
Labels: bugfix

#2617 Re-added :mod:`.value_tracker` documentation
  docs/source/reference_index/mobjects.rst
Labels: documentation

#2620 Fixed typo in :meth:`.Animation.is_introducer`
  manim/animation/animation.py
Labels: documentation

#2062 Reuse shader wrappers and shader data
  manim/mobject/opengl/opengl_vectorized_mobject.py
Labels: opengl, performance

#2610 Add example PolygonOnAxes
  docs/source/examples.rst
Labels: documentation

#2561 Run tests on Linux-aarch64
  .github/workflows/ci.yml
  tests/test_scene_rendering/opengl/test_opengl_renderer.py
Labels: infrastructure

#2630 Remove WebGL renderer
  .github/workflows/ci.yml
  docker/Dockerfile
  docs/source/tutorials/configuration.rst
  manim/__init__.py
  manim/_config/default.cfg
  manim/_config/utils.py
  manim/camera/webgl_camera.py
  manim/cli/render/commands.py
  manim/cli/render/render_options.py
  manim/constants.py
  manim/grpc/__init__.py
  manim/grpc/gen/__init__.py
  manim/grpc/gen/frameserver_pb2.py
  manim/grpc/gen/frameserver_pb2_grpc.py
  manim/grpc/gen/renderserver_pb2.py
  manim/grpc/gen/renderserver_pb2_grpc.py
  manim/grpc/impl/__init__.py
  manim/grpc/impl/frame_server_impl.py
  manim/grpc/proto/frameserver.proto
  manim/grpc/proto/renderserver.proto
  manim/renderer/webgl_renderer.py
  poetry.lock
  pyproject.toml
  scripts/simple_cors_http_server.py
  scripts/update_protos.py
Labels: breaking changes, maintenance
