Repository ManimCommunity/manim, pull requests merged in 2023-11, with the labels that each got.

#3439 Prepare v0.18.0
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.18.0-changelog.rst
  docs/source/changelog/0.9.0-changelog.rst
  manim/mobject/graphing/coordinate_systems.py
  manim/utils/tex_file_writing.py
  pyproject.toml
Labels: release

#3450 Fixed wrong path in action building downloadable docs
  .github/workflows/release-publish-documentation.yml
Labels: maintenance

#3435 Allow accessing ghost vectors in :class:`.LinearTransformationScene`
  manim/scene/vector_space_scene.py
  tests/test_linear_transformation_scene.py
Labels: enhancement

#3461 Fix Indicate docstring typo
  manim/animation/indication.py
Labels: documentation

#3477 indication.py documentation typo
  manim/animation/indication.py
Labels: documentation
