Repository ManimCommunity/manim, pull requests merged in 2023-07, with the labels that each got.

#3205 Bugfix: Fix arc start angle type
  manim/mobject/geometry/arc.py
  manim/mobject/mobject.py
Labels: enhancement, typehints

#3274 Replaced incorrect mentions of Python 3.7 as the minimally required version
  docs/source/installation.rst
  docs/source/installation/linux.rst
  docs/source/installation/windows.rst
Labels: documentation, pr:easy review

#3298 Fixed expand animation for :class:`.ManimBanner`
  .github/workflows/ci.yml
  manim/mobject/logo.py
  tests/test_graphical_units/control_data/logo/banner.npz
  tests/test_graphical_units/test_banner.py
Labels: pr:bugfix

#3297 Improve Arrow Tip Showcase example in docstring of class ArrowTip
  manim/mobject/geometry/tips.py
Labels: documentation

#3264 Two New Classes in geometry module: :class:`.LabeledLine` and :class:`.LabeledArrow`
  manim/__init__.py
  manim/mobject/geometry/__init__.py
  manim/mobject/geometry/labeled.py
  tests/test_graphical_units/control_data/geometry/LabeledArrow.npz
  tests/test_graphical_units/control_data/geometry/LabeledLine.npz
  tests/test_graphical_units/test_geometry.py
Labels: enhancement
