Repository ManimCommunity/manim, pull requests merged in 2023-08, with the labels that each got.

#3306 Fixed IPython terminal history and embedded shell instatiation for interactive_embed scenes
  manim/scene/scene.py
Labels: pr:bugfix

#3299 Added new ``manim checkhealth`` CLI subcommand
  manim/__main__.py
  manim/cli/checkhealth/__init__.py
  manim/cli/checkhealth/checks.py
  manim/cli/checkhealth/commands.py
  manim/constants.py
  manim/mobject/logo.py
  manim/mobject/text/tex_mobject.py
  tests/interface/test_commands.py
Labels: new feature, highlight

#3315 Fix subcaption Type Mismatch
  manim/scene/scene.py
Labels: pr:bugfix

#3312 Added Docstring/Example for :meth:`always_redraw`
  manim/animation/updaters/mobject_update_utils.py
Labels: documentation

#3020 Adding :class: ManimColor to manim and converting all types
  .mypy.ini
  docs/source/_templates/autosummary/class.rst
  docs/source/conf.py
  manim/_config/utils.py
  manim/animation/changing.py
  manim/animation/creation.py
  manim/animation/indication.py
  manim/camera/camera.py
  manim/communitycolors.py
  manim/mobject/geometry/arc.py
  manim/mobject/geometry/labeled.py
  manim/mobject/geometry/line.py
  manim/mobject/geometry/polygram.py
  manim/mobject/geometry/shape_matchers.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/probability.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/table.py
  manim/mobject/text/tex_mobject.py
  manim/mobject/text/text_mobject.py
  manim/mobject/three_d/three_dimensions.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/plugins/import_plugins.py
  manim/scene/vector_space_scene.py
  manim/utils/color.py
  manim/utils/color/AS2700.py
  manim/utils/color/BS381.py
  manim/utils/color/X11.py
  manim/utils/color/XKCD.py
  manim/utils/color/__init__.py
  manim/utils/color/core.py
  manim/utils/color/manim_colors.py
  manim/utils/docbuild/autocolor_directive.py
  manim/utils/docbuild/manim_directive.py
  manim/utils/space_ops.py
  poetry.lock
  pyproject.toml
  tests/module/mobject/svg/test_svg_mobject.py
  tests/module/mobject/text/test_numbers.py
  tests/module/mobject/text/test_text_mobject.py
  tests/module/mobject/types/vectorized_mobject/test_stroke.py
  tests/module/utils/test_color.py
  tests/module/utils/test_manim_color.py
  tests/opengl/test_color_opengl.py
  tests/opengl/test_stroke_opengl.py
  tests/opengl/test_svg_mobject_opengl.py
  tests/test_graphical_units/test_text.py
Labels: enhancement, breaking changes, highlight
