Repository ManimCommunity/manim, pull requests merged in 2023-03, with the labels that each got.

#3186 Fixed extlinks in docs to work with latest version of Sphinx.
  docs/source/conf.py
Labels: documentation

#3195 Fix: Axes Scaling Had No Effect on plot_implicit_curve()
  manim/mobject/graphing/coordinate_systems.py
Labels: pr:bugfix

#3191 Fixed rendering in named threads, limit condition to interactive OpenGL mode
  manim/scene/scene.py
Labels: enhancement, opengl

#3189 Corrected the hinted return type for :func:`angle_between_vectors`
  manim/utils/space_ops.py
Labels: typehints

#3180 Speed up width/height/depth by reducing copying
  manim/mobject/mobject.py
  tests/module/mobject/mobject/test_mobject.py
Labels: enhancement, performance

#3155 Added support for individualized radius values in :meth:`.Polygram.round_corners`
  manim/mobject/geometry/polygram.py
  tests/test_graphical_units/control_data/geometry/RoundedRectangle.npz
Labels: new feature

#3134 Store color data to prevent opengl embed lag
  manim/mobject/opengl/opengl_surface.py
Labels: enhancement, opengl

#3159 Added :meth:`.set_opacity_by_tex` method for setting the opacity of parts of Tex mobjects
  manim/mobject/text/tex_mobject.py
  tests/test_graphical_units/control_data/tex_mobject/set_opacity_by_tex.npz
  tests/test_graphical_units/test_tex_mobject.py
Labels: new feature

#3046 Add warning if font is not found for Text, Code, and MarkupText
  manim/mobject/text/code_mobject.py
  manim/mobject/text/text_mobject.py
  tests/test_graphical_units/test_text.py
Labels: enhancement

#3181 Improve creation time for large Text Mobjects
  manim/mobject/svg/svg_mobject.py
  manim/mobject/text/text_mobject.py
Labels: enhancement, performance

#3199 Updated ``winget`` command for installing MiKTeX in documentation
  docs/source/installation/windows.rst
Labels: documentation

#3200 Made import from ``moderngl`` compatible with more recent versions
  manim/renderer/shader.py
Labels: maintenance

#3015 Fixed bug with ``label_constructor`` in :meth:`.NumberLine.add_labels`
  manim/mobject/graphing/number_line.py
Labels: pr:bugfix
