Repository ManimCommunity/manim, pull requests merged in 2023-01, with the labels that each got.

#3103 Remove deprecated function from `opengl_surface.py`
  manim/mobject/opengl/opengl_surface.py
Labels: pr:deprecation, maintenance

#3109 Clean-up, type-hints and documentation for `three_dimensions.py`
  manim/mobject/three_d/three_dimensions.py
Labels: documentation

#3107 Porting and drastical rewrite to reach compatibility with `3b1b/manim` again
  manim/_config/utils.py
  manim/constants.py
  manim/event_handler/__init__.py
  manim/event_handler/event_dispatcher.py
  manim/event_handler/event_listener.py
  manim/event_handler/event_type.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/renderer/opengl_renderer.py
  manim/renderer/shader_wrapper.py
  manim/scene/scene.py
  manim/utils/bezier.py
  manim/utils/color.py
  manim/utils/directories.py
  manim/utils/file_ops.py
  manim/utils/simple_functions.py
  manim/utils/space_ops.py
Labels: breaking changes, maintenance

#3126 Change links redirecting to dead troubleshooting page
  .github/ISSUE_TEMPLATE/installation_issue.md
  manim/utils/tex_file_writing.py
Labels: documentation

#3106 Fixes ignored depth_test parameter for OpenGLVMobjects
  manim/mobject/opengl/opengl_vectorized_mobject.py
Labels: pr:bugfix, opengl
