Repository ManimCommunity/manim, pull requests merged in 2023-04, with the labels that each got.

#3166 Made :class:`.ArrowTriangleTip`, :class:`.ArrowTriangleFilledTip` available to module namespace
  manim/mobject/geometry/tips.py
Labels: maintenance

#3201 New tip shape :class:`.StealthTip`, allow specifying tip shape of :class:`.NumberLine`
  manim/mobject/geometry/tips.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/number_line.py
  tests/test_graphical_units/control_data/plot/axes.npz
  tests/test_graphical_units/test_axes.py
Labels: new feature

#2974 Added :class:`.DiGraph`, a mobject representing directed graphs
  manim/mobject/graph.py
  tests/module/mobject/test_graph.py
  tests/opengl/test_graph_opengl.py
Labels: new feature

#3204 Fixed docstring formatting of :meth:`.Scene.replace` and improved its error handling
  manim/scene/scene.py
Labels: documentation, maintenance

#3198 Prepare new release: v0.17.3
  CITATION.cff
  docs/source/changelog.rst
  docs/source/changelog/0.17.3-changelog.rst
  manim/mobject/graphing/coordinate_systems.py
  pyproject.toml
Labels: release

#3219 Enable social cards in documentation
  docs/source/_static/logo.png
  docs/source/conf.py
  poetry.lock
  pyproject.toml
Labels: documentation

#3190 Enables Use of input_to_graph_point() by CurvesAsSubmobjects Instances
  manim/mobject/types/vectorized_mobject.py
  tests/module/mobject/types/vectorized_mobject/test_vectorized_mobject.py
Labels: enhancement
