Repository ManimCommunity/manim, pull requests merged in 2023-02, with the labels that each got.

#3152 Fixed behavior of `Wait` with specified `stop_condition`
  manim/animation/animation.py
  manim/scene/scene.py
  tests/test_scene_rendering/test_play_logic.py
Labels: pr:bugfix

#3165 Remove deprecated arg in M.object.align_to()
  manim/mobject/mobject.py
Labels: maintenance

#3160 typo(docs): Fix grammar
  docs/i18n/gettext/reference/manim.animation.animation.Animation.pot
  manim/animation/animation.py
Labels: documentation
