Repository ManimCommunity/manim, pull requests merged in 2023-12, with the labels that each got.

#3510 fix line_join to joint_type in example_scenes/basic.py
  example_scenes/basic.py
Labels: maintenance

#3316 Implement caching of fonts list to improve runtime performance
  manim/mobject/text/text_mobject.py
Labels: pr:bugfix

#3516 Added `cap_style` feature to `VMobject`
  manim/camera/camera.py
  manim/constants.py
  manim/mobject/types/vectorized_mobject.py
  tests/test_graphical_units/control_data/mobjects/vmobject_cap_styles.npz
  tests/test_graphical_units/test_mobjects.py
Labels: documentation, new feature, cairo

#3329 feat(cli): optionally hide version splash
  manim/__main__.py
  tests/interface/test_commands.py
Labels: new feature

#3499 Reformatting the `--save_sections` output to have the format `<Scene>_<SecNum>_<SecName><extension>`
  manim/scene/scene_file_writer.py
  tests/control_data/videos_data/SceneWithEnabledSections.json
  tests/control_data/videos_data/SceneWithSections.json
  tests/control_data/videos_data/SceneWithSkipAnimations.json
Labels: enhancement, refactor, breaking changes

#3500 Explain ``.Transform`` vs ``.ReplacementTransform`` in quickstart examples
  docs/source/tutorials/quickstart.rst
Labels: documentation

#3515 Fix formatting building blocks
  docs/html
  docs/skip-manim
  docs/source/tutorials/building_blocks.rst
Labels: documentation, pr:easy review

#3493 Account for dtype in the pixel array so the maximum value stays correct in the invert function
  manim/mobject/types/image_mobject.py
  tests/module/mobject/test_image.py
Labels: pr:bugfix

#3428 Added `grid_lines` attribute to `Rectangle` to add individual styling to the grid lines
  manim/mobject/geometry/polygram.py
Labels: pr:bugfix, enhancement

#3513 Fix rectangle grid properties (#3082)
  manim/mobject/geometry/polygram.py
Labels: pr:bugfix

#3491 Fix animations with zero runtime length to give a useful error instead of a broken pipe
  manim/animation/animation.py
  manim/animation/composition.py
  tests/module/animation/test_composition.py
Labels: pr:bugfix

#3436 fixed the stroke width issue with single color in streamlines
  manim/mobject/vector_field.py
  tests/module/mobject/types/vectorized_mobject/test_stroke.py
Labels: pr:bugfix

#3408 Add Documentation to `.to_edge` and `to_corner`
  manim/mobject/mobject.py
Labels: documentation

#3365 Adding the ability to pass lists and generators to .play()
  manim/animation/composition.py
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
  manim/utils/parameter_parsing.py
Labels: new feature, Suggestion

#3475 Disable rendering doc examples for experimental branch
  manim/utils/docbuild/manim_directive.py
Labels: experimental

#3530 chore(docs): add some words about Cairo 1.18
  docs/source/contributing/testing.rst
Labels: documentation

#3541 Fix formatting of ``MoveAlongPath`` docs
  manim/animation/movement.py
Labels: documentation, pr:easy review

#3543 Fixed :attr:`.Mobject.animate` type-hint to allow LSP autocomplete
  manim/mobject/mobject.py
Labels: maintenance

#3539 Remove meth:``.Mobject.wag``
  manim/mobject/mobject.py
Labels: maintenance

#3545 Finish TODO's in ``contributing/typings.rst``
  docs/source/contributing/typings.rst
Labels: documentation

#3549 Fix use of `Mobject`'s deprecated `get_*()` and `set_*()` methods in Cairo tests
  manim/animation/specialized.py
  manim/animation/transform_matching_parts.py
  manim/mobject/graphing/number_line.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/text/text_mobject.py
  manim/mobject/value_tracker.py
Labels: maintenance

#3554 Add note in docstring of `ManimColor` about class constructors
  manim/utils/color/core.py
Labels: documentation, maintenance

#3555 Improve documentation section about contributing to docs
  docs/source/contributing.rst
  docs/source/contributing/development.rst
  docs/source/contributing/docs.rst
  docs/source/contributing/docs/admonitions.rst
  docs/source/contributing/docs/docstrings.rst
  docs/source/contributing/docs/examples.rst
  docs/source/contributing/docs/references.rst
  docs/source/contributing/docs/typings.rst
  manim/utils/docbuild/__init__.py
Labels: documentation, breaking changes
