Repository ManimCommunity/manim, pull requests merged in 2024-05, with the labels that each got.

#3501 Let `SceneFileWriter` access `ffmpeg` via `av` instead of via external process
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/installation_issue.md
  .github/workflows/ci.yml
  .github/workflows/release-publish-documentation.yml
  .readthedocs.yml
  docker/Dockerfile
  docs/source/contributing/development.rst
  docs/source/guides/deep_dive.rst
  docs/source/installation.rst
  docs/source/installation/jupyter.rst
  docs/source/installation/linux.rst
  docs/source/installation/macos.rst
  docs/source/installation/windows.rst
  manim/_config/default.cfg
  manim/_config/logger_utils.py
  manim/_config/utils.py
  manim/animation/animation.py
  manim/animation/composition.py
  manim/cli/checkhealth/checks.py
  manim/mobject/geometry/polygram.py
  manim/renderer/cairo_renderer.py
  manim/renderer/opengl_renderer.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/commands.py
  manim/utils/file_ops.py
  manim/utils/testing/_test_class_makers.py
  poetry.lock
  pyproject.toml
  tests/control_data/videos_data/InputFileViaCfg.json
  tests/control_data/videos_data/SceneWithDisabledSections.json
  tests/control_data/videos_data/SceneWithEnabledSections.json
  tests/control_data/videos_data/SceneWithMultipleCallsWithNFlag.json
  tests/control_data/videos_data/SceneWithMultiplePlayCallsWithNFlag.json
  tests/control_data/videos_data/SceneWithMultipleWaitCallsWithNFlag.json
  tests/control_data/videos_data/SceneWithSections.json
  tests/control_data/videos_data/SceneWithSkipAnimations.json
  tests/control_data/videos_data/SquareToCircleWithDefaultValues.json
  tests/control_data/videos_data/SquareToCircleWithlFlag.json
  tests/interface/test_commands.py
  tests/module/animation/test_animation.py
  tests/module/animation/test_composition.py
  tests/test_graphical_units/control_data/coordinate_system/implicit_graph.npz
  tests/test_graphical_units/control_data/creation/bring_to_back_introducer.npz
  tests/test_graphical_units/control_data/creation/z_index_introducer.npz
  tests/test_graphical_units/control_data/functions/ImplicitFunction.npz
  tests/test_graphical_units/control_data/img_and_svg/Arcs02.npz
  tests/test_graphical_units/control_data/img_and_svg/WeightSVG.npz
  tests/test_graphical_units/control_data/indication/Circumscribe.npz
  tests/test_graphical_units/control_data/transform/ReplacementTransform.npz
  tests/test_graphical_units/control_data/transform_matching_parts/TransformMatchingDisplaysCorrect.npz
  tests/test_graphical_units/control_data/updaters/LastFrameWhenCleared.npz
  tests/test_graphical_units/control_data/vector_scene/vector_to_coords.npz
  tests/test_scene_rendering/test_file_writer.py
Labels: refactor, breaking changes

#3761 Use --py39-plus in pre-commit
  .pre-commit-config.yaml
  manim/_config/__init__.py
  manim/_config/utils.py
  manim/animation/animation.py
  manim/animation/composition.py
  manim/animation/creation.py
  manim/animation/indication.py
  manim/animation/rotation.py
  manim/animation/specialized.py
  manim/animation/transform.py
  manim/camera/camera.py
  manim/mobject/graph.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/functions.py
  manim/mobject/graphing/number_line.py
  manim/mobject/graphing/probability.py
  manim/mobject/graphing/scale.py
  manim/mobject/matrix.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_surface.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/svg/brace.py
  manim/mobject/table.py
  manim/mobject/text/numbers.py
  manim/mobject/text/tex_mobject.py
  manim/mobject/text/text_mobject.py
  manim/mobject/three_d/three_dimensions.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/renderer/cairo_renderer.py
  manim/renderer/opengl_renderer.py
  manim/scene/scene.py
  manim/scene/three_d_scene.py
  manim/utils/bezier.py
  manim/utils/color/__init__.py
  manim/utils/color/core.py
  manim/utils/color/manim_colors.py
  manim/utils/commands.py
  manim/utils/deprecation.py
  manim/utils/family.py
  manim/utils/iterables.py
  manim/utils/parameter_parsing.py
  manim/utils/space_ops.py
  manim/utils/tex_file_writing.py
Labels: maintenance

#3768 Optimized `manim.utils.bezier.is_closed()`
  manim/utils/bezier.py
Labels: pr:easy review, performance

#3766 Created and optimized Bézier splitting functions such as `partial_bezier_points()` in `manim.utils.bezier`
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/utils/bezier.py
  tests/module/utils/_split_matrices.py
  tests/module/utils/_subdivision_matrices.py
  tests/module/utils/test_bezier.py
Labels: performance

#3756 Fix assertions and improve error messages when adding submobjects
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
  tests/module/mobject/mobject/test_mobject.py
  tests/module/mobject/types/vectorized_mobject/test_vectorized_mobject.py
  tests/opengl/test_opengl_mobject.py
  tests/opengl/test_opengl_vectorized_mobject.py
Labels: pr:bugfix, refactor, maintenance

#3779 pre-commit change to ruff
  .pre-commit-config.yaml
  example_scenes/basic.py
  manim/_config/__init__.py
  manim/_config/cli_colors.py
  manim/mobject/geometry/tips.py
  manim/mobject/graph.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/number_line.py
  manim/mobject/mobject.py
  manim/mobject/text/text_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/utils/color/X11.py
  manim/utils/color/core.py
  manim/utils/deprecation.py
  manim/utils/docbuild/module_parsing.py
  manim/utils/space_ops.py
  tests/module/mobject/text/test_markup.py
  tests/opengl/test_markup_opengl.py
  tests/test_scene_rendering/opengl/test_cli_flags_opengl.py
  tests/test_scene_rendering/test_cli_flags.py
Labels: maintenance

#3778 Fixed `there_and_back_with_pause()` rate function behaviour with different `pause_ratio` values
  manim/utils/rate_functions.py
Labels: pr:bugfix

#3765 Optimize `VMobject` methods which append to `points`
  manim/mobject/types/vectorized_mobject.py
Labels: performance

#3754 Add `@` shorthand for `CoordinateSystem` methods `coords_to_point` (`c2p`) and `point_to_coords` (`p2c`)
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/number_line.py
  tests/module/mobject/graphing/test_coordinate_system.py
Labels: new feature
