Repository ManimCommunity/manim, pull requests merged in 2024-04, with the labels that each got.

#3620 Code Cleanup: removing unused imports and global variables
  manim/__main__.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_geometry.py
  manim/mobject/table.py
  manim/mobject/text/tex_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/renderer/opengl_renderer.py
Labels: maintenance

#3508 Fixing the behavior of `.become` to not modify target mobject via side effects fix color linking
  manim/mobject/mobject.py
  manim/mobject/types/vectorized_mobject.py
  tests/test_graphical_units/control_data/mobjects/become.npz
  tests/test_graphical_units/control_data/mobjects/become_no_color_linking.npz
  tests/test_graphical_units/test_mobjects.py
Labels: enhancement, breaking changes

#3641 Added some examples for `Mobject`/`VMobject` methods
  manim/mobject/mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: documentation

#3640 Fix typehint of `Vector` direction parameter
  manim/mobject/geometry/line.py
Labels: maintenance

#3688 Remove deprecated parameters and animations
  manim/animation/indication.py
  manim/utils/paths.py
  tests/test_graphical_units/control_data/indication/ShowCreationThenFadeOut.npz
  tests/test_graphical_units/test_indication.py
Labels: pr:deprecation, maintenance

#3687 Fix for windows cp1252 encoding failure (fix test pipeline)
  .github/workflows/ci.yml
  manim/utils/commands.py
  tests/test_logging/test_logging.py
Labels: github_actions

#3694 Fix NameError in try... except
  manim/cli/render/commands.py
Labels: pr:bugfix

#3704 docs: update typing guidelines
  docs/source/contributing/docs/typings.rst
Labels: documentation

#3703 Update documentation and typings for `ParametricFunction`
  manim/mobject/graphing/functions.py
Labels: documentation, typehints

#3708 fix(copyright): automate copyright updating for docs
  docs/source/conf.py
Labels: maintenance

#3668 Fix some typehints in mobject.py
  manim/animation/speedmodifier.py
  manim/mobject/mobject.py
Labels: typehints

#3718 Fixed `Mobject.put_start_and_end_on` with same start and end point
  manim/mobject/mobject.py
  tests/module/mobject/graphing/test_number_line.py
Labels: enhancement

#3671 fix(autoaliasattr): search for type aliases under if TYPE_CHECKING
  manim/utils/docbuild/module_parsing.py
Labels: pr:bugfix, documentation

#3720 build(deps): Update sphinx deps
  docs/requirements.txt
Labels: dependencies

#3589 Fix issue where SpiralIn doesn't show elements.
  manim/animation/creation.py
  tests/test_graphical_units/control_data/creation/SpiralIn.npz
  tests/test_graphical_units/test_creation.py
Labels: pr:bugfix, needs discussion

#3434 Clean Graph layouts and increase flexibility
  manim/mobject/graph.py
  tests/module/mobject/test_graph.py
Labels: enhancement, new feature

#3728 Follow-up to graph layout cleanup: improvements for tests and typing
  manim/mobject/graph.py
  tests/module/mobject/test_graph.py
Labels: maintenance

#3730 Improve consistency in axis label example
  manim/mobject/graphing/coordinate_systems.py
Labels: documentation

#3729 build(ci): change from macos-latest to macos-13
  .github/workflows/ci.yml
Labels: pr:bugfix

#3615 Add ``--preview_command`` cli flag
  manim/_config/utils.py
  manim/cli/render/global_options.py
  manim/utils/file_ops.py
Labels: new feature

#3542 AnimationGroup: optimized interpolate() and fixed alpha bug on finish()
  manim/animation/animation.py
  manim/animation/composition.py
  tests/module/animation/test_composition.py
  tests/opengl/test_composition_opengl.py
Labels: performance

#3214 Fixed ```get_anchors()``` Return Type Inconsistency
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: maintenance, typehints

#3734 Fixed warning about missing plugin `""`
  manim/_config/utils.py
Labels: pr:bugfix, easy

#3719 Prepare new release: v0.18.1
  CITATION.cff
  docs/source/changelog.rst
  pyproject.toml
Labels: release

#3612 feat: Add three animations that together simulate a typing animation
  manim/animation/creation.py
  manim/animation/indication.py
Labels: new feature

#3737 Fixed action for building downloadable documentation
  .github/workflows/release-publish-documentation.yml
Labels: maintenance
