Repository ManimCommunity/manim, pull requests merged in 2024-12, with the labels that each got.

#4037 Pin version of pyav to avoid breaking changes in their API
  poetry.lock
  pyproject.toml
Labels: dependencies

#4039 Add a `delay` parameter to `turn_animation_into_updater`
  manim/animation/updaters/mobject_update_utils.py
Labels: new feature

#3930 Rewrite installation instructions
  docs/requirements.txt
  docs/source/conf.py
  docs/source/faq/installation.md
  docs/source/installation.rst
  docs/source/installation/conda.rst
  docs/source/installation/linux.rst
  docs/source/installation/macos.rst
  docs/source/installation/uv.md
  docs/source/installation/windows.rst
  docs/source/tutorials/quickstart.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#4038 Fix typehint of :meth:`.Scene.play` to allow `.animate`
  manim/renderer/cairo_renderer.py
  manim/scene/scene.py
Labels: maintenance

#3924 Fix `SyntaxWarnings` when building the docs and bump `readthedocs` to Python 3.13
  .readthedocs.yml
  docs/source/examples.rst
  manim/animation/fading.py
  manim/mobject/geometry/line.py
  manim/mobject/matrix.py
  manim/utils/docbuild/manim_directive.py
Labels: maintenance

#4060 [Experimental] Start Migration Guide
  docs/source/changelog.rst
  docs/source/changelog/experimental.md
Labels: documentation, experimental

#4059 [EXPERIMENTAL] Remove `ThreeDScene` and rewrite `Camera` internals
  docs/i18n/gettext/reference/manim.mobject.three_d.three_dimensions.Line3D.pot
  docs/i18n/gettext/reference/manim.mobject.three_d.three_dimensions.pot
  docs/i18n/gettext/reference/manim.scene.three_d_scene.SpecialThreeDScene.pot
  docs/i18n/gettext/reference/manim.scene.three_d_scene.ThreeDScene.pot
  docs/source/contributing/testing.rst
  docs/source/examples.rst
  manim/__init__.py
  manim/camera/camera.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/functions.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/three_d/polyhedra.py
  manim/mobject/three_d/three_dimensions.py
  manim/renderer/opengl_renderer.py
  manim/renderer/renderer.py
  manim/scene/three_d_scene.py
  manim/utils/testing/frames_comparison.py
  tests/module/scene/test_threed_scene.py
  tests/test_graphical_units/test_axes.py
  tests/test_graphical_units/test_coordinate_systems.py
  tests/test_graphical_units/test_mobjects.py
  tests/test_graphical_units/test_threed.py
Labels: experimental
