Repository ManimCommunity/manim, pull requests merged in 2024-07, with the labels that each got.

#3849 Fix incorrect version number in plugin section in docs
  docs/source/plugins.rst
Labels: documentation

#3851 Rename `manim.typing.Image` type aliases to `PixelArray` to avoid conflict with `PIL.Image`
  manim/mobject/mobject.py
  manim/typing.py
Labels: documentation, pr:easy review, typehints

#3853 Change from tempconfig to a config fixture in tests
  tests/conftest.py
  tests/helpers/graphical_units.py
  tests/module/animation/test_animation.py
  tests/module/animation/test_creation.py
  tests/module/mobject/mobject/test_copy.py
  tests/module/mobject/mobject/test_opengl_metaclass.py
  tests/module/mobject/mobject/test_set_attr.py
  tests/module/mobject/text/test_texmobject.py
  tests/module/scene/test_scene.py
  tests/module/utils/test_units.py
  tests/opengl/test_config_opengl.py
  tests/opengl/test_copy_opengl.py
  tests/opengl/test_ipython_magic_opengl.py
  tests/opengl/test_texmobject_opengl.py
  tests/test_config.py
  tests/test_ipython_magic.py
  tests/test_scene_rendering/conftest.py
  tests/test_scene_rendering/opengl/test_opengl_renderer.py
  tests/test_scene_rendering/opengl/test_play_logic_opengl.py
  tests/test_scene_rendering/simple_scenes.py
  tests/test_scene_rendering/test_play_logic.py
Labels: enhancement, testing

#3839 Fix :attr:`.ManimConfig.format` not updating movie file extension
  manim/_config/utils.py
  tests/test_config.py
Labels: pr:bugfix

#3829 Rewrite `manim.utils.bezier.get_quadratic_approximation_of_cubic()` to produce curves which can be animated smoothly
  manim/utils/bezier.py
  tests/module/utils/test_bezier.py
Labels: enhancement

#3855 Log execution time of scene rendering in the Manim Checkhealth command
  manim/cli/checkhealth/commands.py
Labels: enhancement

#3760 Optimize `VMobject.pointwise_become_partial()`
  manim/mobject/types/vectorized_mobject.py
Labels: pr:easy review, performance

#3857 Update installation instructions for MacOS (via dedicated brew formula)
  docs/source/installation/macos.rst
Labels: documentation

#3858 Update docker to use ENV x=y instead of ENV x y
  docker/Dockerfile
Labels: maintenance

#3680 Fixed behavior of `config.background_opacity < 1` and duplicated log messages
  manim/_config/logger_utils.py
  manim/_config/utils.py
  manim/cli/render/global_options.py
  manim/cli/render/render_options.py
  manim/renderer/shader_wrapper.py
  manim/utils/deprecation.py
  manim/utils/testing/_frames_testers.py
  tests/conftest.py
  tests/helpers/graphical_units.py
  tests/module/animation/test_animation.py
  tests/module/mobject/geometry/test_unit_geometry.py
  tests/module/utils/test_deprecation.py
  tests/test_config.py
Labels: pr:bugfix, enhancement

#3877 Fix pre-commit linting
  manim/_config/utils.py
  manim/mobject/graph.py
Labels: maintenance

#3872 Use ruff for pytest style
  manim/mobject/mobject.py
  pyproject.toml
  tests/module/animation/test_animate.py
  tests/module/animation/test_composition.py
  tests/module/mobject/graphing/test_coordinate_system.py
  tests/module/mobject/test_boolean_ops.py
  tests/module/mobject/text/test_texmobject.py
  tests/module/scene/test_auto_zoom.py
  tests/opengl/test_animate_opengl.py
  tests/opengl/test_coordinate_system_opengl.py
  tests/opengl/test_texmobject_opengl.py
  tests/test_graphical_units/conftest.py
  tests/test_graphical_units/test_transform_matching_parts.py
  tests/test_linear_transformation_scene.py
  tests/test_logging/test_logging.py
  tests/test_plugins/test_plugins.py
  tests/test_scene_rendering/test_file_writer.py
Labels: maintenance

#3876 feat: set_default for Animation class
  manim/animation/animation.py
  tests/test_graphical_units/test_animation.py
Labels: new feature

#3873 Use ruff instead of flake8-simplify
  docs/source/conf.py
  manim/_config/utils.py
  manim/animation/creation.py
  manim/animation/fading.py
  manim/animation/specialized.py
  manim/cli/cfg/group.py
  manim/mobject/geometry/line.py
  manim/mobject/geometry/polygram.py
  manim/mobject/graph.py
  manim/mobject/graphing/probability.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_geometry.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/text/numbers.py
  manim/mobject/three_d/three_dimensions.py
  manim/mobject/types/vectorized_mobject.py
  manim/opengl/__init__.py
  manim/renderer/opengl_renderer.py
  manim/renderer/shader.py
  manim/scene/scene_file_writer.py
  manim/utils/bezier.py
  manim/utils/docbuild/autoaliasattr_directive.py
  manim/utils/docbuild/autocolor_directive.py
  manim/utils/docbuild/manim_directive.py
  manim/utils/space_ops.py
  pyproject.toml
  scripts/dev_changelog.py
Labels: maintenance

#3874 Cleanup legacy code in experimental
  example_scenes/test_new_rendering.py
  manim/animation/animation.py
  manim/animation/protocol.py
  manim/animation/transform.py
  manim/manager.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/mobject/text/tex_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/renderer/opengl_renderer.py
Labels: maintenance, experimental

#3882 Change flake8-comprehensions and flake8-bugbear to ruff
  .pre-commit-config.yaml
  manim/_config/utils.py
  manim/cli/cfg/group.py
  manim/cli/default_group.py
  manim/mobject/geometry/arc.py
  manim/mobject/geometry/boolean_ops.py
  manim/mobject/graph.py
  manim/mobject/opengl/opengl_point_cloud_mobject.py
  manim/mobject/svg/brace.py
  manim/mobject/text/text_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/scene/scene.py
  manim/scene/three_d_scene.py
  manim/utils/hashing.py
  manim/utils/testing/_frames_testers.py
  manim/utils/testing/_test_class_makers.py
  manim/utils/testing/frames_comparison.py
  manim/utils/tex.py
  pyproject.toml
Labels: enhancement

#3884 Rename parameters and variables conflicting with builtin functions
  .pre-commit-config.yaml
  docs/source/conf.py
  manim/mobject/mobject.py
  manim/mobject/svg/svg_mobject.py
  manim/renderer/opengl_renderer.py
  manim/scene/scene.py
  manim/scene/scene_file_writer.py
  manim/scene/section.py
  manim/utils/color/core.py
  manim/utils/deprecation.py
  manim/utils/opengl.py
  pyproject.toml
  tests/test_scene_rendering/simple_scenes.py
Labels: breaking changes

#3148 Added `colorscale` to `axes.plot()`
  manim/mobject/graphing/coordinate_systems.py
  tests/opengl/control_data/coordinate_system_opengl/gradient_line_graph_x_axis_using_opengl_renderer[None].npz
  tests/opengl/control_data/coordinate_system_opengl/gradient_line_graph_y_axis_using_opengl_renderer[None].npz
  tests/opengl/test_coordinate_system_opengl.py
  tests/test_graphical_units/control_data/coordinate_system/gradient_line_graph_x_axis.npz
  tests/test_graphical_units/control_data/coordinate_system/gradient_line_graph_y_axis.npz
  tests/test_graphical_units/test_coordinate_systems.py
Labels: new feature

#3885 Fix :meth:`.OpenGLMobject.invert` not reassembling family
  manim/mobject/opengl/opengl_mobject.py
Labels: pr:bugfix

#3518 Experimenting with an HSV class
  manim/typing.py
  manim/utils/color/core.py
  tests/module/utils/test_manim_color.py
Labels: new feature, needs discussion

#3887 Fix typo from HSV PR
  manim/utils/color/core.py
Labels: pr:easy review, maintenance

#3871 Fix MathTex on experimental
  example_scenes/test_new_rendering.py
  manim/mobject/text/tex_mobject.py
Labels: experimental
