Repository ManimCommunity/manim, pull requests merged in 2024-11, with the labels that each got.

#3913 Feat: dvipsnames and svgnames color palettes
  manim/utils/color/DVIPSNAMES.py
  manim/utils/color/SVGNAMES.py
  manim/utils/color/__init__.py
Labels: enhancement

#3997 Add a time property to scene
  manim/scene/scene.py
  tests/module/scene/test_scene.py
  tests/test_scene_rendering/test_play_logic.py
Labels: enhancement, new feature

#4006 Stop ignoring `manim.plugins` errors in `mypy.ini`
  manim/plugins/__init__.py
  manim/plugins/plugins_flags.py
  mypy.ini
Labels: pr:easy review, typehints

#4007 Add typings to `manim/__main__.py`
  manim/__main__.py
  mypy.ini
Labels: pr:easy review, typehints

#4013 Fix scene skipping for `config.upto_animation_number` set to 0 to end after first animation
  manim/renderer/cairo_renderer.py
  manim/renderer/opengl_renderer.py
  tests/test_config.py
Labels: pr:bugfix, pr:easy review

#3992 Add darker, lighter and contrasting methods to ManimColor
  manim/utils/color/core.py
  manim/utils/color/manim_colors.py
  tests/module/utils/test_manim_color.py
Labels: new feature
