Repository ManimCommunity/manim, pull requests merged in 2024-01, with the labels that each got.

#3553 Add 'to be used in the future' TODOs to `ManimFrame`
  manim/_config/__init__.py
  manim/_config/utils.py
Labels: pr:easy review

#3520 Refactor `TexTemplate`
  manim/_config/utils.py
  manim/utils/tex.py
  tests/control_data/logs_data/bad_tex_scene_BadTex.txt
  tests/module/mobject/text/test_texmobject.py
  tests/module/utils/test_tex.py
  tests/opengl/test_texmobject_opengl.py
Labels: refactor

#3593 updated several packages (pillow, jupyterlab, notebook, jupyterlab-lsp, jinja2, gitpython)
  poetry.lock
Labels: maintenance, dependencies

#3528 Removed -s / --save_last_frame flag from CLI arguments
  manim/cli/render/render_options.py
Labels: maintenance

#3582 Update docker.rst to use bash from the PATH in docker run command
  docs/source/installation/docker.rst
Labels: enhancement

#3594 fix typo in value_tracker.py
  manim/mobject/value_tracker.py
Labels: documentation
