Repository ManimCommunity/manim, pull requests merged in 2024-02, with the labels that each got.

#3599 Fix `get_arc_center()` returning reference of point
  manim/mobject/geometry/arc.py
Labels: pr:bugfix

#3592 Fix typehint of :attr:`InternalPoint2D_Array`
  manim/typing.py
Labels: pr:easy review, maintenance

#3611 Fix error in Windows CI pipeline
  .github/workflows/ci.yml
Labels: maintenance

#3595 Revert vector type aliases to NumPy ndarrays
  manim/typing.py
Labels: maintenance

#3429 Improve handling of specified font name
  manim/mobject/text/text_mobject.py
  tests/module/mobject/text/test_text_mobject.py
Labels: enhancement

#3524 Remove support for dynamic plugin imports
  docs/source/plugins.rst
  manim/plugins/__init__.py
  manim/plugins/import_plugins.py
  manim/plugins/plugins_flags.py
  poetry.lock
  pyproject.toml
  tests/test_plugins/simple_scenes.py
  tests/test_plugins/test_plugins.py
Labels: maintenance

#3621 Run `poetry lock --no-update`
  poetry.lock
Labels: maintenance
