Repository ManimCommunity/manim, pull requests merged in 2024-08, with the labels that each got.

#3888 Significantly reduce rendering time with a separate thread for writing frames to stream
  manim/scene/scene_file_writer.py
Labels: enhancement

#3895 Lock `poetry.lock`
  poetry.lock
Labels: pr:easy review, maintenance

#3832 bugfix: convert non-`.wav`/`.raw` files to `.wav` before passing to pydub
  manim/scene/scene_file_writer.py
  tests/test_scene_rendering/click.mp3
  tests/test_scene_rendering/test_file_writer.py
Labels: pr:bugfix

#3922 Simplify Sector Class by Removing Redundant Parameters
  manim/mobject/geometry/arc.py
Labels: breaking changes
