Repository ManimCommunity/manim, pull requests merged in 2024-10, with the labels that each got.

#3955 os.system -> subprocess
  manim/utils/tex_file_writing.py
  scripts/make_and_open_docs.py
Labels: pr:easy review, maintenance

#3956 Set AAC codec for audio in mp4 files, add transcoding utility
  manim/scene/scene_file_writer.py
  tests/test_scene_rendering/test_file_writer.py
Labels: pr:bugfix, enhancement

#3960 Optimized `interpolate` and `bezier` in `manim.utils.bezier`
  manim/utils/bezier.py
Labels: enhancement, performance

#3958 Fix: `.to_edge()`'s example demonstration in docs
  manim/mobject/mobject.py
Labels: documentation

#3925 Use Github Markdown on README
  README.md
Labels: enhancement

#3878 Fixed typehint in `types.rst` and replaced outdated reference to `manim.typing.Image` with `manim.typing.PixelArray`
  docs/source/contributing/docs/types.rst
Labels: documentation, pr:easy review

#3893 Improve line rendering performance by decreasing redundant subdivision count
  manim/mobject/three_d/three_dimensions.py
  tests/test_graphical_units/control_data/threed/AddFixedInFrameMobjects.npz
  tests/test_graphical_units/control_data/threed/AmbientCameraMove.npz
  tests/test_graphical_units/control_data/threed/Arrow3D.npz
  tests/test_graphical_units/control_data/threed/Axes.npz
  tests/test_graphical_units/control_data/threed/CameraMove.npz
  tests/test_graphical_units/control_data/threed/CameraMoveAxes.npz
  tests/test_graphical_units/control_data/threed/Cone.npz
  tests/test_graphical_units/control_data/threed/Cube.npz
  tests/test_graphical_units/control_data/threed/Cylinder.npz
  tests/test_graphical_units/control_data/threed/Dot3D.npz
  tests/test_graphical_units/control_data/threed/Line3D.npz
  tests/test_graphical_units/control_data/threed/MovingVertices.npz
  tests/test_graphical_units/control_data/threed/Sphere.npz
  tests/test_graphical_units/control_data/threed/SurfaceColorscale.npz
  tests/test_graphical_units/control_data/threed/Torus.npz
  tests/test_graphical_units/control_data/threed/Y_Direction.npz
Labels: performance

#3926 Fix typehints of `ParametricFunction`
  manim/mobject/graphing/functions.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
Labels: typehints

#3964 Allow :class:`.SurroundingRectangle` to accept multiple Mobjects
  docs/source/examples.rst
  manim/animation/indication.py
  manim/mobject/geometry/shape_matchers.py
  tests/module/mobject/geometry/test_unit_geometry.py
Labels: enhancement
