Repository ManimCommunity/manim, pull requests merged in 2024-06, with the labels that each got.

#3812 Fix MacOS LaTeX CI
  .github/manimdependency.json
Labels: maintenance

#3732 Fixed infinite loop in OpenGL `BackgroundRectangle.get_color()`
  manim/mobject/opengl/opengl_vectorized_mobject.py
Labels: pr:bugfix, opengl

#3785 Rewrite Animation Loop
  example_scenes/new_test_new.py
  example_scenes/test_new_rendering.py
  manim/__init__.py
  manim/cli/render/render_options.py
  manim/renderer/cairo_renderer.py
  manim/renderer/opengl_renderer.py
  manim/renderer/opengl_renderer_window.py
  manim/renderer/opengl_shader_program.py
  manim/renderer/render_manager.py
  manim/renderer/renderer.py
  manim/scene/scene.py
  poetry.lock
Labels: experimental

#3669 docs(contributing): add manim.typing guide
  docs/source/contributing/docs.rst
  docs/source/contributing/docs/types.rst
  docs/source/contributing/docs/typings.rst
Labels: documentation, typehints

#3706 Fixed `Arrow3D.put_start_and_end_on()` to use the actual end of the arrow
  manim/mobject/three_d/three_dimensions.py
  tests/test_graphical_units/test_threed.py
Labels: pr:bugfix

#3767 Optimized `manim.utils.bezier.get_smooth_cubic_bezier_handle_points()`
  manim/mobject/types/vectorized_mobject.py
  manim/utils/bezier.py
  tests/module/utils/test_bezier.py
Labels: performance

#3715 Doc: add docstrings to Brace
  manim/mobject/svg/brace.py
Labels: documentation
