Repository ManimCommunity/manim, pull requests merged in 2025-08, with the labels that each got.

#4125 Add type annotations for most of `camera` and `mobject.graphing`
  manim/camera/camera.py
  manim/camera/moving_camera.py
  manim/camera/multi_camera.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/functions.py
  manim/mobject/graphing/number_line.py
  manim/mobject/graphing/probability.py
  manim/mobject/graphing/scale.py
  manim/mobject/types/image_mobject.py
  mypy.ini
Labels: typehints

#4068 Add `VectorNDLike` type aliases
  docs/source/contributing/docs/types.rst
  manim/mobject/geometry/arc.py
  manim/mobject/geometry/line.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/svg/brace.py
  manim/mobject/text/numbers.py
  manim/mobject/three_d/three_dimensions.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/scene/vector_space_scene.py
  manim/typing.py
  manim/utils/paths.py
  manim/utils/space_ops.py
Labels: typehints

#4370 Fix Sphinx exceptions when trying to build documentation via latex / as pdf
  docs/source/conf.py
  manim/utils/docbuild/autocolor_directive.py
  manim/utils/docbuild/manim_directive.py
Labels: documentation

#4384 Exclude check for cyclic imports by CodeQL
  .github/codeql.yml
Labels: testing

#4360 Properly define `init_points` methods for use in OpenGL instead of defining `init_points = generate_points`
  manim/mobject/geometry/arc.py
  manim/mobject/geometry/line.py
  manim/mobject/graphing/functions.py
  manim/mobject/svg/svg_mobject.py
Labels: maintenance

#4353 Refactor imports from `collections.abc`, `typing` and `typing_extensions` for Python 3.9
  .github/scripts/ci_build_cairo.py
  manim/animation/animation.py
  manim/animation/changing.py
  manim/animation/composition.py
  manim/animation/creation.py
  manim/animation/fading.py
  manim/animation/growing.py
  manim/animation/numbers.py
  manim/animation/rotation.py
  manim/animation/speedmodifier.py
  manim/animation/transform.py
  manim/animation/updaters/mobject_update_utils.py
  manim/animation/updaters/update.py
  manim/camera/camera.py
  manim/cli/checkhealth/checks.py
  manim/cli/default_group.py
  manim/mobject/frame.py
  manim/mobject/geometry/arc.py
  manim/mobject/geometry/boolean_ops.py
  manim/mobject/geometry/labeled.py
  manim/mobject/geometry/line.py
  manim/mobject/geometry/polygram.py
  manim/mobject/geometry/tips.py
  manim/mobject/graphing/coordinate_systems.py
  manim/mobject/graphing/functions.py
  manim/mobject/graphing/number_line.py
  manim/mobject/logo.py
  manim/mobject/matrix.py
  manim/mobject/mobject.py
  manim/mobject/opengl/opengl_mobject.py
  manim/mobject/opengl/opengl_vectorized_mobject.py
  manim/mobject/table.py
  manim/mobject/three_d/three_dimensions.py
  manim/mobject/types/image_mobject.py
  manim/mobject/types/point_cloud_mobject.py
  manim/mobject/types/vectorized_mobject.py
  manim/mobject/vector_field.py
  manim/renderer/cairo_renderer.py
  manim/renderer/vectorized_mobject_rendering.py
  manim/scene/scene.py
  manim/scene/vector_space_scene.py
  manim/typing.py
  manim/utils/bezier.py
  manim/utils/caching.py
  manim/utils/deprecation.py
  manim/utils/hashing.py
  manim/utils/iterables.py
  manim/utils/module_ops.py
  manim/utils/opengl.py
  manim/utils/simple_functions.py
  manim/utils/space_ops.py
  manim/utils/testing/_test_class_makers.py
  manim/utils/testing/frames_comparison.py
Labels: maintenance

#4390 Allow passing a tuple to `buff` in `SurroundingRectangle` to specify buffer in x and y direction independently
  manim/mobject/geometry/shape_matchers.py
  tests/module/mobject/geometry/test_unit_geometry.py
Labels: enhancement

#4401 Fix some config options specified via `--config_file` not being respected properly
  manim/_config/utils.py
  manim/cli/render/global_options.py
  tests/test_scene_rendering/test_cli_flags.py
Labels: pr:bugfix
