Repository ManimCommunity/manim, pull requests merged in 2025-01, with the labels that each got.

#4108 Remove duplicate __all__ declarations in vectorized_mobject.py
  manim/mobject/types/vectorized_mobject.py
Labels: enhancement

#4102 Remove PT004 from Ruff ignore
  pyproject.toml
Labels: pr:easy review, maintenance

#4089 Fix of ImageMobject opacity bug
  manim/utils/bezier.py
  tests/module/utils/test_bezier.py
Labels: pr:bugfix

#4116 Fix broken link to Poetry installation in contribution docs
  docs/source/contributing/development.rst
Labels: documentation

#4069 Add Noto fonts install command to Dockerfile
  docker/Dockerfile
Labels: maintenance

#4115 Completely rewrite `Code` mobject + add support for short notation RGB(A) hex code specifications to `ManimColor`
  manim/mobject/text/code_mobject.py
  manim/utils/color/core.py
  mypy.ini
  poetry.lock
  pyproject.toml
  tests/module/utils/test_manim_color.py
  tests/test_code_mobject.py
Labels: refactor, breaking changes

#4121 Bump typing extensions minimum version
  poetry.lock
  pyproject.toml
Labels: pr:bugfix, dependencies

#4127 Add docstring to :meth:`.Mobject.get_family`
  manim/mobject/mobject.py
Labels: documentation

#4131 Fix link formatting and clarify the distinction between Manim versions in index.rst
  docs/source/index.rst
Labels: documentation
