Repository ManimCommunity/manim, pull requests merged in 2025-06, with the labels that each got.

#4274 Fix formatting of color space documentation
  manim/utils/color/core.py
Labels: documentation, pr:easy review

#4278 docs: add explanation about the rate_func in the custom animation
  docs/source/tutorials/building_blocks.rst
Labels: documentation

#4283 Fixed artifact in docstring of Animation
  manim/animation/animation.py
Labels: documentation

#4147 Refactor `Rotating` and add docstrings to `Mobject.rotate()` and `Rotating`
  docs/source/examples.rst
  manim/animation/rotation.py
  manim/mobject/mobject.py
Labels: documentation, refactor, breaking changes

#4213 Fix default config of `manim init project` to use correct `pixel_height` and `pixel_width`
  manim/cli/init/commands.py
Labels: pr:bugfix

#4313 Handle opacity and transparent images
  manim/mobject/types/image_mobject.py
Labels: pr:bugfix
