Repository ManimCommunity/manim, pull requests merged in 2025-07, with the labels that each got.

#4332 Add zero to vmobject points to remove negative zeros in `get_mobject_key`
  manim/animation/transform_matching_parts.py
Labels: enhancement

#4322 Adding type annotations to polyhedra.py and matrix.py
  manim/mobject/matrix.py
  manim/mobject/three_d/polyhedra.py
  mypy.ini
Labels: enhancement, typehints

#4319 Ensure `stroke_width` attribute of `SVGMobject` is not set to `None`
  manim/mobject/svg/svg_mobject.py
Labels: pr:bugfix

#4003 Fix `Prism` incorrectly rendering with `dimensions=[2, 2, 2]` in OpenGL
  manim/mobject/three_d/three_dimensions.py
Labels: pr:bugfix, enhancement, opengl

#4357 Optimize `always_redraw()` by reducing `Mobject` copying in `Mobject.become()`
  manim/mobject/mobject.py
Labels: performance, easy
