Repository ManimCommunity/manim, pull requests merged in 2025-02, with the labels that each got.

#4138 Change project management tool from poetry to uv
  .codespellrc
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  .github/workflows/release-publish-documentation.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  docs/source/contributing/development.md
  docs/source/contributing/development.rst
  docs/source/plugins.rst
  poetry.lock
  pyproject.toml
  tests/test_plugins/test_plugins.py
  uv.lock
Labels: infrastructure

#4150 Re-add ffmpeg as dependency within Docker image
  docker/Dockerfile
Labels: pr:bugfix, dependencies

#4159 Fix environment formating for Tex() mobject
  manim/utils/tex.py
  tests/module/utils/test_tex.py
Labels: pr:bugfix

#4144 Improved consistency of rate_function implementations
  manim/utils/rate_functions.py
Labels: maintenance

#4164 Make new `Code` mobject compatible with OpenGL renderer
  manim/mobject/geometry/shape_matchers.py
  manim/mobject/text/code_mobject.py
Labels: pr:bugfix, opengl
